package mumble;

/*
 * Mumble is the language of the SQL Parser AST Tree. It provides a list of simplified grouping names for repeating portions of the abstract syntax tree
 * generated by the SqlParserEventWalker. Each of the constants listed act as the "key" or signifier for a specific node in the AST which is constructed
 * from the parser's output. These constants are used to identify and manipulate the nodes in the tree. The project document "SQL Parse Event Walker" provides
 * a detailed description of the structure and purpose of each constant.
 */
public final class MumbleConstants {

	public static final String MUMBLE_ALIAS_KEY = "alias";
	public static final String MUMBLE_AND_KEY = "and";
	public static final String MUMBLE_ASSIGNMENTS_KEY = "assignments";
	public static final String MUMBLE_BETWEEN_KEY = "between";
	public static final String MUMBLE_BRACKET_FRAME_KEY = "bracket";
	public static final String MUMBLE_BRACKET_DIRECTION_KEY = "direction";
	public static final String MUMBLE_CALCULATION_KEY = "calc";
	public static final String MUMBLE_CASE_KEY = "case";
	public static final String MUMBLE_CLAUSES_KEY = "clauses";
	public static final String MUMBLE_COLUMN_KEY = "column";
	public static final String MUMBLE_COLUMNS_KEY = "columns";
	public static final String MUMBLE_COLUMN_TREE_KEY = "COLUMN";
	public static final String MUMBLE_CONCATENATE_KEY = "concatenate";
	public static final String MUMBLE_CONDITION_KEY = "condition";
	public static final String MUMBLE_CONDITION_TREE_KEY = "CONDITION";
	public static final String MUMBLE_DATATYPE_KEY = "data_type";
	public static final String MUMBLE_DATABASE_NAME_KEY = "dbname";
	public static final String MUMBLE_ELSE_KEY = "else";
	public static final String MUMBLE_ESCAPE_KEY = "escape";
	public static final String MUMBLE_FOLLOWING_KEY = "FOLLOWING";
	public static final String MUMBLE_FROM_KEY = "from";
	public static final String MUMBLE_FUNCTION_KEY = "function";
	public static final String MUMBLE_FUNCTION_NAME_KEY = "function_name";
	public static final String MUMBLE_GROUPBY_KEY = "groupby";
	public static final String MUMBLE_HAVING_KEY = "having";
	public static final String MUMBLE_ILIKE_ANY_KEY = "ilike_any";
	public static final String MUMBLE_IN_KEY = "in";
	public static final String MUMBLE_IN_LIST_KEY = "in_list";
	public static final String MUMBLE_IN_LIST_TREE_KEY = "IN_LIST";
	public static final String MUMBLE_INSERT_KEY = "insert";
	public static final String MUMBLE_INSERT_TREE_KEY = "INSERT";
	public static final String MUMBLE_INSERT_INTO_KEY = "insert_into";
	public static final String MUMBLE_INSERT_INTO_OVERWRITE_KEY = "insert_overwrite_into";
	public static final String MUMBLE_INTERSECT_KEY = "intersect";
	public static final String MUMBLE_INTO_KEY = "into";
	public static final String MUMBLE_ITEM_KEY = "item";
	public static final String MUMBLE_JOIN_EXTENSION_KEY = "extension";
	public static final String MUMBLE_JOIN_EXTENSION_TREE_KEY = "JOIN_EXTENSION";
	public static final String MUMBLE_JOIN_KEY = "join";
	public static final String MUMBLE_JOIN_ON_KEY = "on";
	public static final String MUMBLE_LEFT_FACTOR_KEY = "left";
	public static final String MUMBLE_LENGTH_KEY = "length";
	public static final String MUMBLE_LIKE_ANY_KEY = "like_any";
	public static final String MUMBLE_LIKE_ANY_LIST_KEY = "like_any_list";
	public static final String MUMBLE_LIMIT_KEY = "limit";
	public static final String MUMBLE_LIST_KEY = "list";
	public static final String MUMBLE_LITERAL_KEY = "literal";
	public static final String MUMBLE_LOOKUP_KEY = "lookup";
	public static final String MUMBLE_MATRIX_KEY = "matrix";
	public static final String MUMBLE_NAME_KEY = "name";
	public static final String MUMBLE_NOT_IN_LIST_KEY = "not_in_list";
	public static final String MUMBLE_NOT_LIKE_ANY_LIST_KEY = "not_like_any_list";
	public static final String MUMBLE_NOT_KEY = "not";
	public static final String MUMBLE_NULL_LITERAL_KEY = "null_literal";
	public static final String MUMBLE_NULL_ORDER_KEY = "null_order";
	public static final String MUMBLE_OFFSET_KEY = "offset";
	public static final String MUMBLE_OPERATOR_KEY = "operator";
	public static final String MUMBLE_OR_KEY = "or";
	public static final String MUMBLE_ORDERBY_KEY = "orderby";
	public static final String MUMBLE_OVER_KEY = "over";
	public static final String MUMBLE_PARAMETERS_KEY = "parameters";
	public static final String MUMBLE_PARENTHESES_KEY = "parentheses";
	public static final String MUMBLE_PARTITION_BY_KEY = "partition_by";
	public static final String MUMBLE_PARTS_KEY = "parts";
	public static final String MUMBLE_INSERT_PREAMBLE_KEY = "Preamble";
	public static final String MUMBLE_PRECISION_KEY = "precision";
	public static final String MUMBLE_PRECEDING_KEY = "PRECEDING";
	public static final String MUMBLE_PREDICAND_KEY = "predicand";
	public static final String MUMBLE_PREDICAND_TREE_KEY = "PREDICAND";
	public static final String MUMBLE_PUML_CONSTANT_KEY = "puml_constant";
	public static final String MUMBLE_QUALIFIER_KEY = "qualifier";
	public static final String MUMBLE_QUERY_KEY = "query";
	public static final String MUMBLE_QUERY_TREE_KEY = "QUERY";
	public static final String MUMBLE_RANGE_BEGIN_KEY = "begin";
	public static final String MUMBLE_RANGE_END_KEY = "end";
	public static final String MUMBLE_RETURNING_KEY = "returning";
	public static final String MUMBLE_RIGHT_FACTOR_KEY = "right";
	public static final String MUMBLE_ROW_KEY = "row";
	public static final String MUMBLE_SCALE_KEY = "scale";
	public static final String MUMBLE_SCHEMA_KEY = "schema";
	public static final String MUMBLE_SELECT_KEY = "select";
	
	public static final String MUMBLE_SELECT_DIRECTION_KEY = "select_from";
	public static final String MUMBLE_NULL_HANDLING_KEY = "null_handle";
	
	public static final String MUMBLE_SET_KEY = "set";
	public static final String MUMBLE_SORT_ORDER_KEY = "sort_order";
	public static final String MUMBLE_SQL_TREE_KEY = "SQL";
	public static final String MUMBLE_SUBSTITUTION_KEY = "substitution";
	public static final String MUMBLE_SYMMETRY_KEY = "symmetry";
	public static final String MUMBLE_TABLE_KEY = "table";
	public static final String MUMBLE_TABLE_REF_KEY = "table_ref";
	public static final String MUMBLE_THEN_KEY = "then";
	public static final String MUMBLE_TO_KEY = "to";
	public static final String MUMBLE_TRIM_CHARACTER_KEY = "trim_character";
	public static final String MUMBLE_TUPLE_TREE_KEY = "TUPLE";
	public static final String MUMBLE_TYPE_KEY = "type";
	public static final String MUMBLE_UNKNOWN_KEY = "unknown";
	public static final String MUMBLE_UNION_KEY = "union";
	public static final String MUMBLE_UPDATE_KEY = "update";
	public static final String MUMBLE_VALUES_TREE_KEY = "VALUES";
	public static final String MUMBLE_VALUES_KEY = "values";
	public static final String MUMBLE_VALUE_KEY = "value";
	public static final String MUMBLE_WHEN_KEY = "when";
	public static final String MUMBLE_WHERE_KEY = "where";
	public static final String MUMBLE_WINDOW_FUNCTION_KEY = "window_function";
	public static final String MUMBLE_WITH_KEY = "with";

}
