package mumble;

import java.lang.reflect.Field;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

/*
 * Mumble is the language of the SQL Parser AST Tree. It provides a list of simplified grouping names for repeating portions of the abstract syntax tree
 * generated by the SqlParserEventWalker. Each of the constants listed act as the "key" or signifier for a specific node in the AST which is constructed
 * from the parser's output. These constants are used to identify and manipulate the nodes in the tree. The project document "SQL Parse Event Walker" provides
 * a detailed description of the structure and purpose of each constant.
 */
public final class MumbleConstants {

    public static final String MUMBLE_ALIAS_KEY = "alias";
    public static final String MUMBLE_AND_KEY = "and";
    public static final String MUMBLE_ALTER_KEY = "alter";
    public static final String MUMBLE_ARGUMENT_KEY = "argument";
    public static final String MUMBLE_ASSIGNMENTS_KEY = "assignments";
    public static final String MUMBLE_BETWEEN_KEY = "between";
    public static final String MUMBLE_BRACKET_DIRECTION_KEY = "direction";
    public static final String MUMBLE_BRACKET_FRAME_KEY = "bracket";
    public static final String MUMBLE_CALCULATION_KEY = "calc";
    public static final String MUMBLE_CASE_KEY = "case";
    public static final String MUMBLE_CAST_FUNCTION_NAME = "cast";
    /** Semantic {@link #MUMBLE_TYPE_KEY} value for cast function nodes (including {@code ::} casts). */
    public static final String MUMBLE_CAST_FUNCTION_TYPE = "CAST";
    public static final String MUMBLE_CLAUSES_KEY = "clauses";
    public static final String MUMBLE_COLUMNS_KEY = "columns";
    public static final String MUMBLE_COLUMN_KEY = "column";
    public static final String MUMBLE_CONCATENATE_KEY = "concatenate";
    public static final String MUMBLE_CONDITION_KEY = "condition";
    public static final String MUMBLE_CREATE_KEY = "create";
    public static final String MUMBLE_CTE_KEY = "cte";
    /** Named scope registry (WITH CTEs, inherited outer aliases) visible to nested subqueries. */
    public static final String MUMBLE_CONTEXT_LIST_KEY = "context_list";
    public static final String MUMBLE_OUTER_CONTEXT_LIST_KEY = "outer_context_list_backup";
    public static final String MUMBLE_OUTER_DEF_ENTRIES_KEY = "outer_def_entries_backup"; // Saved outer def_* symbol-table entries before a nested WITH clause absorbs them
    /** Saved outer {@link #MUMBLE_TABLE_ALIAS_KEY} map before a nested WITH clause seeds its own aliases. */
    public static final String MUMBLE_OUTER_TABLE_ALIAS_KEY = "mumble_outer_table_alias";
    /** Immutable alias snapshot captured when a nested scope inherits visible outer scope. */
    public static final String MUMBLE_INHERITED_VISIBLE_ALIASES_KEY = "inherited_visible_aliases";
    /** Alias keys registered by this frame's local {@code FROM} clause (not inherited-only snapshots). */
    public static final String MUMBLE_LOCAL_FROM_REGISTERED_ALIASES_KEY = "local_from_registered_aliases";
    public static final String MUMBLE_DATABASE_NAME_KEY = "dbname";
    public static final String MUMBLE_DATATYPE_KEY = "data_type";
    public static final String MUMBLE_DELETE_KEY = "delete";
    public static final String MUMBLE_DEFAULT_VALUES_KEY = "default_values";
    /** Submap grouping predicandN, in_listN, existsN, and quantifiedN query references on a scope. */
    public static final String MUMBLE_DEPENDENT_QUERIES_KEY = "dependent_queries";
    /** Clause context label on each {@link #MUMBLE_DEPENDENT_QUERIES_KEY} entry ({@code query=queryN} sibling). */
    public static final String MUMBLE_DEPENDENT_QUERY_TYPE_KEY = "type";
    public static final String MUMBLE_DEPENDENT_QUERY_CONTEXT_INTERFACE = "interface";
    public static final String MUMBLE_DEPENDENT_QUERY_CONTEXT_FILTERS = "filters";
    public static final String MUMBLE_DEPENDENT_QUERY_CONTEXT_GROUP_BY = "group_by";
    public static final String MUMBLE_DEPENDENT_QUERY_CONTEXT_ORDER_BY = "order_by";
    public static final String MUMBLE_DROP_KEY = "drop";
    public static final String MUMBLE_ELSE_KEY = "else";
    public static final String MUMBLE_ESCAPE_KEY = "escape";
    public static final String MUMBLE_EXISTS_KEY = "exists";
    public static final String MUMBLE_EXTRACT_KEY = "extract";
    public static final String MUMBLE_EXTRACT_PART_KEY = "part";
    public static final String MUMBLE_EXTRACT_PART_FORM_KEY = "part_form";
    public static final String MUMBLE_EXTRACT_PART_FORM_KEYWORD = "KEYWORD";
    public static final String MUMBLE_EXTRACT_PART_FORM_STRING = "STRING";
    public static final String MUMBLE_EXTRACT_SOURCE_KEY = "source";
    public static final String MUMBLE_EXTRACT_SOURCE_TYPE_KEY = "source_type";
    /** {@link #MUMBLE_EXTRACT_SOURCE_TYPE_KEY} values for typed SQL literals in extract sources. */
    public static final String MUMBLE_EXTRACT_SOURCE_TYPE_DATE = "DATE";
    public static final String MUMBLE_EXTRACT_SOURCE_TYPE_TIME = "TIME";
    public static final String MUMBLE_EXTRACT_SOURCE_TYPE_TIMESTAMP = "TIMESTAMP";
    public static final String MUMBLE_EXTRACT_SOURCE_TYPE_INTERVAL = "INTERVAL";
    /** Distinguishes {@link #MUMBLE_EXTRACT_KEY} produced by {@code EXTRACT(...)} vs {@code DATE_PART(...)}. */
    public static final String MUMBLE_EXTRACT_INVOCATION_KEY = "invocation";
    public static final String MUMBLE_EXTRACT_INVOCATION_DATE_PART = "DATE_PART";
    public static final String MUMBLE_FILES_KEY = "files";
    public static final String MUMBLE_FILE_FORMAT_KEY = "file_format";
    public static final String MUMBLE_FILTERS_KEY = "filters";
    public static final String MUMBLE_FOLLOWING_KEY = "FOLLOWING";
    public static final String MUMBLE_FOR_KEY = "for";
    public static final String MUMBLE_FROM_KEY = "from";
    public static final String MUMBLE_FUNCTION_KEY = "function";
    public static final String MUMBLE_FUNCTION_NAME_KEY = "function_name";
    public static final String MUMBLE_GROUPBY_KEY = "groupby";
    public static final String MUMBLE_GROUPED_BY_KEY = "grouped_by";
    public static final String MUMBLE_HAVING_KEY = "having";
    public static final String MUMBLE_IGNORE_CASE_KEY = "ignore_case";
    public static final String MUMBLE_ILIKE_ANY_KEY = "ilike_any";
    public static final String MUMBLE_INPUT_KEY = "input";
    public static final String MUMBLE_INSERT_INTO_KEY = "insert_into";
    public static final String MUMBLE_INSERT_INTO_OVERWRITE_KEY = "insert_overwrite_into";
    public static final String MUMBLE_INSERT_KEY = "insert";
    public static final String MUMBLE_INSERT_PREAMBLE_KEY = "preamble";
    public static final String MUMBLE_INTERFACE_KEY = "interface"; // Special key for the symbol table to store interface references
    public static final String MUMBLE_INTERSECT_KEY = "intersect";
    public static final String MUMBLE_INTO_KEY = "into";
    public static final String MUMBLE_IN_KEY = "in";
    public static final String MUMBLE_IN_LIST_KEY = "in_list";
    public static final String MUMBLE_ITEM_KEY = "item";
    public static final String MUMBLE_JSON_PATH_KEY = "json_path";
    public static final String MUMBLE_JINJA_TABLE_KEY = "jinja_table";
    public static final String MUMBLE_JINJA_VARIABLE_KEY = "jinja_variable";
    public static final String MUMBLE_JOB_ID_KEY = "job_id";
    public static final String MUMBLE_JOIN_EXTENSION_KEY = "extension";
    public static final String MUMBLE_JOIN_KEY = "join";
    public static final String MUMBLE_JOIN_ON_KEY = "on";
    public static final String MUMBLE_KIND_KEY = "kind";
    public static final String MUMBLE_LABEL_KEY = "label";
    public static final String MUMBLE_LEFT_FACTOR_KEY = "left";
    public static final String MUMBLE_LENGTH_KEY = "length";
    public static final String MUMBLE_LHS_UNRESOLVED_COLUMNS_KEY = "lhs_unresolved_columns"; // Special key for LHS assignment column references in update statements
    public static final String MUMBLE_LIKE_ANY_KEY = "like_any";
    public static final String MUMBLE_LIKE_ANY_LIST_KEY = "like_any_list";
    public static final String MUMBLE_LIMIT_KEY = "limit";
    public static final String MUMBLE_LIST_KEY = "list";
    public static final String MUMBLE_LITERAL_KEY = "literal";
    public static final String MUMBLE_LOCATION_KEY = "location";
    public static final String MUMBLE_LOOKUP_KEY = "lookup";
    public static final String MUMBLE_MATRIX_KEY = "matrix";
    public static final String MUMBLE_MAX_FILE_COUNT_KEY = "max_file_count";
    public static final String MUMBLE_MAX_RECORDS_PER_FILE_KEY = "max_records_per_file";
    public static final String MUMBLE_MODE_KEY = "mode";
    public static final String MUMBLE_MODIFIER_KEY = "modifier";
    public static final String MUMBLE_NAME_KEY = "name";
    public static final String MUMBLE_NOT_IN_LIST_KEY = "not_in_list";
    public static final String MUMBLE_NOT_KEY = "not";
    public static final String MUMBLE_NOT_LIKE_ANY_LIST_KEY = "not_like_any_list";
    public static final String MUMBLE_NULL_HANDLING_KEY = "null_handle";
    public static final String MUMBLE_NULL_LITERAL_KEY = "null_literal";
    public static final String MUMBLE_NULL_ORDER_KEY = "null_order";
    public static final String MUMBLE_ON_CONFLICT_KEY = "on_conflict";
    public static final String MUMBLE_NULLS_POLICY_KEY = "nulls";
    public static final String MUMBLE_OFFSET_KEY = "offset";
    public static final String MUMBLE_OPERAND_KEY = "operand";
    public static final String MUMBLE_OPERATOR_KEY = "operator";
    public static final String MUMBLE_OPTIONS_KEY = "options";
    public static final String MUMBLE_ORDERBY_KEY = "orderby";
    public static final String MUMBLE_ORDERED_BY_KEY = "ordered_by";
    /** Archived flat column-ref list for {@code OVER (PARTITION BY …)} at convert egress. */
    public static final String MUMBLE_WINDOW_PARTITION_BY_KEY = "window_partition_by";
    /** Archived flat column-ref list for in-{@code OVER} {@code ORDER BY} at convert egress. */
    public static final String MUMBLE_WINDOW_ORDERED_BY_KEY = "window_ordered_by";
    public static final String MUMBLE_OR_KEY = "or";
    public static final String MUMBLE_OUTER_KEY = "outer";
    public static final String MUMBLE_OVER_KEY = "over";
    public static final String MUMBLE_PARAMETERS_KEY = "parameters";
    public static final String MUMBLE_PARENTHESES_KEY = "parentheses";
    public static final String MUMBLE_PARTITION_BY_KEY = "partition_by";
    public static final String MUMBLE_PARTS_KEY = "parts";
    public static final String MUMBLE_PARENT_CTE_KEY = "parent_cte"; // Optional key for inherited CTE chain metadata
    public static final String MUMBLE_PATH_KEY = "path";
    public static final String MUMBLE_PRECEDING_KEY = "PRECEDING";
    public static final String MUMBLE_PRECISION_KEY = "precision";
    public static final String MUMBLE_PREDICAND_KEY = "predicand";
    public static final String MUMBLE_PUML_CONSTANT_KEY = "puml_constant";
    public static final String MUMBLE_QUALIFIER_KEY = "qualifier";
    public static final String MUMBLE_QUALIFY_KEY = "qualify";
    public static final String MUMBLE_QUANTIFIED_KEY = "quantified";
    public static final String MUMBLE_QUANTIFIER_KEY = "quantifier";
    public static final String MUMBLE_QUERY_DICTIONARY_KEY = "query_dictionary"; // Special key for the symbol table to store query references
    public static final String MUMBLE_QUERY_KEY = "query";
    public static final String MUMBLE_RANGE_BEGIN_KEY = "begin";
    public static final String MUMBLE_RANGE_END_KEY = "end";
    public static final String MUMBLE_RECURSIVE_KEY = "recursive";
    public static final String MUMBLE_RETURNING_KEY = "returning";
    public static final String MUMBLE_RIGHT_FACTOR_KEY = "right";
    public static final String MUMBLE_ROWCOUNT_KEY = "rowcount";
    public static final String MUMBLE_ROW_KEY = "row";
    public static final String MUMBLE_SCALAR_SUBQUERY_ALIASES_KEY = "scalar_subquery_aliases"; // Special key for the symbol table to store scalar subquery aliases
    public static final String MUMBLE_SCALE_KEY = "scale";
    public static final String MUMBLE_SCHEMA_KEY = "schema";
    public static final String MUMBLE_SELECT_DIRECTION_KEY = "select_from";
    /** Set operator that introduced this participant into its parent set-op scope ({@code UNION}, {@code EXCEPT}, or {@code INTERSECTION}). Anchor branch omits. */
    public static final String MUMBLE_SETOP_KEY = "setop";
    public static final String MUMBLE_SELECT_KEY = "select";
    public static final String MUMBLE_SET_KEY = "set";
    public static final String MUMBLE_TUPLE_KEY = SQLParserEndPoints.getLowerCaseValueForValue(SQLParserEndPoints.SQLPARSER_TUPLE_TREE_KEY);
    public static final String MUMBLE_JOIN_EXTENSION_TYPE_KEY = SQLParserEndPoints.getLowerCaseValueForValue(SQLParserEndPoints.SQLPARSER_JOIN_EXTENSION_TREE_KEY);
    public static final String MUMBLE_SORT_ORDER_KEY = "sort_order";
    public static final String MUMBLE_SUBSTITUTION_KEY = "substitution";
    public static final String MUMBLE_SYMMETRY_KEY = "symmetry";
    public static final String MUMBLE_TABLE_ALIAS_KEY = "table_alias";
    public static final String MUMBLE_TABLE_DICTIONARY_KEY = "table_dictionary"; // Special key for the symbol table to store table references
    public static final String MUMBLE_TABLE_FUNCTION_KEY = "table_function";
    public static final String MUMBLE_TABLE_KEY = "table";
    public static final String MUMBLE_TABLE_REF_KEY = "table_ref";
    public static final String MUMBLE_TARGET_TABLE_KEY = "target_table"; // Special key for DML target table references (INSERT/UPDATE)
    public static final String MUMBLE_THEN_KEY = "then";
    public static final String MUMBLE_TIMELIMIT_KEY = "timelimit";
    public static final String MUMBLE_TO_KEY = "to";
    public static final String MUMBLE_TRIM_CHARACTER_KEY = "trim_character";
    public static final String MUMBLE_TRUNCATE_KEY = "truncate";
    public static final String MUMBLE_TYPE_KEY = "type";
    public static final String MUMBLE_USING_KEY = "using";
    public static final String MUMBLE_UNION_KEY = "union";
    public static final String MUMBLE_UNKNOWN_KEY = "unknown";
    public static final String MUMBLE_PIVOT_KEY = "pivot";
    public static final String MUMBLE_PIVOT_LITERAL_KEY = "pivot_literal";
    public static final String MUMBLE_PIVOT_PREFIX_KEY = "pivot_prefix";
    public static final String MUMBLE_UNPIVOT_KEY = "unpivot";
    public static final String MUMBLE_UNRESOLVED_COLUMN_KEY = "unresolved_column"; // Special key for collecting unresolved column references in the symbol table
    public static final String MUMBLE_UPDATE_DICTIONARY_KEY = "update_dictionary"; // Special key for update statement assignment token references
    public static final String MUMBLE_UPDATE_KEY = "update";
    public static final String MUMBLE_VALUES_KEY = "values";
    public static final String MUMBLE_VALUE_KEY = "value";
    public static final String MUMBLE_WHEN_KEY = "when";
    public static final String MUMBLE_WHERE_KEY = "where";
    public static final String MUMBLE_WINDOW_FUNCTION_KEY = "window_function";
    public static final String MUMBLE_WITH_KEY = "with";
    
    // Maps to lookup constants by name or value
    private static final Map<String, String> NAME_TO_VALUE_MAP = new HashMap<>();
    private static final Map<String, String> VALUE_TO_NAME_MAP = new HashMap<>();
    
    // Static initializer block to populate maps using reflection
    static {
        try {
            for (Field field : MumbleConstants.class.getDeclaredFields()) {
                if (java.lang.reflect.Modifier.isStatic(field.getModifiers()) && 
                    field.getType() == String.class &&
                    field.getName().startsWith("MUMBLE_")) {
                    
                    String name = field.getName();
                    String value = (String) field.get(null);
                    
                    NAME_TO_VALUE_MAP.put(name, value);
                    VALUE_TO_NAME_MAP.put(value, name);
                }
            }
        } catch (IllegalAccessException e) {
            throw new ExceptionInInitializerError("Failed to initialize MumbleConstants maps: " + e.getMessage());
        }
    }
    
    /**
     * Returns an unmodifiable map of constant names to their values.
     * @return Map where keys are constant names (e.g., "MUMBLE_SELECT_KEY") and values are their string values (e.g., "select")
     */
    public static Map<String, String> getNameToValueMap() {
        return Collections.unmodifiableMap(NAME_TO_VALUE_MAP);
    }
    
    /**
     * Returns an unmodifiable map of constant values to their names.
     * @return Map where keys are constant values (e.g., "select") and values are their names (e.g., "MUMBLE_SELECT_KEY")
     */
    public static Map<String, String> getValueToNameMap() {
        return Collections.unmodifiableMap(VALUE_TO_NAME_MAP);
    }
    
    /**
     * Gets the constant name for a given value.
     * @param value The string value to look up
     * @return The name of the constant, or null if not found
     */
    public static String getNameForValue(String value) {
        return VALUE_TO_NAME_MAP.get(value);
    }
    
    /**
     * Gets the constant value for a given name.
     * @param name The constant name to look up
     * @return The value of the constant, or null if not found
     */
    public static String getValueForName(String name) {
        return NAME_TO_VALUE_MAP.get(name);
    }
}
