-- Bound-query CSV row 129 (~74k ASCII). Frozen from outstanding csv_row 130 handoff fixture.
select
CONCAT(TRY_TO_DATE(CONCAT(LEFT(ADMIT_DATE,7),'20',RIGHT(ADMIT_DATE,2))),' 00:00:00') ADMIT_DATE
,ADDRESS_LINE_1
,ADDRESS_LINE_2
,CASE WHEN ADMIT_SOURCE_VALUE IN ('Y') THEN 1 ELSE 0 END ADMIT_INDICATOR
,ANALYSIS_CUSTOM_FIELD_1
,ANALYSIS_CUSTOM_FIELD_2
,ANALYSIS_CUSTOM_FIELD_3
,ANALYSIS_CUSTOM_FIELD_4
,ANALYSIS_CUSTOM_FIELD_5
,CASE WHEN LEFT(ENTRY_TERM_SOURCE_VALUE,4) >= 2021 AND INQUIRY_SOURCE_VALUE = 'UG' AND STUDENT_TYPE_SOURCE_VALUE IN ('A','D') THEN 1 ELSE 0 END INCLUDE_IN_ANALYSIS
,APPLICATION_COMPLETION_DATE
,APPLICATION_START_DATE
,CONCAT(TRY_TO_DATE(APPLICATION_SUBMIT_DATE),' 00:00:00') APPLICATION_SUBMIT_DATE
,APPLICATION_TYPE
,APPLICATION_TYPE_SOURCE_VALUE
,CASE WHEN INQUIRY_SOURCE_VALUE = 'UG' AND APPLICATION_SUBMIT_DATE IS NOT NULL THEN 'PAPPL' ELSE NULL END AUDIENCE_CODE
,SUBSTRING(BIRTH_DAY,4,2) BIRTH_DAY
,LEFT(BIRTH_MONTH,2) BIRTH_MONTH
,RIGHT(BIRTH_YEAR,4) BIRTH_YEAR
,CAMPAIGN_YEAR
,CAMPUS_SOURCE_VALUE CAMPUS
,CAMPUS_TYPE
,HIGH_SCHOOL_CEEB_CODE
,CASE WHEN LENGTH(REGEXP_REPLACE(CELL_PHONE,'[^0-9]','')) = 10 THEN REGEXP_REPLACE(CELL_PHONE,'[^0-9]','') ELSE NULL END CELL_PHONE
,CITY
,NULL CLIENT_FILE_NAME
,SOURCE_SYSTEM_ID_FOR_THE_PERSON
,COHORT_DESC
,COMPLETED_APPLICATION_INDICATOR
,CASE WHEN COUNTRY_NAME = '157' THEN 'USA' ELSE NULL END COUNTRY_NAME
,CURRENT_UNDERGRAD_COLLEGE_SENIOR_INDICATOR
,CUSTOM_SEGMENT_01
,CUSTOM_SEGMENT_02
,CUSTOM_SEGMENT_03
,CUSTOM_SEGMENT_04
,DECISION_TYPE
,CASE WHEN LEFT(DENIED_SOURCE_VALUE,1) = 'V' THEN 1 ELSE DEFER_INDICATOR END DEFER_INDICATOR
,DEGREE_TYPE
,DEGREE_TYPE_SOURCE_VALUE
,CASE WHEN DENIED_SOURCE_VALUE = 'Y' THEN 1 ELSE DENIED_INDICATOR END DENIED_INDICATOR
,DEPOSIT_2_DATE
,DEPOSIT_2_INDICATOR
,DEPOSIT_DATE
,DEPOSIT_INDICATOR
,EMAIL_ADDRESS
,EMAIL_OPT_OUT_INDICATOR
,EMPLOYER
,CASE WHEN ENROLLED_SOURCE_VALUE = 'Y' AND ADMIT_SOURCE_VALUE = 'Y' THEN CONCAT(TRY_TO_DATE(ENROLL_DATE),' 00:00:00') ELSE NULL END ENROLL_DATE
,CASE WHEN ENROLLED_SOURCE_VALUE = 'Y' AND ADMIT_SOURCE_VALUE = 'Y' THEN 1 ELSE ENROLLED_INDICATOR END ENROLLED_INDICATOR
,ENROLL_TYPE
,CASE 
WHEN RIGHT(ENTRY_TERM_SOURCE_VALUE,2) = '40' THEN 'Fall' 
WHEN RIGHT(ENTRY_TERM_SOURCE_VALUE,2) = '35' THEN 'Summer' 
WHEN RIGHT(ENTRY_TERM_SOURCE_VALUE,2) = '70' THEN 'Spring'
ELSE NULL END ENTRY_TERM
,ENTRY_TERM_SOURCE_VALUE
,TO_NUMBER(CASE WHEN RIGHT(ENTRY_TERM_SOURCE_VALUE,2) = '40' OR RIGHT(ENTRY_TERM_SOURCE_VALUE,2) = '35' THEN TO_NUMBER(LEFT(ENTRY_TERM_SOURCE_VALUE,4))-1 ELSE LEFT(ENTRY_TERM_SOURCE_VALUE,4) END) ENTRY_YEAR
,ENTRY_YEAR_SOURCE_VALUE
,RACE
,RACE_2
,RACE_3
,RACE_4
,RACE_5
,RACE_6
,'U' ETHNICITY_ROLLUP
,DATE_FILE_WAS_RECEIVED_FROM_PARTNER
,FIRST_NAME
,FIRST_SOURCE_DESCRIPTION
,FIRST_SOURCE_SOURCE_VALUE
,FULL_PART_TIME
,CASE WHEN GENDER_SOURCE_VALUE IS NOT NULL THEN GENDER_SOURCE_VALUE ELSE GENDER END GENDER
,GMAT_COMPOSITE_SCORE
,GMAT_MAJOR
,GMAT_TEST_DATE
,GRE_COMPOSITE_SCORE
,GRE_EXAM_DATE
,GRE_MAJOR
,CASE WHEN LENGTH(REGEXP_REPLACE(HOME_PHONE,'[^0-9]','')) = 10 THEN REGEXP_REPLACE(HOME_PHONE,'[^0-9]','') ELSE NULL END HOME_PHONE
,INCOME
,INQUIRY_DATE
,INQUIRY_INDICATOR
,LAST_NAME
,LEAD_ELIGIBLE_FOR_MARKETING_EXPORT_INDICATOR
,LEAD_ELIGIBLE_FOR_PARTNER_ANALYSIS_INDICATOR
,LSAT_ACCOUNT_IDENTIFIER
,LSAT_COMPOSITE_SCORE
,LSAT_EXAM_DATE
,MAIL_OPT_OUT_INDICATOR
,CASE WHEN INQUIRY_SOURCE_VALUE = 'UG' AND APPLICATION_SUBMIT_DATE IS NOT NULL THEN 1 ELSE MARKETING_INDICATOR END MARKETING_INDICATOR
,MCAT_ACCOUNT_IDENTIFIER
,MCAT_COMP_SCORE
,MCAT_EXAM_DATE
,MIDDLE_NAME
,MILITARY_SERVICE_STATUS
,NCH_FILE_INDICATOR
,OPT_OUT_INDICATOR
,OTHER_AUDIENCE_INDICATOR
,OTHER_EXAM_DATE
,OTHER_EXAM_IDENTIFIER
,OTHER_EXAM_SCORE
,PARENT_EMAIL
,PARENT_FIRST_NAME
,PARENT_LAST_NAME
,EAB_ID_FROM_PARTNER
,PCAT_ACCOUNT_IDENTIFIER
,PCAT_COMP_SCORE
,PCAT_EXAM_DATE
,PREFERRED_NAME
,PREFIX
,PREVIOUS_COLLEGE_CEEB_CODE_1
,PREVIOUS_COLLEGE_CEEB_CODE_2
,PREVIOUS_COLLEGE_CEEB_CODE_3
,PREVIOUS_COLLEGE_GPA_1
,PREVIOUS_COLLEGE_GPA_2
,PREVIOUS_COLLEGE_GPA_3
,PREVIOUS_COLLEGE_GRAD_YEAR
,PREVIOUS_COLLEGE_GRAD_YEAR_1
,PREVIOUS_COLLEGE_GRAD_YEAR_2
,PREVIOUS_COLLEGE_GRAD_YEAR_3
,PREVIOUS_COLLEGE_MAJOR
,PREVIOUS_COLLEGE_NAME_1
,PREVIOUS_COLLEGE_NAME_2
,PREVIOUS_COLLEGE_NAME_3
,PREVIOUSLY_ENROLLED_INDICATOR
,HIGH_SCHOOL_GPA
,TO_NUMBER(CASE WHEN HISPANIC_LATINO_SOURCE_VALUE IS NOT NULL THEN HISPANIC_LATINO_SOURCE_VALUE ELSE HISPANIC_LATINO END) HISPANIC_LATINO
,SCHOOL_CONCENTRATION
,SCHOOL_IDENTIFIER
,SCHOOL_NAME
,SCHOOL_OF_STUDY
,CASE
WHEN school_program = 'AAADULTINSTR' THEN 'AA Adult Instruction/Training'
WHEN school_program = 'AAAPPLIEDCHE' THEN 'AA Applied Chemistry'
WHEN school_program = 'AABUSADM' THEN 'AA Business Administration'
WHEN school_program = 'AABUSADM14' THEN 'AA Business Administration'
WHEN school_program = 'AABUSINFO' THEN 'AA Bus Information Systems'
WHEN school_program = 'AACOMMART' THEN 'AA Communication Arts'
WHEN school_program = 'AAFASHDESN' THEN 'AA Fashion Design'
WHEN school_program = 'AAFASHMERCH' THEN 'AA Fashion Merchandising'
WHEN school_program = 'AAFASHMGMT' THEN 'AA Fashion Management'
WHEN school_program = 'AAGENERALSTD' THEN 'AA General Studies'
WHEN school_program = 'AAGENSTD14' THEN 'AA General Studies'
WHEN school_program = 'AAINFOSYST14' THEN 'AA Information Systems'
WHEN school_program = 'AAINFOTECH' THEN 'AA Information Technology'
WHEN school_program = 'AAINFOTECH14' THEN 'AA Information Technology'
WHEN school_program = 'AAINTENVDES' THEN 'AA Interior Environment Design'
WHEN school_program = 'AALIBARTS' THEN 'AA Liberal Arts'
WHEN school_program = 'AASOTA' THEN 'AAS Occupational Therapy Asst'
WHEN school_program = 'AASRT' THEN 'AAS Respiratory Therapy'
WHEN school_program = 'ASCARDIAC' THEN 'AS Cardiac Rhythm Analysis Pro'
WHEN school_program = 'ASHEALTHSCI' THEN 'AS Health Sciences'
WHEN school_program = 'ASHLTHSCI15' THEN 'AS Health Sciences/General'
WHEN school_program = 'ASHSADMIN' THEN 'AS Health Sci/Administration'
WHEN school_program = 'ASHSADMIN15' THEN 'AS Health Sci/Administration'
WHEN school_program = 'ASHSBLCD15' THEN 'AS Hth Sci/Cert Bill/Coding Sp'
WHEN school_program = 'ASHSCBILLCOD' THEN 'AS Hth Sci/Cert Bill/Coding Sp'
WHEN school_program = 'ASHSCHTHINFO' THEN 'AS Hlth Sci/Reg Hlth Info Tech'
WHEN school_program = 'ASHSCMEDTRAN' THEN 'AS Hth Sci/Reg Med Transcript'
WHEN school_program = 'ASHSCMOA' THEN 'AS Hth Sci/Cert Med Admin Asst'
WHEN school_program = 'ASHSCRAT' THEN 'AS Hth Sci/Card Rhy Anlys Tech'
WHEN school_program = 'ASHSHLTRECSP' THEN 'AS Hlth Sci/Crt El Hlth Rec Sp'
WHEN school_program = 'ASHSNUTR15' THEN 'AS Health Science Nutrition'
WHEN school_program = 'ASHSOTA' THEN 'AS Hlth Sci/Occup Therapy Asst'
WHEN school_program = 'ASHSOTA15' THEN 'AS Hlth Sci/Occup Therapy Asst'
WHEN school_program = 'ASHSRESP13' THEN 'AS Health Science/Resp Therapy'
WHEN school_program = 'ASHSRESP15' THEN 'AS Health Science/Resp Therapy'
WHEN school_program = 'ASHSRT' THEN 'AS Hlth Sci/Respiratory Therap'
WHEN school_program = 'ASMEDADMIN' THEN 'AS Medical Admin Assistant'
WHEN school_program = 'ASMEDINSCOD' THEN 'AS Med Insurance Coding Spec'
WHEN school_program = 'ASNUTRSCI' THEN 'AS Nutrition Sciences'
WHEN school_program = 'ASREGHLTHINF' THEN 'AS Reg Hlth Inform Technician'
WHEN school_program = 'ASREGMEDTRAN' THEN 'AS Reg Medical Transcription'
WHEN school_program = 'AUDIT' THEN 'Audit'
WHEN school_program = 'BA CRJSOC920' THEN 'BA Criminal Justice/Sociology'
WHEN school_program = 'BA HSIA9238' THEN 'BA Hist/International Affairs'
WHEN school_program = 'BA632078' THEN 'BA English/Political Science'
WHEN school_program = 'BA791035' THEN 'BA Criminal Justice/Sociology'
WHEN school_program = 'BA807162' THEN 'BA Criminal Justice/Psychology'
WHEN school_program = 'BA854805' THEN 'BA Psychology/Religious Stds'
WHEN school_program = 'BA866939' THEN 'BA English and Psychology'
WHEN school_program = 'BA881754' THEN 'BA Criminal Justice/Sociology'
WHEN school_program = 'BA904201' THEN 'BA Fash Mgmt/Merch-Prod Devlpm'
WHEN school_program = 'BA909268' THEN 'BA Music and Theatre Arts'
WHEN school_program = 'BA914781' THEN 'BA Music and Psychology'
WHEN school_program = 'BA915425' THEN 'BA Criminal Justice/Sociology'
WHEN school_program = 'BA915445' THEN 'BA English/Govt-Amer Politics'
WHEN school_program = 'BA916529' THEN 'BA Criminal Justice/Psychology'
WHEN school_program = 'BA917105' THEN 'BA Criminal Justice/Psychology'
WHEN school_program = 'BA920516' THEN 'BA Criminal Justice/Psychology'
WHEN school_program = 'BA925407' THEN 'BA Fash Mgmt/Merch/Prod Devlpm'
WHEN school_program = 'BA936137' THEN 'BA Criminal Justice/Sociology'
WHEN school_program = 'BA937601' THEN 'BA English and Philosophy'
WHEN school_program = 'BA937978' THEN 'BA English/Religions Studies'
WHEN school_program = 'BA939425' THEN 'BA Criminal Justice/Psychology'
WHEN school_program = 'BA945483' THEN 'BA Criminal Justice/Psychology'
WHEN school_program = 'BAADMHR2075' THEN 'BA Admin and Human Resources'
WHEN school_program = 'BAADMHR3043' THEN 'BA Admin/Human Resources'
WHEN school_program = 'BAADMHR7381' THEN 'BA Admin/Human Resources'
WHEN school_program = 'BAADMIN' THEN 'BA Administration'
WHEN school_program = 'BAADMIN14' THEN 'BA Administration'
WHEN school_program = 'BAADMNHR2607' THEN 'BA Admin/Human Resources'
WHEN school_program = 'BAALEDUCART' THEN 'BA All-Level Cert Art'
WHEN school_program = 'BAALEDUCMUS' THEN 'BA All-Level Cert Music'
WHEN school_program = 'BAALEDUCPE' THEN 'BA All-Level Cert Physical Ed'
WHEN school_program = 'BAAMERPOLSCI' THEN 'BA American Politics'
WHEN school_program = 'BAAPADMIN' THEN 'BA Applied Administration'
WHEN school_program = 'BAAPPLMUSIC' THEN 'BA Applied Music'
WHEN school_program = 'BAAPSCOMPSYC' THEN 'BA Add Prev Spec/Comm Psyc'
WHEN school_program = 'BAART' THEN 'BA Art'
WHEN school_program = 'BAARTCAR3951' THEN 'BA Art and Cart-3D'
WHEN school_program = 'BAARTCART' THEN 'BA Art and CART'
WHEN school_program = 'BAARTCUL8943' THEN 'BA Art and Cultural Studies'
WHEN school_program = 'BAARTENG6534' THEN 'BA Art and English'
WHEN school_program = 'BAARTIED1508' THEN 'BA Art/Interior Environ Design'
WHEN school_program = 'BAARTIED4808' THEN 'BA Art/Interior Environ Design'
WHEN school_program = 'BAARTIED9758' THEN 'BA Art/Interior Environ Design'
WHEN school_program = 'BAARTPSY0122' THEN 'BA Art and Psychology'
WHEN school_program = 'BAARTPSY0981' THEN 'BA Art and Psychology'
WHEN school_program = 'BAARTPSY3418' THEN 'BA Art and Psychology'
WHEN school_program = 'BAARTPSY5268' THEN 'BA Art and Psychology'
WHEN school_program = 'BAARTPSY7224' THEN 'BA Art/Psychology'
WHEN school_program = 'BAARTRST6145' THEN 'BA Art and Religious Studies'
WHEN school_program = 'BAAS' THEN 'Bachelor of Applied Arts/Scien'
WHEN school_program = 'BAAS14' THEN 'Bachelor of Applied Arts/Scien'
WHEN school_program = 'BABIOLOGY' THEN 'BA Biology'
WHEN school_program = 'BACAJSC8029' THEN 'BA Comm Arts/Journ-Speech Comm'
WHEN school_program = 'BACART' THEN 'BA Computer Graphic Arts'
WHEN school_program = 'BACART3D' THEN 'BA Comp Graphics-3D Animation'
WHEN school_program = 'BACARTGRAPH' THEN 'BA Computer Graphics Design'
WHEN school_program = 'BACARTHE4956' THEN 'BA Computer Graphic/Theatre'
WHEN school_program = 'BACATECHPRD' THEN 'BA Comm Arts Tech and Prod'
WHEN school_program = 'BACHEMISTRY' THEN 'BA Chemistry'
WHEN school_program = 'BACHILDSTDS' THEN 'BA Child Studies'
WHEN school_program = 'BACHLDADOPSY' THEN 'BA Child/Adolescent Psychology'
WHEN school_program = 'BACJGVSO5576' THEN 'BA Crim Jus/Government/Soc'
WHEN school_program = 'BACJPSY8260' THEN 'BA Crim Justice/Psychology'
WHEN school_program = 'BACJPSY9905' THEN 'BA Criminal Justice/Psychology'
WHEN school_program = 'BACJSOC4201' THEN 'BA Criminal Justice/Sociology'
WHEN school_program = 'BACJUPSY1275' THEN 'BA Criminal Justice/Psychology'
WHEN school_program = 'BACJUPSY7732' THEN 'BA Criminal Justice/Psychology'
WHEN school_program = 'BACJUSOC0981' THEN 'BA Criminal Justice/Sociology'
WHEN school_program = 'BACLTPHL7845' THEN 'BA Cultural Studies/Philosophy'
WHEN school_program = 'BACMAMEDSTD' THEN 'BA Comm Art Media Studies'
WHEN school_program = 'BACMARTJOUR' THEN 'BA Comm Arts Journalism'
WHEN school_program = 'BACOMARTHIST' THEN 'BA Comm Arts and History'
WHEN school_program = 'BACOMJOURMST' THEN 'BA Comm Arts-Journ-Media Stds'
WHEN school_program = 'BACOMMART' THEN 'BA Communication Arts'
WHEN school_program = 'BACOMMBILING' THEN 'BA Comm/Bilingual Comm Arts'
WHEN school_program = 'BACOMMENGL' THEN 'BA Communications & English'
WHEN school_program = 'BACOMMHIST70' THEN 'BA Comm Art and History'
WHEN school_program = 'BACOMMJOUR' THEN 'BA Comm Arts Journalism'
WHEN school_program = 'BACOMMMEDST' THEN 'BA Comm Arts Media Studies'
WHEN school_program = 'BACOMMNMTP' THEN 'BA Comm Arts New Media/Tech/Pr'
WHEN school_program = 'BACOMMPROD' THEN 'BA Communcat Arts/Production'
WHEN school_program = 'BACOMMPSYC' THEN 'BA Community Psychology'
WHEN school_program = 'BACOMMSPAN' THEN 'BA Communications and Spanish'
WHEN school_program = 'BACOMMSPCH' THEN 'BA Comm Arts Speech Comm'
WHEN school_program = 'BACOMMSTUDIE' THEN 'BA Comm/Comm Studies'
WHEN school_program = 'BACOMMUS4899' THEN 'BA Communication Arts/Music'
WHEN school_program = 'BACOMPSY1988' THEN 'BA Comm Arts/Psychology'
WHEN school_program = 'BACOMSTUDIES' THEN 'BA Comm Arts Comm Studies'
WHEN school_program = 'BACONVERGENT' THEN 'BA Convergent Media'
WHEN school_program = 'BACRIMJUSPSY' THEN 'BA Criminal Justice/Psychology'
WHEN school_program = 'BACRIMJUSSOC' THEN 'BA Criminal Justice/Sociology'
WHEN school_program = 'BACRIMJUST' THEN 'BA Criminal Justice'
WHEN school_program = 'BACRIPSY8972' THEN 'BA Criminal Justice/Psychology'
WHEN school_program = 'BACRISOC4053' THEN 'BA Criminal Justice/Sociology'
WHEN school_program = 'BACRJPSY1511' THEN 'BA Criminal Justice/Psychology'
WHEN school_program = 'BACRJPSY6847' THEN 'BA Criminal Justice/Psychology'
WHEN school_program = 'BACRJPSY6968' THEN 'BA Criminal Justice/Psychology'
WHEN school_program = 'BACRJPSY7337' THEN 'BA Criminal Justice/Psychology'
WHEN school_program = 'BACRJPSY9814' THEN 'BA Criminal Justice/Psychology'
WHEN school_program = 'BACRJSOC0068' THEN 'BA Criminal Justice/Sociology'
WHEN school_program = 'BACRJSOC0920' THEN 'BA Criminal Justice/Sociology'
WHEN school_program = 'BACRJSOC0981' THEN 'BA Criminal Justice/Sociology'
WHEN school_program = 'BACRJSOC0988' THEN 'BA Criminal Justice/Sociology'
WHEN school_program = 'BACRJSOC2676' THEN 'BA Criminal Justice/Sociology'
WHEN school_program = 'BACRJSOC4160' THEN 'BA Criminal Justice/Sociology'
WHEN school_program = 'BACRJSOC5425' THEN 'BA Criminal Justice/Sociology'
WHEN school_program = 'BACRJSOC9950' THEN 'BA Crim Justice/Sociology'
WHEN school_program = 'BACRJU6260' THEN 'BA Criminal Justice/Psychology'
WHEN school_program = 'BACRJUGOVT' THEN 'BA Crim Justice & Government'
WHEN school_program = 'BACRJUPS0296' THEN 'BA Crim Just and Psychology'
WHEN school_program = 'BACRJUPS6980' THEN 'BA Criminal Justice/Psychology'
WHEN school_program = 'BACRJUPS7978' THEN 'BA Criminal Justice/Psychology'
WHEN school_program = 'BACRJUPSYC' THEN 'BA Crim Justice & Psych'
WHEN school_program = 'BACRJUSO1551' THEN 'BA Criminal Justice/Sociology'
WHEN school_program = 'BACRJUSO8066' THEN 'BA Criminal Justice/Sociology'
WHEN school_program = 'BACRMPSY2200' THEN 'BA Criminal Justice/Psychology'
WHEN school_program = 'BACRMPSY4044' THEN 'BA Criminal Justice/Psychology'
WHEN school_program = 'BACRMPSY4866' THEN 'BA Criminal Justice/Psychology'
WHEN school_program = 'BACSTENG0917' THEN 'BA Cultural Studies/English'
WHEN school_program = 'BACSTRST4369' THEN 'BA Cultural Stds/Relig Stds'
WHEN school_program = 'BACULENG8410' THEN 'BA Cultural Studies/English'
WHEN school_program = 'BACULTPOLI' THEN 'BA Cultural Studies-Political'
WHEN school_program = 'BACULTREL223' THEN 'BA Cultural/Religious Studies'
WHEN school_program = 'BACULTSTDS' THEN 'BA Cultural Studies'
WHEN school_program = 'BACUSTIA3024' THEN 'BA Cultural Stds/Intnl Affairs'
WHEN school_program = 'BADESMEDTECH' THEN 'BA Design/Media/Tech Studies'
WHEN school_program = 'BADESMER0706' THEN 'BA Fashion Desgn/Merchandising'
WHEN school_program = 'BADESMER4547' THEN 'BA Fashion Dsgn/Merchandising'
WHEN school_program = 'BADESMER4980' THEN 'BA Fash Design/Merchandising'
WHEN school_program = 'BADESMER9541' THEN 'BA Fash Design/Merchandising'
WHEN school_program = 'BAECHILDADMN' THEN 'BA Early Childhood Admin'
WHEN school_program = 'BAENGCOM2222' THEN 'BA English/Communication Arts'
WHEN school_program = 'BAENGHIS1842' THEN 'BA English and History'
WHEN school_program = 'BAENGHIS5698' THEN 'BA English and History'
WHEN school_program = 'BAENGHIS7905' THEN 'BA English and History'
WHEN school_program = 'BAENGIDS8028' THEN 'BA English/Interdiscip Studies'
WHEN school_program = 'BAENGIND8028' THEN 'BA English/Interdiscip Studies'
WHEN school_program = 'BAENGLISH' THEN 'BA English'
WHEN school_program = 'BAENGMUS' THEN 'BA English and Music'
WHEN school_program = 'BAENGPHI2055' THEN 'BA English and Philosophy'
WHEN school_program = 'BAENGPHL2055' THEN 'BA English and Philosophy'
WHEN school_program = 'BAENGPHL4755' THEN 'BA English and Philogophy'
WHEN school_program = 'BAENGPHL5047' THEN 'BA English and Philosophy'
WHEN school_program = 'BAENGPOL3412' THEN 'BA English & Political Science'
WHEN school_program = 'BAENGPSY1333' THEN 'BA English and Psychology'
WHEN school_program = 'BAENGPSY2231' THEN 'BA English and Psychology'
WHEN school_program = 'BAENGPSY6029' THEN 'BA English and Psychology'
WHEN school_program = 'BAENGPSY9700' THEN 'BA English and Psychology'
WHEN school_program = 'BAENGSOC4654' THEN 'BA English and Sociology'
WHEN school_program = 'BAENGTHE4926' THEN 'BA English/Theatre Arts'
WHEN school_program = 'BAENGTHE7047' THEN 'BA English and Theatre'
WHEN school_program = 'BAENGTHR7047' THEN 'BA English and Theatre Arts'
WHEN school_program = 'BAENINST7169' THEN 'BA English/International Stds'
WHEN school_program = 'BAENPH5047' THEN 'BA English and Philosophy'
WHEN school_program = 'BAENPH5645' THEN 'BA English and Philosophy'
WHEN school_program = 'BAEXPERPSYC' THEN 'BA Experimental Psychology'
WHEN school_program = 'BAEXPSPH1324' THEN 'BA Exp Psychology/Philosophy'
WHEN school_program = 'BAFASDESPROD' THEN 'BA Fashion Mgmt/Product Dev'
WHEN school_program = 'BAFASH926326' THEN 'BA Fash Mgt-Fash Merc/Prod Dev'
WHEN school_program = 'BAFASHDESIGN' THEN 'BA Fashion MGMT-- Design'
WHEN school_program = 'BAFASHMERCH' THEN 'BA Fash MGMT--Merchandising'
WHEN school_program = 'BAFASHSTDS' THEN 'BA Fashion Studies'
WHEN school_program = 'BAFMFDFM7802' THEN 'BA Fashion Mgt/Design/Merch'
WHEN school_program = 'BAFMGDES7168' THEN 'BA Fashion Mgt/Design/Merchand'
WHEN school_program = 'BAGOVAMERPOL' THEN 'BA Govt/American Politics'
WHEN school_program = 'BAGOVAPCOM' THEN 'BA Government-AP and Commuic'
WHEN school_program = 'BAGOVAPPHL' THEN 'BA Government-AP and Philosoph'
WHEN school_program = 'BAGOVCOMINR' THEN 'BA Govt Comp/Intrnl Relations'
WHEN school_program = 'BAGOVCOMINRE' THEN 'BA Govt/Comp Pol/Intrntl Rel'
WHEN school_program = 'BAGOVHIS4552' THEN 'BA Govt-Comp Pols/Int Rel-Hist'
WHEN school_program = 'BAGOVHIS5828' THEN 'BA Government and History'
WHEN school_program = 'BAGOVRS9228' THEN 'BA Governnt/Religious Studies'
WHEN school_program = 'BAGOVT922361' THEN 'BA Govt: AmericanPol/Pre-Law'
WHEN school_program = 'BAGVCOMINREM' THEN 'BA Govt/Comp Pol/Interntl Rel'
WHEN school_program = 'BAGVTSOC' THEN 'BA Government and Sociology'
WHEN school_program = 'BAHISIAF7734' THEN 'BA History/Internatl Affairs'
WHEN school_program = 'BAHISINA1867' THEN 'BA Hist/International Affairs'
WHEN school_program = 'BAHISPHI0826' THEN 'BA History and Philosophy'
WHEN school_program = 'BAHISPOL0479' THEN 'BA History & Poltical Science'
WHEN school_program = 'BAHISPOL5038' THEN 'BA History/Political Science'
WHEN school_program = 'BAHISPOL6749' THEN 'BA History/Political Science'
WHEN school_program = 'BAHISPOL8288' THEN 'BA History/Political Science'
WHEN school_program = 'BAHISPSY5145' THEN 'BA History and Psychology'
WHEN school_program = 'BAHISPSY7377' THEN 'BA History and Psychology'
WHEN school_program = 'BAHISREL2725' THEN 'BA History/Religious Studies'
WHEN school_program = 'BAHISREL7895' THEN 'BA History/Religious Studies'
WHEN school_program = 'BAHISREL8221' THEN 'BA History/Religious Studies'
WHEN school_program = 'BAHISREL8875' THEN 'BA History/Religious Studies'
WHEN school_program = 'BAHISRST5927' THEN 'BA History/Religious Studies'
WHEN school_program = 'BAHISRST6994' THEN 'BA History/Religious Studies'
WHEN school_program = 'BAHISTORY' THEN 'BA History'
WHEN school_program = 'BAHMRSOD6985' THEN 'BA Human Res/Organ Development'
WHEN school_program = 'BAHMRSOD9769' THEN 'BA Human Res/Organ Development'
WHEN school_program = 'BAHROD2483' THEN 'BA Hum Res/Org Development'
WHEN school_program = 'BAHROD4403' THEN 'BA Human Res/Organiz Develop'
WHEN school_program = 'BAHROD5724' THEN 'BA Human Resrcs/Org Develpment'
WHEN school_program = 'BAHROD592852' THEN 'BA Human Resources/Org Develop'
WHEN school_program = 'BAHROD7968' THEN 'BA Human Resources/Org Develop'
WHEN school_program = 'BAHROD8376' THEN 'BA Human Res/Org Development'
WHEN school_program = 'BAHROD9317' THEN 'BA Human Res/Org Devevelopment'
WHEN school_program = 'BAHRORDV4403' THEN 'BA Hum Res/Organiz Development'
WHEN school_program = 'BAHRORDV6875' THEN 'BA Hum Res/Organiz Development'
WHEN school_program = 'BAHRORGD0080' THEN 'BA Human Res/Org Development'
WHEN school_program = 'BAHRORGD6622' THEN 'BA Human Res/Org Development'
WHEN school_program = 'BAHSRS5915' THEN 'BA History/Religious Studies'
WHEN school_program = 'BAHUMANRES' THEN 'BA Human Resources'
WHEN school_program = 'BAHUMANRES14' THEN 'BA Human Resources'
WHEN school_program = 'BAHUMRESOURC' THEN 'BA Human Resource'
WHEN school_program = 'BAHURESORDV' THEN 'BA Human Res/Organiz Develop'
WHEN school_program = 'BAHURESORGDV' THEN 'BA Human Res/Organiz Develop'
WHEN school_program = 'BAINAFCONFLT' THEN 'BA Intnl Affair/Conflict-Peace'
WHEN school_program = 'BAINAFEUROPE' THEN 'BA Intnl Affair/European Focus'
WHEN school_program = 'BAINAFLATAME' THEN 'BA Intnl Affair/Latin Amer Foc'
WHEN school_program = 'BAINAFSPECFO' THEN 'BA Intnl Affair/Special Focus'
WHEN school_program = 'BAINAPHI2242' THEN 'BA Intnl Affairs/Philosophy'
WHEN school_program = 'BAINAPHL6962' THEN 'BA Interntl Affairs/Philosophy'
WHEN school_program = 'BAINENAR9758' THEN 'BA Inter Environ Design/Art'
WHEN school_program = 'BAINSRST1204' THEN 'BA International Stds/Rel Stds'
WHEN school_program = 'BAINSTSP1350' THEN 'BA International Stds/Spanish'
WHEN school_program = 'BAINTDSNC13' THEN 'BA Interdisciplinary Stds (NC)'
WHEN school_program = 'BAINTDSNC15' THEN 'BA Interdisciplinary Stds (NC)'
WHEN school_program = 'BAINTENVDES' THEN 'BA Interior Environment Design'
WHEN school_program = 'BAINTERAFFRS' THEN 'BA International Affairs'
WHEN school_program = 'BAINTERDESN' THEN 'BA Interior Design'
WHEN school_program = 'BAINTERDSNC' THEN 'BA Interdisciplinary Stds (NC)'
WHEN school_program = 'BAINTERNSTDS' THEN 'BA International Studies'
WHEN school_program = 'BAINTERSTDS' THEN 'BA Interdisciplinary Studies'
WHEN school_program = 'BAINTLAFFMUS' THEN 'BA Intl Affairs & Music'
WHEN school_program = 'BAINTRDISCNC' THEN 'BA Interdisciplinary Stds-NC'
WHEN school_program = 'BAISPS2884' THEN 'BA Interntll Stds/Pol Science'
WHEN school_program = 'BAISTPOL2884' THEN 'BA Internatl Std/Political Scn'
WHEN school_program = 'BAJCOMM4016' THEN 'BA Comm Arts Journ and Speech'
WHEN school_program = 'BAJOUMST7229' THEN 'BA Journalism/Media Studies'
WHEN school_program = 'BALIBSTUDIES' THEN 'BA Liberal Studies'
WHEN school_program = 'BAMATH' THEN 'BA Mathematics'
WHEN school_program = 'BAMATSOC1049' THEN 'BA Mathematics and Sociology'
WHEN school_program = 'BAMDSTD1326' THEN 'BA Multidisciplinary Studies'
WHEN school_program = 'BAMDSTD1696' THEN 'BA Multidisciplinary Studies'
WHEN school_program = 'BAMDSTD4025' THEN 'BA Multidisciplinary Studies'
WHEN school_program = 'BAMISRST3924' THEN 'BA Mus Ind Stds/Religious Stds'
WHEN school_program = 'BAMTHPHL0786' THEN 'BA Mathematics and Philosophy'
WHEN school_program = 'BAMUCPRS7093' THEN 'BA Music Comp/Perf/Relig Stds'
WHEN school_program = 'BAMULSTD3515' THEN 'BA Multi Studies 457333515'
WHEN school_program = 'BAMULTIST593' THEN 'BA Multidisciplinary Studies'
WHEN school_program = 'BAMULTISTDS' THEN 'BA Multidisciplinary Studies'
WHEN school_program = 'BAMULTISTUDY' THEN 'BA Multidisciplinary Studies'
WHEN school_program = 'BAMULTST3041' THEN 'BA Multidisciplinary Studies'
WHEN school_program = 'BAMULTST9245' THEN 'BA Multidisciplinary Studies'
WHEN school_program = 'BAMUMIST1942' THEN 'BA Music/Music Industry Study'
WHEN school_program = 'BAMUMUIN1942' THEN 'BA Mus/Mu Industry Studies'
WHEN school_program = 'BAMUREST7093' THEN 'BA Music and Religious Studies'
WHEN school_program = 'BAMUSIC' THEN 'BA Music'
WHEN school_program = 'BAMUSICCOMPO' THEN 'BA Music/Composition'
WHEN school_program = 'BAMUSICPERFM' THEN 'BA Music/Performance'
WHEN school_program = 'BAMUSINDSTDS' THEN 'BA Music Industry Studies'
WHEN school_program = 'BAMUSPOL7245' THEN 'BA Music/Political Science'
WHEN school_program = 'BAMUSPSY5818' THEN 'BA Music and Psychology'
WHEN school_program = 'BAMUSTHA3450' THEN 'BA Music/Theatre Arts'
WHEN school_program = 'BAMUTA9268' THEN 'BA Music and Theatre Arts'
WHEN school_program = 'BANATAMERSTD' THEN 'BA Native American Studies'
WHEN school_program = 'BAODHR6985' THEN 'BA Org Dev/Human Resources'
WHEN school_program = 'BAORGANADMIN' THEN 'BA Organizational Admin'
WHEN school_program = 'BAORGDEV' THEN 'BA Organizational Development'
WHEN school_program = 'BAORGDEV14' THEN 'BA Organizational Development'
WHEN school_program = 'BAPAMNPH1739' THEN 'BA Pastoral Min/Philosophy'
WHEN school_program = 'BAPASTMIN' THEN 'BA Pastoral Ministry'
WHEN school_program = 'BAPHIL' THEN 'BA Philosophy'
WHEN school_program = 'BAPHIPSY6435' THEN 'BA Philosophy/Psychology'
WHEN school_program = 'BAPHIPSY7300' THEN 'BA Philosophy/Psychology'
WHEN school_program = 'BAPHLPOL1712' THEN 'BA Philosophy/Poltical Science'
WHEN school_program = 'BAPHLPSY1252' THEN 'BA Philosophy and Psychology'
WHEN school_program = 'BAPHLPSY7553' THEN 'BA Philosophy and Psychology'
WHEN school_program = 'BAPHLREL9705' THEN 'BA Philosophy and Religion'
WHEN school_program = 'BAPHLRST7023' THEN 'BA Philosophy/Religious Stds'
WHEN school_program = 'BAPHLSOC' THEN 'BA Philosophy and Sociology'
WHEN school_program = 'BAPHPOLS8348' THEN 'BA Phil/Pol Sci-Amer Politics'
WHEN school_program = 'BAPHSP861272' THEN 'BA Philosophy and Spanish'
WHEN school_program = 'BAPLRELS9779' THEN 'BA Phil/Religious Studies'
WHEN school_program = 'BAPMINCALEAD' THEN 'BA Pas Min/Catholic Leadership'
WHEN school_program = 'BAPMINCATECH' THEN 'BA Pas Min/Catechetics'
WHEN school_program = 'BAPMINPHIL' THEN 'BA Pas Min/Philosophy'
WHEN school_program = 'BAPOLCOM8490' THEN 'BA Polictical Sci/Comm Arts'
WHEN school_program = 'BAPOLPSY0756' THEN 'BA Political Sci/Psychology'
WHEN school_program = 'BAPOLSCI' THEN 'BA Political Science'
WHEN school_program = 'BAPOLSCIAMER' THEN 'BA Pol Sci American Politics'
WHEN school_program = 'BAPOLSCIINCO' THEN 'BA Pol Sci Intern Rel/Comp Pol'
WHEN school_program = 'BAPOLSOC3297' THEN 'BS Political Science/Sociology'
WHEN school_program = 'BAPOLSOC9204' THEN 'BA Political Science/Sociology'
WHEN school_program = 'BAPOSSOC3297' THEN 'BA Political Science/Sociology'
WHEN school_program = 'BAPSCREL7499' THEN 'BA Psychology/Religious Stds'
WHEN school_program = 'BAPSINSTPLPO' THEN 'BA Pol Sci Int Stds-Pub Law Po'
WHEN school_program = 'BAPSOD' THEN 'BA Psych of Org Development'
WHEN school_program = 'BAPSYC' THEN 'BA Psychology'
WHEN school_program = 'BAPSYPOL9420' THEN 'BA Psych/Political Science'
WHEN school_program = 'BAPSYREL4159' THEN 'BA Psychology/Religious Stds'
WHEN school_program = 'BAPSYREL4803' THEN 'BA Psychology/Religious Stds'
WHEN school_program = 'BAPSYREL5937' THEN 'BA Psychology/Religious Stdies'
WHEN school_program = 'BAPSYRELS967' THEN 'BA Psychology/Rel Studies'
WHEN school_program = 'BAPSYSOC0103' THEN 'BA Psychology and Sociology'
WHEN school_program = 'BAPSYSOC1753' THEN 'BA Psyc/Soc-Child/Adolescent'
WHEN school_program = 'BAPSYSOC4270' THEN 'BA Psychology and Sociology'
WHEN school_program = 'BAPSYSOC9976' THEN 'BA Psychology and Sociology'
WHEN school_program = 'BAPSYSPA5533' THEN 'BA Psychology and Spanish'
WHEN school_program = 'BAPSYTHA0185' THEN 'BA Psychology/Theatre Arts'
WHEN school_program = 'BARELSBIBSTD' THEN 'BA Religious Stds/Biblical Std'
WHEN school_program = 'BARELSCATSTD' THEN 'BA Religious Stds/Catholic Std'
WHEN school_program = 'BARELSGENSTD' THEN 'BA Religious Stds/General Stds'
WHEN school_program = 'BARELSOC0391' THEN 'BA Religious Studies/Sociology'
WHEN school_program = 'BARELSOC1476' THEN 'BA Religious Studies/Sociology'
WHEN school_program = 'BARELSPA5206' THEN 'BA Religion Studies/Spanish'
WHEN school_program = 'BARELSTHEOST' THEN 'BA Relig Stds/Theolocial Stds'
WHEN school_program = 'BARELSTUDIES' THEN 'BA Religious Studies'
WHEN school_program = 'BASOCIOLOGY' THEN 'BA Sociology (Academic)'
WHEN school_program = 'BASOCPROF' THEN 'BA Sociology (Professional)'
WHEN school_program = 'BASOCPSY8260' THEN 'BA Sociology/Psychology'
WHEN school_program = 'BASOCSPN4041' THEN 'BA Sociology and Spanish'
WHEN school_program = 'BASPANISH' THEN 'BA Spanish'
WHEN school_program = 'BATHEATRE' THEN 'BA Theatre Arts'
WHEN school_program = 'BBA GBMK3944' THEN 'BBA General Business/Marketing'
WHEN school_program = 'BBA MGMK0360' THEN 'BBA Bus Adm/Management/Market'
WHEN school_program = 'BBA834220' THEN 'BBA Bus-Account/Mgmt Info Syst'
WHEN school_program = 'BBA905087' THEN 'BBA Bus-Accounting/Intnl Bus'
WHEN school_program = 'BBA930412' THEN 'BBA Bus-Intnl Bus/Sport Mgmt'
WHEN school_program = 'BBA933718' THEN 'BBA Bus-Fin Econ/Marketing'
WHEN school_program = 'BBA939978' THEN 'BBA Bus-Intnl Bus/Mgt Info Sys'
WHEN school_program = 'BBA940588' THEN 'BBA Bus-Intnl Econ/Sport Mgmt'
WHEN school_program = 'BBAACBE7920' THEN 'BBA Bus Adm-Account/Bus Econ'
WHEN school_program = 'BBAACBEC7920' THEN 'BBA Bus Adm/Acct-Bus Economics'
WHEN school_program = 'BBAACBKFN183' THEN 'BBA Accounting/Bank & Finance'
WHEN school_program = 'BBAACCBF9183' THEN 'BBA Accounting/Banking/Finance'
WHEN school_program = 'BBAACCBFN233' THEN 'BBA Accounting/Banking-Finance'
WHEN school_program = 'BBAACCECO857' THEN 'BBA Accounting and Economics'
WHEN school_program = 'BBAACCMG9055' THEN 'BBA Accounting and Management'
WHEN school_program = 'BBAACCMGT033' THEN 'BBA Accounting and Management'
WHEN school_program = 'BBAACCMGT940' THEN 'BBA Accounting and Management'
WHEN school_program = 'BBAACCMIS592' THEN 'BBA Bus Admin-Acc/Mgt Info Syt'
WHEN school_program = 'BBAACCSPT589' THEN 'BBA Accounting and Sport Mgmt'
WHEN school_program = 'BBAACCT' THEN 'BBA Accounting'
WHEN school_program = 'BBAACCTBAFN' THEN 'BBA Acct-Banking&Finance'
WHEN school_program = 'BBAACFN2079' THEN 'BBA Bus Admin-Accounting/Finan'
WHEN school_program = 'BBAACIB1023' THEN 'BBA Accounting/Intern Business'
WHEN school_program = 'BBAACIBSM085' THEN 'BBA Bus-Acct/Intl Bus/Spt Mgmt'
WHEN school_program = 'BBAACINB5087' THEN 'BBA Bus Adm/Acct-Intrnl Bus'
WHEN school_program = 'BBAACINF1468' THEN 'BBA Accounting/Inform Systems'
WHEN school_program = 'BBAACINF9467' THEN 'BBA Accounting/Inform Systems'
WHEN school_program = 'BBAACINS5140' THEN 'BBA Accounting/Inform Systems'
WHEN school_program = 'BBAACIS4278' THEN 'BBA Bus Adm-Acct/Mgmt Info Sys'
WHEN school_program = 'BBAACMG0268' THEN 'BBA Accounting and Management'
WHEN school_program = 'BBAACMG0388' THEN 'BBA Bus Admin/Acct-Management'
WHEN school_program = 'BBAACMGT8497' THEN 'BBA Bus Admin-Accounting/Mgmt'
WHEN school_program = 'BBAACMIS' THEN 'BBA Bus Adm/Acct-Mgmt Info Sys'
WHEN school_program = 'BBAACMIS4220' THEN 'BBA Bus Adm/Acct-Mgmt Info Sys'
WHEN school_program = 'BBAACMIS5927' THEN 'BBA Bus Adm/Acct-Mgmt Info Sys'
WHEN school_program = 'BBAACMIS7941' THEN 'BBA Bus Adm/Acct-Mgmt Info Sys'
WHEN school_program = 'BBABADMMIS' THEN 'BBA Bus Admin/Mgmt Info Systs'
WHEN school_program = 'BBABAGENERIC' THEN 'BBA Business Administration'
WHEN school_program = 'BBABFEF0746' THEN 'BBA Bank-Finance/Eco-Finance'
WHEN school_program = 'BBABFEF2635' THEN 'BBA Bank-Finance/Eco-Finance'
WHEN school_program = 'BBABFEF7283' THEN 'BBA Banking-Fin/Economics-Fin'
WHEN school_program = 'BBABFIN' THEN 'BBA Banking and Finance'
WHEN school_program = 'BBABFMK9947' THEN 'BBABanking-Finance/Marketing'
WHEN school_program = 'BBABFNINB824' THEN 'BBA Banking-Finan/Interntl Bus'
WHEN school_program = 'BBABIMKT3094' THEN 'BBA Intnl Bus/Marketing'
WHEN school_program = 'BBABINF' THEN 'BBA Information Systems'
WHEN school_program = 'BBABINT' THEN 'BBA International Business'
WHEN school_program = 'BBABKECFN017' THEN 'BBA Bank/Fin and Econ/Fin'
WHEN school_program = 'BBABKFIM7463' THEN 'BBA Banking/Finance/Marketing'
WHEN school_program = 'BBABKFIM7481' THEN 'BBA Banking/Finance/Marketing'
WHEN school_program = 'BBABKFMK8197' THEN 'BBA Banking-Finance/Marketing'
WHEN school_program = 'BBABKFNK8164' THEN 'BBA Banking-Finance/Marketing'
WHEN school_program = 'BBABKFNM0772' THEN 'BBA Banking/Finance/Marketing'
WHEN school_program = 'BBABNKFN5735' THEN 'BBA Banking and Finance'
WHEN school_program = 'BBABUECOFNTR' THEN 'BBA Business Admin/Economics'
WHEN school_program = 'BBABUINTECON' THEN 'BBA Business Admin/Economics'
WHEN school_program = 'BBABUSECON' THEN 'BBA Business Economics'
WHEN school_program = 'BBABUSECTRAC' THEN 'BBA Business Admin/Economics'
WHEN school_program = 'BBABUSPOLECO' THEN 'BBA Business Admin/Economics'
WHEN school_program = 'BBAECOFIN' THEN 'BBA Economics and Finance'
WHEN school_program = 'BBAECOFIN741' THEN 'BBA Economics and Finance'
WHEN school_program = 'BBAECONOMICS' THEN 'BBA Economics'
WHEN school_program = 'BBAEFNBI3600' THEN 'BBA Econ & Fin/Intntl Business'
WHEN school_program = 'BBAFINANCE' THEN 'BBA Finance'
WHEN school_program = 'BBAFINBANKIN' THEN 'BBA Business Admin/Finance'
WHEN school_program = 'BBAFINECON' THEN 'BBA Financial Economics'
WHEN school_program = 'BBAFINPLAN' THEN 'BBA Business Admin/Finance'
WHEN school_program = 'BBAFNMIS8375' THEN 'BBA Finance/Mgmt Info Systems'
WHEN school_program = 'BBAFNMKT1657' THEN 'BBA Banking&Finance/Marketing'
WHEN school_program = 'BBAGBPLA6670' THEN 'BBA Bus Adm/Gen Bus-Pre-Law'
WHEN school_program = 'BBAGBUMKT944' THEN 'BBA General Business/Marketing'
WHEN school_program = 'BBAGENBUS' THEN 'BBA General Business'
WHEN school_program = 'BBAHISMKTG' THEN 'BBA Hispanic Marketing'
WHEN school_program = 'BBAIBIEC2629' THEN 'BBA Bus Adm/Itnl Bus-Itnl Econ'
WHEN school_program = 'BBAIBMIS5134' THEN 'BBA Bus-Intnl Bus/Mgt Info Sys'
WHEN school_program = 'BBAIBMIS9978' THEN 'BBA Bus Adm/Intl Bus-Mgmt Info'
WHEN school_program = 'BBAIBMK2950' THEN 'BBA Internationl Bus/Marketing'
WHEN school_program = 'BBAIBMK2955' THEN 'BBA Internationl Bus/Marketing'
WHEN school_program = 'BBAIBMK2958' THEN 'BBA Intrntl Business/Marketing'
WHEN school_program = 'BBAIBMK2960' THEN 'BBA Internationl Bus/Marketing'
WHEN school_program = 'BBAIBMK2961' THEN 'BBA Internationl Bus/Marketing'
WHEN school_program = 'BBAIBMK3166' THEN 'BBA Internationl Bus/Marketing'
WHEN school_program = 'BBAIBMK3167' THEN 'BBA Internationl Bus/Marketing'
WHEN school_program = 'BBAIBMK3168' THEN 'BBA Internationl Bus/Marketing'
WHEN school_program = 'BBAIBMK3170' THEN 'BBA Internationl Bus/Marketing'
WHEN school_program = 'BBAIBMK3171' THEN 'BBA Internationl Bus/Marketing'
WHEN school_program = 'BBAIBMKT0069' THEN 'BBA Bus Adm/Intl Bus & Mktg'
WHEN school_program = 'BBAIBMKT0097' THEN 'BBA Bus Adm/Intl Bus & Mktg'
WHEN school_program = 'BBAIBMKT0120' THEN 'BBA Intntl Business/Marketing'
WHEN school_program = 'BBAIBMKT0436' THEN 'BBA Interntl Bus/Marketing'
WHEN school_program = 'BBAIBMKT7862' THEN 'BBA Internatl Bus/Marketing'
WHEN school_program = 'BBAIBMKT8112' THEN 'BBA Interntnl Bus/Marketing'
WHEN school_program = 'BBAIBMKT9094' THEN 'BBA Bus Adm/Intl Bus & Mktg'
WHEN school_program = 'BBAIBMKT9112' THEN 'BBA Bus Adm/Intl Bus & Mktg'
WHEN school_program = 'BBAIBUMK4952' THEN 'BBA Internation Bus/Marketing'
WHEN school_program = 'BBAINBMG8015' THEN 'BBA Bus Admin-Intnl Bus/Mgmt'
WHEN school_program = 'BBAINBMK1276' THEN 'BBA Internationl Bus/Marketing'
WHEN school_program = 'BBAINBMK5728' THEN 'BBA Internatnl Bus/Marketing'
WHEN school_program = 'BBAINBMK8088' THEN 'BBA Bus Admin-Intnl Bus/Mktg'
WHEN school_program = 'BBAINBMK8789' THEN 'BBA Bus Admin-Intnl Bus/Mktg'
WHEN school_program = 'BBAINBMK9468' THEN 'BBA Bus Adm/Intrnl Bus-Mktg'
WHEN school_program = 'BBAINBMKT198' THEN 'BBA Intl Business/Marketing'
WHEN school_program = 'BBAINBMKT438' THEN 'BBA Interntl Bus/Marketing'
WHEN school_program = 'BBAINBSMK045' THEN 'BBA Intern Business/Marketing'
WHEN school_program = 'BBAINBSMK047' THEN 'BBA Intern Business/Marketing'
WHEN school_program = 'BBAINBSMK112' THEN 'BBA Intern Business/Marketing'
WHEN school_program = 'BBAINBSMK427' THEN 'BBA Intern Business/Marketing'
WHEN school_program = 'BBAINBSMK490' THEN 'BBA Intern Business/Marketing'
WHEN school_program = 'BBAINBSMK746' THEN 'BBA Intern Business/Marketing'
WHEN school_program = 'BBAINBUMK460' THEN 'BBA Internationl Business/Mktg'
WHEN school_program = 'BBAINBUMK801' THEN 'BBA Internationl Business/Mktg'
WHEN school_program = 'BBAINBUMK805' THEN 'BBA Internationl Business/Mktg'
WHEN school_program = 'BBAINBUMK835' THEN 'BBA Internationl Business/Mktg'
WHEN school_program = 'BBAINFOMKTG' THEN 'BBA Info Syst/Marketing'
WHEN school_program = 'BBAINMKT1660' THEN 'BBA Interntnl Bus/Marketing'
WHEN school_program = 'BBAINTACCTCH' THEN 'BBA International Accounting'
WHEN school_program = 'BBAINTACCTMX' THEN 'BBA International Accounting'
WHEN school_program = 'BBAINTERECON' THEN 'BBA International Economics'
WHEN school_program = 'BBAINTMK4547' THEN 'BBA Internationl Bus/Marketing'
WHEN school_program = 'BBAINTMKT109' THEN 'BBA International Bus/Marketin'
WHEN school_program = 'BBAINTMKT943' THEN 'BBA International Bus/Marketin'
WHEN school_program = 'BBAMANMAR831' THEN 'BBA Management and Marketing'
WHEN school_program = 'BBAMANMK6549' THEN 'BBA Management and Marketing'
WHEN school_program = 'BBAMANMK7470' THEN 'BBA Management and Marketing'
WHEN school_program = 'BBAMEX080043' THEN 'BBA Banking-Finance/Marketing'
WHEN school_program = 'BBAMEX09093' THEN 'BBA Banking-Finance/Marketing'
WHEN school_program = 'BBAMEX881225' THEN 'BBA Internatnl Bus/Marketing'
WHEN school_program = 'BBAMEX904278' THEN 'BBA Internatnl Bus/Marketing'
WHEN school_program = 'BBAMEX941583' THEN 'BBA Banking-Finance/Marketing'
WHEN school_program = 'BBAMEX943072' THEN 'BBA International Bus/Marketin'
WHEN school_program = 'BBAMEX943107' THEN 'BBA Internationl Bus/Marketing'
WHEN school_program = 'BBAMGAC2113' THEN 'BBA Management and Accounting'
WHEN school_program = 'BBAMGIS8394' THEN 'BBA Bus Admin/Mgmt & MIS'
WHEN school_program = 'BBAMGMIS8394' THEN 'BBA Bus Adm/Mgmt-Mgmt Info Sys'
WHEN school_program = 'BBAMGMK4854' THEN 'BBA Management and Marketing'
WHEN school_program = 'BBAMGMMIS811' THEN 'BBA Mgmt/Mgmt Inform Systems'
WHEN school_program = 'BBAMGMMKT574' THEN 'BBA Management/Marketing'
WHEN school_program = 'BBAMGMT' THEN 'BBA Management'
WHEN school_program = 'BBAMGMTMKTG' THEN 'BBA Management-Marketing'
WHEN school_program = 'BBAMGPE3810' THEN 'BBA Bus Adm: Mgmt/Politic Econ'
WHEN school_program = 'BBAMGPL6790' THEN 'BBA Bus Adm/Mgmt & Pre-Law'
WHEN school_program = 'BBAMGTMK2329' THEN 'BBA Management and Marketing'
WHEN school_program = 'BBAMGTMK4574' THEN 'BBA Management and Marketing'
WHEN school_program = 'BBAMGTMKT799' THEN 'BBA Management and Marketing'
WHEN school_program = 'BBAMIS' THEN 'BBA Bus Admin/Mgmt Info Systs'
WHEN school_program = 'BBAMKINB8964' THEN 'BBA Bus Adm/Mktg & Intntl Bus'
WHEN school_program = 'BBAMKSMG6614' THEN 'BBA Marketing/Sports Mgmt'
WHEN school_program = 'BBAMKTG' THEN 'BBA Marketing'
WHEN school_program = 'BBAMMGT' THEN 'BBA Merchandising Management'
WHEN school_program = 'BBAPGM' THEN 'BBA Prof Golf Management'
WHEN school_program = 'BBAPOLECON' THEN 'BBA Political Economy'
WHEN school_program = 'BBASMHP' THEN 'BBA Sport Management'
WHEN school_program = 'BFA3DGAMANIM' THEN 'BFA 3D Anim/Game Des-Animation'
WHEN school_program = 'BFA3DGAMEDES' THEN 'BFA 3D Animation/Game Design'
WHEN school_program = 'BFA3DGAMODEL' THEN 'BFA 3D Anim/Game Des-Modeling'
WHEN school_program = 'BFAARCGA6035' THEN 'BFA Art/Computer Graphic Arts'
WHEN school_program = 'BFAARGRP6035' THEN 'BFA Art and Graphic Arts'
WHEN school_program = 'BFAART' THEN 'BFA Art'
WHEN school_program = 'BFAART7117' THEN 'BFA Art w/Ceramics/Photography'
WHEN school_program = 'BFAARTFADS' THEN 'BFA Art & Fashion Design'
WHEN school_program = 'BFACART' THEN 'BFA Computer Graphic Arts'
WHEN school_program = 'BFACART3D' THEN 'BFA Comp Graphics-3D Animation'
WHEN school_program = 'BFACARTGRAPH' THEN 'BFA Comp Graphics Design'
WHEN school_program = 'BFACERAMICS' THEN 'BFA Art/Ceramics'
WHEN school_program = 'BFADRAWING' THEN 'BFA Art/Drawing'
WHEN school_program = 'BFAFASHDESGN' THEN 'BFA Fashion Design'
WHEN school_program = 'BFAGRDESIGN' THEN 'BFA Graphic Design'
WHEN school_program = 'BFAINTERDESI' THEN 'BFA Interior Design'
WHEN school_program = 'BFAPAINTING' THEN 'BFA Art/Painting'
WHEN school_program = 'BFAPHOTO' THEN 'BFA Art/Photography'
WHEN school_program = 'BFAPHOTOGRAP' THEN 'BFA Photography'
WHEN school_program = 'BFAPRINTMAK' THEN 'BFA Art/Printmaking'
WHEN school_program = 'BFASCULPTURE' THEN 'BFA Art/Sculpture'
WHEN school_program = 'BMAPMUSCOMP' THEN 'BM Applied Music Composition'
WHEN school_program = 'BMAPPLMUSIC' THEN 'BM Applied Music'
WHEN school_program = 'BMMEDALSE108' THEN 'BM Music Ed/All-Level/Spec Ed'
WHEN school_program = 'BMMUSED9830' THEN 'BM Music/All-Level Education'
WHEN school_program = 'BMMUSIC' THEN 'BM Music'
WHEN school_program = 'BMMUSICCOMPO' THEN 'BM Music/Composition'
WHEN school_program = 'BMMUSICEDUC' THEN 'BM Music Education'
WHEN school_program = 'BMMUSTHERAPY' THEN 'BM Music Therapy'
WHEN school_program = 'BS884134' THEN 'BS Biol/Nutrition (Dietetics)'
WHEN school_program = 'BS921446' THEN 'BS Com Inf Sys/Netwk-Cyber Sec'
WHEN school_program = 'BS942239' THEN 'BS Comp Info Sys/Net-Comp Prog'
WHEN school_program = 'BS964236' THEN 'BS Bus Adm/Info Syst-Proj Mgmt'
WHEN school_program = 'BS990696' THEN 'BS Com Info Sys/Net-Cyber Sec'
WHEN school_program = 'BSACCMGM512' THEN 'BS Bus Admin/Acct & Mgmt'
WHEN school_program = 'BSAT' THEN 'BS in Athletic Training'
WHEN school_program = 'BSATHRSC4054' THEN 'BS Athletic Trng/Rehab Science'
WHEN school_program = 'BSATHRSC8176' THEN 'BS Athletic Training/Rehab Sci'
WHEN school_program = 'BSATHTRAIN' THEN 'BS Athletic Training'
WHEN school_program = 'BSATHTRREHAB' THEN 'BS Athletic Train/Rehab Scien'
WHEN school_program = 'BSATRSC0736' THEN 'BS Athletic Trng/Rehab Science'
WHEN school_program = 'BSATRSCI0084' THEN 'BS Athletic Training/Rehab Sci'
WHEN school_program = 'BSATRSCI3010' THEN 'BS Athletic Trng/Rehab Science'
WHEN school_program = 'BSBAACCOUNT' THEN 'BS Business/Accounting'
WHEN school_program = 'BSBAACCT14' THEN 'BS Business/Accounting'
WHEN school_program = 'BSBAACFI0148' THEN 'BS Bus Adm/Accounting/Finance'
WHEN school_program = 'BSBAACFI3817' THEN 'BS Bus Adm/Accounting/Finance'
WHEN school_program = 'BSBAACFN2824' THEN 'BS Bus Adm-Accounting/Finance'
WHEN school_program = 'BSBAACFN7198' THEN 'BS Bus Adm--Accounting/Finance'
WHEN school_program = 'BSBAACMK2458' THEN 'BS Bus Adm/Account/Marketing'
WHEN school_program = 'BSBABANKFIN' THEN 'BS Business/Banking/Finance'
WHEN school_program = 'BSBABFIS1185' THEN 'BS Bus Adm/Bank-Fin/Info Syst'
WHEN school_program = 'BSBAEBUSMG14' THEN 'BS Bus Admin/E-Business Mgmt'
WHEN school_program = 'BSBAEBUSMGMT' THEN 'BS Bus Admin/E-Business Mgmt'
WHEN school_program = 'BSBAFIMG8576' THEN 'BS Bus Adm/Finance/Management'
WHEN school_program = 'BSBAFINAN14' THEN 'BS Business/Finance'
WHEN school_program = 'BSBAFINANCE' THEN 'BS Business/Finance'
WHEN school_program = 'BSBAFNMG2714' THEN 'BS Bus Admin/Finance/Mgmt'
WHEN school_program = 'BSBAGBMG9496' THEN 'BBA Bus Admin/Gen Bus-Mgmt'
WHEN school_program = 'BSBAGENBUS' THEN 'BS Business/General Business'
WHEN school_program = 'BSBAGENBUS14' THEN 'BS Business/General Business'
WHEN school_program = 'BSBAGENER14' THEN 'BS Business Administration'
WHEN school_program = 'BSBAGENERIC' THEN 'BS Business Administration'
WHEN school_program = 'BSBAGENMKT14' THEN 'BS Bus Admin/General Marketing'
WHEN school_program = 'BSBAGENMKTG' THEN 'BS Bus Admin/General Marketing'
WHEN school_program = 'BSBAINFMK380' THEN 'BS Bus Adm/Info Syst/Marketing'
WHEN school_program = 'BSBAINFOSYST' THEN 'BS Business/Information System'
WHEN school_program = 'BSBAINFSYS14' THEN 'BS Business/Information System'
WHEN school_program = 'BSBAINNOMG14' THEN 'BS Business Administration'
WHEN school_program = 'BSBAINNOMGMT' THEN 'BS Bus Admin/Innovation Mgmt'
WHEN school_program = 'BSBAINTERBUS' THEN 'BS Business/International Bus'
WHEN school_program = 'BSBAISMG3540' THEN 'BS Bus Admin/Info Systems/Mgmt'
WHEN school_program = 'BSBAISMG9780' THEN 'BS Bus Admin/Info Systems-Mgmt'
WHEN school_program = 'BSBAISMK2231' THEN 'BS Bus Admin/Info Syst/Market'
WHEN school_program = 'BSBAMANAGE' THEN 'BS Business/Management'
WHEN school_program = 'BSBAMANAGE14' THEN 'BS Business/Management'
WHEN school_program = 'BSBAMARKET' THEN 'BS Business/Marketing'
WHEN school_program = 'BSBAMARKET14' THEN 'BS Business/Marketing'
WHEN school_program = 'BSBAMGMK2880' THEN 'BS Bus Adm/Management/Market'
WHEN school_program = 'BSBAMGMK5115' THEN 'BS Bus Admin/Mgmt & Marketing'
WHEN school_program = 'BSBAMGMK5312' THEN 'BS Bus Adm/Management/Market'
WHEN school_program = 'BSBAMKBF7277' THEN 'BS Bus Adm-Marketing/Bank Fin'
WHEN school_program = 'BSBAPJTMGT14' THEN 'BS Bus Admin/Project Mgmt'
WHEN school_program = 'BSBAPROJMGMT' THEN 'BS Bus Admin/Project Mgmt'
WHEN school_program = 'BSBASOCMKT14' THEN 'BS Bus Admin/Social Marketing'
WHEN school_program = 'BSBASOCMKTG' THEN 'BS Bus Admin/Social Marketing'
WHEN school_program = 'BSBCHBIO6823' THEN 'BS Biochemistry and Biology'
WHEN school_program = 'BSBCHCHM1693' THEN 'BS Biochemistry/Chemistry'
WHEN school_program = 'BSBIOBCH5844' THEN 'BS Biology/Biochemistry'
WHEN school_program = 'BSBIOBCH6023' THEN 'BS Biology and Biochemistry'
WHEN school_program = 'BSBIOCHE1983' THEN 'BS Biology and Chemistry'
WHEN school_program = 'BSBIOCHE1985' THEN 'BS Biology and Chemistry'
WHEN school_program = 'BSBIOCHE2294' THEN 'BS Biology and Chemistry'
WHEN school_program = 'BSBIOCHE6893' THEN 'BS Biology and Chemistry'
WHEN school_program = 'BSBIOCHE8274' THEN 'BS Biology and Chemistry'
WHEN school_program = 'BSBIOCHE9269' THEN 'BS Biology and Chemistry'
WHEN school_program = 'BSBIOCHEM886' THEN 'BS Biology and Chemistry'
WHEN school_program = 'BSBIOCHEMIST' THEN 'BS Biochemistry'
WHEN school_program = 'BSBIOCHM2632' THEN 'BS Biology and Chemistry'
WHEN school_program = 'BSBIOCHM6893' THEN 'BS Biology and Chemistry'
WHEN school_program = 'BSBIOCMA3549' THEN 'BS Biochemistry/Mathematics'
WHEN school_program = 'BSBIOENV1800' THEN 'BS Biochemistry/Enrivo Science'
WHEN school_program = 'BSBIOENVSCI' THEN 'BS Biology--Environmental Sci'
WHEN school_program = 'BSBIOLENVSCI' THEN 'BS Biology/Environmental Scien'
WHEN school_program = 'BSBIOLNUTR' THEN 'BS Biology and Nutrition'
WHEN school_program = 'BSBIOLNUTR48' THEN 'BS Biology and Nutrition'
WHEN school_program = 'BSBIOLOGY' THEN 'BS Biology'
WHEN school_program = 'BSBIOLRESEAR' THEN 'BS Biology-Health/Researc/Grad'
WHEN school_program = 'BSBIONMD9233' THEN 'BS Biology/Nuclear Medicine Sc'
WHEN school_program = 'BSBIONMED219' THEN 'BS Biology/Nuclear Medicine'
WHEN school_program = 'BSBIONUT7713' THEN 'BS Biology/Nutrition'
WHEN school_program = 'BSBIONUT9636' THEN 'BS Biol/Nutrition-Nutrition Sc'
WHEN school_program = 'BSBIOSECEDUC' THEN 'BS Biology--Sec Education'
WHEN school_program = 'BSBIOVIS3964' THEN 'BS Biology and Vision Science'
WHEN school_program = 'BSBROADMETEO' THEN 'BS Broadcast Meteorology'
WHEN school_program = 'BSBUGBPM3083' THEN 'BS Bus Adm-Gen Bus/Proj Mgmt'
WHEN school_program = 'BSBUMGMK9361' THEN 'BS Bus Adm-Management/Market'
WHEN school_program = 'BSCHEMAT0983' THEN 'BS Chemistry and Mathematics'
WHEN school_program = 'BSCHEMISTRY' THEN 'BS Chemistry'
WHEN school_program = 'BSCICYPR7885' THEN 'BS Comp Info Sys/Cyber Sec/Pro'
WHEN school_program = 'BSCIS' THEN 'BS Computer Information System'
WHEN school_program = 'BSCISCOMNET' THEN 'BS CIS/Computer Networking'
WHEN school_program = 'BSCISCOMPROG' THEN 'BS CIS/Computer Programming'
WHEN school_program = 'BSCISCSS' THEN 'BS Comp Info Sys/Cyber Sec Sys'
WHEN school_program = 'BSCISCYBER' THEN 'BS CIS/Cyber Security'
WHEN school_program = 'BSCISEMTECH' THEN 'BS CIS/Emerging Technologies'
WHEN school_program = 'BSCISNETSECR' THEN 'BS CIS/Network Security'
WHEN school_program = 'BSCISWEBDEV' THEN 'BS CIS/Web Development'
WHEN school_program = 'BSCJCRCT14' THEN 'BS Criminal Just/Corrections'
WHEN school_program = 'BSCJDIGFOR14' THEN 'BS Crim Just/Digital Forensics'
WHEN school_program = 'BSCJHOMESEC' THEN 'BS CJ/Homeland Sec/Cntr Terror'
WHEN school_program = 'BSCJHOMSEC14' THEN 'BS CJ/Homeland Sec/Cntr Terror'
WHEN school_program = 'BSCLINRESEAR' THEN 'BS Clinical Research'
WHEN school_program = 'BSCOMMHLTHED' THEN 'BS Community Health Education'
WHEN school_program = 'BSCRIJLAW' THEN 'BS Crim Just/Law Enforcement'
WHEN school_program = 'BSCRIJLAW14' THEN 'BS Crim Just/Law Enforcement'
WHEN school_program = 'BSCRIMJUST' THEN 'BS Criminal Justice'
WHEN school_program = 'BSCRIMJUST15' THEN 'BS Criminal Justice'
WHEN school_program = 'BSCRJCORRECT' THEN 'BS Criminal Just/Corrections'
WHEN school_program = 'BSCRJCRMIN14' THEN 'BS Crim Jus/Crim Investigation'
WHEN school_program = 'BSCRJJUVJU14' THEN 'BS Crim Jus/Juvenile Justice'
WHEN school_program = 'BSCRJUCRMINV' THEN 'BS Crim Jus/Crim Investigation'
WHEN school_program = 'BSCRJUDIGFOR' THEN 'BS Crim Just/Digital Forensics'
WHEN school_program = 'BSCRJUJUVJUS' THEN 'BS Crim Jus/Juvenile Justice'
WHEN school_program = 'BSCYBERSEC' THEN 'BS Cyber Security'
WHEN school_program = 'BSCYBRSECSYS' THEN 'BS Cyber Security Systems'
WHEN school_program = 'BSEMGMAT2737' THEN 'BS Engineering Mgmt/Mathematic'
WHEN school_program = 'BSEMGMAT5034' THEN 'BS Engineering Mgmt/Mathematic'
WHEN school_program = 'BSEMGMAT7186' THEN 'BS Engineering Mgmt/Mathematic'
WHEN school_program = 'BSENGINEERIN' THEN 'BS Engineering'
WHEN school_program = 'BSENGRELEC' THEN 'BS Engineering/Electrical'
WHEN school_program = 'BSENGRELECMX' THEN 'BS Engineering/Electrical'
WHEN school_program = 'BSENGRMECHAT' THEN 'BS Engineering/Mechatronics'
WHEN school_program = 'BSENGRMECHAX' THEN 'BS Engineering/Mechatronics'
WHEN school_program = 'BSENGRMECHNL' THEN 'BS Engineering/Mechanical'
WHEN school_program = 'BSENGRMGMT' THEN 'BS Engineering Management'
WHEN school_program = 'BSENMGMT5034' THEN 'BS Engineer Mgmt/Mathematics'
WHEN school_program = 'BSENVIRONSCI' THEN 'BS Environmental Science'
WHEN school_program = 'BSFDNUT' THEN 'BS Nutrition(Food & Nutrition)'
WHEN school_program = 'BSGENCRIMJUS' THEN 'BS General Criminal Justice'
WHEN school_program = 'BSGENPSYC' THEN 'BS General Psychology'
WHEN school_program = 'BSGENPSYC15' THEN 'BS General Psychology'
WHEN school_program = 'BSHEALTHSCI' THEN 'BS Health Sciences'
WHEN school_program = 'BSHLTHSCIADM' THEN 'BS Health Sci/Administration'
WHEN school_program = 'BSHLTHSCIGEN' THEN 'BS Health Sciences/General'
WHEN school_program = 'BSHLTHSCINUT' THEN 'BS Health Sciences/Nutrition'
WHEN school_program = 'BSHSCBILLCOD' THEN 'BS Hth Sci/Cert Bill/Coding Sp'
WHEN school_program = 'BSHSCHTHINFO' THEN 'BS Hlth Sci/Reg Hlth Info Tech'
WHEN school_program = 'BSHSCMEDTRAN' THEN 'BS Hth Sci/Reg Med Transcript'
WHEN school_program = 'BSHSCMOA' THEN 'BS Hth Sci/Cert Med Off Asst'
WHEN school_program = 'BSHSCRAT' THEN 'BS Hth Sci/Card Rhy Anlys Tech'
WHEN school_program = 'BSHSHLTRECSP' THEN 'BS Hlth Sci/Crt El Hlth Rec Sp'
WHEN school_program = 'BSHTHSCADM15' THEN 'BS Health Sci/Administration'
WHEN school_program = 'BSHTHSCGEN15' THEN 'BS Health Sciences/General'
WHEN school_program = 'BSHTHSCNUT15' THEN 'BS Health Sciences/Nutrition'
WHEN school_program = 'BSINORGPSYC' THEN 'BS Indust/Organizational Psych'
WHEN school_program = 'BSKINESIOLOG' THEN 'BS Kinesiology (All-Level)'
WHEN school_program = 'BSKINNONCERT' THEN 'BS Kinesiology (Non-Cert)'
WHEN school_program = 'BSKINPERTRNR' THEN 'BS Kinesiology/Persnal Trainer'
WHEN school_program = 'BSLEADSTDS' THEN 'BS Leadership Studies'
WHEN school_program = 'BSMAMT4577' THEN 'BS Mathematics and Meteorology'
WHEN school_program = 'BSMATH' THEN 'BS Mathematics'
WHEN school_program = 'BSMATHSTATS' THEN 'BS Mathematics/Statistics'
WHEN school_program = 'BSMATMET4577' THEN 'BS Mathematics/Meteorology'
WHEN school_program = 'BSMEDINSCOD' THEN 'BS Med Insurance Coding Spec'
WHEN school_program = 'BSMETEROLOGY' THEN 'BS Meterology'
WHEN school_program = 'BSNALT' THEN 'BSN RN to BSN (Alternate)'
WHEN school_program = 'BSNGEN' THEN 'BSN Generic Pathway'
WHEN school_program = 'BSNUCLEARMED' THEN 'BS Nuclear Medicine Science'
WHEN school_program = 'BSNUDISC8572' THEN 'BS Nutrition-Dietetics/Science'
WHEN school_program = 'BSNUTRITION' THEN 'BS Nutrition (Dietetics)'
WHEN school_program = 'BSNUTSCIENCE' THEN 'BS Nutrition (Sciences)'
WHEN school_program = 'BSPENONCERT' THEN 'BS PE (Non-Cert) 639240'
WHEN school_program = 'BSPHYSICALED' THEN 'BS Physical Education'
WHEN school_program = 'BSPUBADMIN14' THEN 'BS Public Administration'
WHEN school_program = 'BSREGHLTHINF' THEN 'BS Reg Hlth Inform Technician'
WHEN school_program = 'BSREHABPRAT' THEN 'BS Rehab Sci/Pre-Athletic Trng'
WHEN school_program = 'BSREHABPRMED' THEN 'BS Rehab Sci/Pre-Medicine'
WHEN school_program = 'BSREHABPRPA' THEN 'BS Rehab Sci/Pre-Physic Asst'
WHEN school_program = 'BSREHABPRPT' THEN 'BS Rehab Sci/Pre-Physical Ther'
WHEN school_program = 'BSREHABSCIEN' THEN 'BS Rehabilitative Sciences'
WHEN school_program = 'BSREHATH4468' THEN 'BS Rehab Science/Athletic Trng'
WHEN school_program = 'BSSTATISTICS' THEN 'BS Statistics'
WHEN school_program = 'BSVISIONSCI' THEN 'BS Vision Science'
WHEN school_program = 'CERTPMCNL' THEN 'Post-Master Clin Nurse Leader'
WHEN school_program = 'CERTPMCNS' THEN 'Post-Masters Clin Nurse Spec'
WHEN school_program = 'CISPREQ12' THEN 'CIS 12 Hour Requirement'
WHEN school_program = 'CISPREREQ' THEN 'CIS Prerequisites'
WHEN school_program = 'CONSORTIUMGR' THEN 'Consortium Graduate Program'
WHEN school_program = 'CONSORTIUMUG' THEN 'Consortium Undergrad Program'
WHEN school_program = 'CONTEDUC' THEN 'Continuing Education'
WHEN school_program = 'CSECPREREQ' THEN 'CSEC Pre-Requisites'
WHEN school_program = 'DBA' THEN 'Doctor/Business Administration'
WHEN school_program = 'DBA13' THEN 'Doctor/Business Administration'
WHEN school_program = 'DBA14' THEN 'Doctor/Business Adminstration'
WHEN school_program = 'DNP' THEN 'Doctor of Nursing Practice'
WHEN school_program = 'DNPFNP' THEN 'Doctor/Nurs Prac-Fam Nurs Prac'
WHEN school_program = 'DNPNURS' THEN 'Doctor of Nursing Practice'
WHEN school_program = 'DNPPSYC' THEN 'Doc/Nrs Prac-Psy Mntl Hlth Pra'
WHEN school_program = 'DO' THEN 'Doctor of Osteopathic Medicine'
WHEN school_program = 'EAPCCGR' THEN 'EAP College Consortium GR'
WHEN school_program = 'EAPCCUG' THEN 'EAP College Consortium UG'
WHEN school_program = 'EAPOCICUGR' THEN 'EAP OCICU Consortium GR'
WHEN school_program = 'EAPOCICUUG' THEN 'EAP OCICU Consortium UG'
WHEN school_program = 'ELDPT' THEN 'Doctor of Physical Therapy'
WHEN school_program = 'ELDPT34' THEN 'Doctor of Physical Therapy'
WHEN school_program = 'ERRORCODE' THEN 'ERROR CODE CORRECTION'
WHEN school_program = 'FAMNURSPRAC' THEN 'Family Nurse Practitioner Cert'
WHEN school_program = 'HIW_HS' THEN 'Incarnate Word High School'
WHEN school_program = 'HSA_HS' THEN 'St. Anthonys High School'
WHEN school_program = 'HSA_PREP' THEN 'UIW Prep High School'
WHEN school_program = 'MAA903938' THEN 'MAA Adm/Com Art-I/O Psy-Org Dv'
WHEN school_program = 'MAAAADOD3018' THEN 'MAA Applied Admin/Org Develop'
WHEN school_program = 'MAAAAOD' THEN 'MAA Applied Admin/Org Develop'
WHEN school_program = 'MAAAAORD6208' THEN 'MAA Applied Admin/Org Develop'
WHEN school_program = 'MAAADCAOD024' THEN 'MAA Admin/Comm Arts/Org Devlpm'
WHEN school_program = 'MAAADEOD2919' THEN 'MAA Adult Educ/Org Development'
WHEN school_program = 'MAAADM903938' THEN 'MAA Adm-ComArt/I O Psy/Org Dev'
WHEN school_program = 'MAAADMIN' THEN 'MAA General Administration'
WHEN school_program = 'MAAADULTED' THEN 'MAA Adult Education'
WHEN school_program = 'MAAADULTED14' THEN 'MAA Adult Education'
WHEN school_program = 'MAAAEDOD2234' THEN 'MAA Adult Educ/Org Development'
WHEN school_program = 'MAAAEDOD3409' THEN 'MAA Adult Educ/Org Development'
WHEN school_program = 'MAAAPAOD3150' THEN 'MAA Admin/Appld Admin-Org Dev'
WHEN school_program = 'MAAAPPADM' THEN 'MAA Applied Administration'
WHEN school_program = 'MAAAPPADM13' THEN 'MAA Applied Administration'
WHEN school_program = 'MAAAPPADM14' THEN 'MAA Applied Administration'
WHEN school_program = 'MAACAORD1024' THEN 'MAA Comm Arts/Org Development'
WHEN school_program = 'MAACOMMART' THEN 'MAA Communication Arts'
WHEN school_program = 'MAACOMMART14' THEN 'MAA Communication Arts'
WHEN school_program = 'MAACRIJLEAD' THEN 'MAA Crim Justice Leadership'
WHEN school_program = 'MAADMINISTRA' THEN 'MAA Administration'
WHEN school_program = 'MAAENGL' THEN 'MAA English Rhetoric/Writing'
WHEN school_program = 'MAAGENER14' THEN 'Master of Arts/Administration'
WHEN school_program = 'MAAGENERIC' THEN 'Master of Arts/Administration'
WHEN school_program = 'MAAHAOD6454' THEN 'MAA Healthcare Adm/Org Devlpmt'
WHEN school_program = 'MAAHCOD2326' THEN 'MAA Healthcare Adm/Org Develop'
WHEN school_program = 'MAAHCOD8727' THEN 'MAA Healthcare Adm/Org Develop'
WHEN school_program = 'MAAHLADOD316' THEN 'MAA Admin/Hlth Admin/Org Devlp'
WHEN school_program = 'MAAHLTHCAR14' THEN 'MAA Health Care Administration'
WHEN school_program = 'MAAHLTHCARE' THEN 'MAA Healthcare Administration'
WHEN school_program = 'MAAHLTORD884' THEN 'MAA Healthcare Adm/Org Develop'
WHEN school_program = 'MAAINSTTECH' THEN 'MAA Instructional Technology'
WHEN school_program = 'MAAINTOD8832' THEN 'MAA Instruct Tech/Org Develop'
WHEN school_program = 'MAAIOPSYC' THEN 'MAA Indus/Organizational Psych'
WHEN school_program = 'MAAIOPSYC14' THEN 'MAA Indust/Organizational Psyc'
WHEN school_program = 'MAAMULTSCI' THEN 'MAA Multidisciplinary Sciences'
WHEN school_program = 'MAAMULTSCI14' THEN 'MAA Multidisciplinary Sciences'
WHEN school_program = 'MAANUTR' THEN 'MAA Nutrition'
WHEN school_program = 'MAAODHAD6831' THEN 'MAA Org Dev/Healthcare Admin'
WHEN school_program = 'MAAORDIT7696' THEN 'MAA Instr Tech/Org Development'
WHEN school_program = 'MAAORGDEV' THEN 'MAA Organizational Development'
WHEN school_program = 'MAAORGDEV14' THEN 'MAA Organizational Development'
WHEN school_program = 'MAASPMG' THEN 'MAA Sports Management'
WHEN school_program = 'MAAURBAN' THEN 'MAA Urban Administration'
WHEN school_program = 'MABIOLOGY' THEN 'MA Biology'
WHEN school_program = 'MACOMARTTHES' THEN 'MA Comm Arts Thesis Option'
WHEN school_program = 'MACOMMART20' THEN 'MA Communication Arts'
WHEN school_program = 'MACOMMARTCAP' THEN 'MA Comm Arts Capstone Option'
WHEN school_program = 'MACOMMARTS' THEN 'MA Communication Arts'
WHEN school_program = 'MACROSSCULT' THEN 'MA Cross-Cultural Education'
WHEN school_program = 'MAEARLYCHILD' THEN 'MA Early Childhood Education'
WHEN school_program = 'MAECHILDLIT' THEN 'MA Early Childhood Literacy'
WHEN school_program = 'MAEDDIVEDUC' THEN 'MA Diversity Education'
WHEN school_program = 'MAEDORGLRN' THEN 'MA Organizational Learning'
WHEN school_program = 'MAEDPHYSED' THEN 'MA Education Physical Educ'
WHEN school_program = 'MAEDPROGEVAL' THEN 'MA Educ/Program Evaluation'
WHEN school_program = 'MAEDSCHLEAD' THEN 'MA Educ/School Leadership'
WHEN school_program = 'MAEDSTUSERV' THEN 'MA Educ/Student Services'
WHEN school_program = 'MAEDUCADLTED' THEN 'MA Adult Education'
WHEN school_program = 'MAEDUCATION' THEN 'MA Education'
WHEN school_program = 'MAEDUCKINE' THEN 'MA Education Kinesiology'
WHEN school_program = 'MAEDUCREAD' THEN 'MA Education Reading'
WHEN school_program = 'MAENGLISH' THEN 'MA English'
WHEN school_program = 'MAFASDESNOTH' THEN 'MA Fashion Design'
WHEN school_program = 'MAFASDESTHES' THEN 'MA Fashion Design'
WHEN school_program = 'MAFASHDESIGN' THEN 'MA Fashion Design'
WHEN school_program = 'MAINSTRTECH' THEN 'MA Instructional Technology'
WHEN school_program = 'MAINTERNEDUC' THEN 'MA International Education'
WHEN school_program = 'MAMATHTCHG' THEN 'MA Mathematics Teaching'
WHEN school_program = 'MAMULTISCI' THEN 'MA Multidisciplinary Sciences'
WHEN school_program = 'MAMULTISTD20' THEN 'MA Multidisciplinary Studies'
WHEN school_program = 'MAMULTISTDS' THEN 'MA Multidisciplinary Studies'
WHEN school_program = 'MAMULTST8751' THEN 'MA Multidisciplinary Studies'
WHEN school_program = 'MAOLTCHTRN' THEN 'MA Online Teach/Training'
WHEN school_program = 'MAORGLDLRN' THEN 'MA Org Leadership/Learning'
WHEN school_program = 'MAORGLRNLEAD' THEN 'MA Org Learning/Leadership'
WHEN school_program = 'MAPASTMINIST' THEN 'MA Pastoral Ministry'
WHEN school_program = 'MARELMINHISP' THEN 'MA Rel Stds/Min with Hispanics'
WHEN school_program = 'MARELSCATECH' THEN 'MA Rel Stds/Catechesis'
WHEN school_program = 'MARELSPAST' THEN 'MA Religious Stds/Pastoral Ins'
WHEN school_program = 'MARELSPIRIT' THEN 'MA Rel Stds/Spirituality'
WHEN school_program = 'MARELSYOUTH' THEN 'MA Rel Stds/Youth Ministry'
WHEN school_program = 'MARELTHEOSTD' THEN 'MA Rel Stds/Theological Stds'
WHEN school_program = 'MASPECEDUC' THEN 'MA Special Education'
WHEN school_program = 'MATALLVTEACH' THEN 'MAT All Level Teaching'
WHEN school_program = 'MATCHLEAD15' THEN 'MA Teacher Leadership'
WHEN school_program = 'MATCHLEAD23' THEN 'MA Teacher Leadership'
WHEN school_program = 'MATEACHLEAD' THEN 'MA Teacher Leadership'
WHEN school_program = 'MATELEM' THEN 'MAT Teaching Elementary'
WHEN school_program = 'MATSECOND' THEN 'MAT Teaching Secondary'
WHEN school_program = 'MBA989031' THEN 'MBA Intntl Business/Marketing'
WHEN school_program = 'MBAASDAT7221' THEN 'MBA Asset Mgmt/Data Analysis'
WHEN school_program = 'MBABUSADM' THEN 'MBA Business Administration'
WHEN school_program = 'MBAFINANCE' THEN 'MBA Finance'
WHEN school_program = 'MBAGENERIC' THEN 'Master/Business Administration'
WHEN school_program = 'MBAINTERN' THEN 'MBA International Business'
WHEN school_program = 'MBAMARKETING' THEN 'MBA Marketing'
WHEN school_program = 'MBASPORT' THEN 'MBA Sports Management'
WHEN school_program = 'MBSBIOMEDSCI' THEN 'MBS Biomedical Sciences'
WHEN school_program = 'MECROSSCULT' THEN 'MEd Cross-Cultural Education'
WHEN school_program = 'MEDADLTEDUC' THEN 'MEd Adult Education'
WHEN school_program = 'MEDDIVEDUC' THEN 'MEd Diversity Education'
WHEN school_program = 'MEDECHILDLIT' THEN 'MEd Early Childhood Literacy'
WHEN school_program = 'MEDEDUCATION' THEN 'MEd Education'
WHEN school_program = 'MEDEDUCKINE' THEN 'MEd Education Kinesiology'
WHEN school_program = 'MEDEDUCREAD' THEN 'MEd Education Reading'
WHEN school_program = 'MEDERCHILD' THEN 'MEd Early Childhood Education'
WHEN school_program = 'MEDINSTTECH' THEN 'MEd Instructional Technology'
WHEN school_program = 'MEDINTERNED' THEN 'MEd International Education'
WHEN school_program = 'MEDOLTCHTRN' THEN 'MEd Online Teaching/Training'
WHEN school_program = 'MEDORGLRNG' THEN 'MEd Organizational Learning'
WHEN school_program = 'MEDORGLRNLEA' THEN 'MEd Org Learning/Leadership'
WHEN school_program = 'MEDPHYSEDUC' THEN 'MEd Physical Education'
WHEN school_program = 'MEDSCHLEAD' THEN 'MEd Educ/School Leadership'
WHEN school_program = 'MEDSPECEDUC' THEN 'MEd Special Education'
WHEN school_program = 'MEDSTUSERV' THEN 'MEd Student Services'
WHEN school_program = 'MEDTCHRLEAD' THEN 'MEd Teacher Leadership'
WHEN school_program = 'MEDTEFLTESL' THEN 'M.Ed. TEFL/TESL'
WHEN school_program = 'MEEDPROGEVAL' THEN 'MEd Educ/ Program Evaluation'
WHEN school_program = 'METCHLRNECED' THEN 'MEd Teach/Learn Early Child Ed'
WHEN school_program = 'METEACHLEARN' THEN 'MEd Teaching and Learning'
WHEN school_program = 'MHAHEALTHADM' THEN 'Master/Health Administration'
WHEN school_program = 'MINACCT' THEN 'Minor Accounting'
WHEN school_program = 'MINALEDUC' THEN 'Minor All Level Education'
WHEN school_program = 'MINANTHRO' THEN 'Minor Anthropology'
WHEN school_program = 'MINART' THEN 'Minor Art'
WHEN school_program = 'MINARTHIST' THEN 'Minor Art History'
WHEN school_program = 'MINBIOLOGY' THEN 'Minor Biology'
WHEN school_program = 'MINBRZLSTDS' THEN 'Minor Brazilian Studies'
WHEN school_program = 'MINBUSADM' THEN 'Minor Business Administration'
WHEN school_program = 'MINCART' THEN 'Minor Computer Graphic Arts'
WHEN school_program = 'MINCHEMISTRY' THEN 'Minor Chemistry'
WHEN school_program = 'MINCOMMARTS' THEN 'Minor Communication Arts'
WHEN school_program = 'MINCULTSTDS' THEN 'Minor Cultural Studies'
WHEN school_program = 'MINECON' THEN 'Minor Economics'
WHEN school_program = 'MINENGLISH' THEN 'Minor English'
WHEN school_program = 'MINENSCIBIOL' THEN 'Min Environmental Sci/Biol Maj'
WHEN school_program = 'MINENSCICHEM' THEN 'Min Environmental Sci/Chem Maj'
WHEN school_program = 'MINENVIRONSC' THEN 'Minor Environmental Science'
WHEN school_program = 'MINFASHDESN' THEN 'Minor Fashion Design'
WHEN school_program = 'MINFASHMERC' THEN 'Minor Fashion Merchandising'
WHEN school_program = 'MINFASHMGMT' THEN 'Minor Fashion Management'
WHEN school_program = 'MINGEOLOGY' THEN 'Minor Geology'
WHEN school_program = 'MINHISTORY' THEN 'Minor History'
WHEN school_program = 'MININENDESN' THEN 'Min Inter Environmental Design'
WHEN school_program = 'MININFORM' THEN 'Minor Information Systems'
WHEN school_program = 'MINMATH' THEN 'Minor Mathematics'
WHEN school_program = 'MINMGMT' THEN 'Minor Management'
WHEN school_program = 'MINMKTG' THEN 'Minor Marketing'
WHEN school_program = 'MINMUSIC' THEN 'Minor Music'
WHEN school_program = 'MINMUSTHRPY' THEN 'Minor Music Therapy'
WHEN school_program = 'MINNUTRITION' THEN 'Minor Nutrition'
WHEN school_program = 'MINPHOTO' THEN 'Minor Photography'
WHEN school_program = 'MINPHYSEDUC' THEN 'Minor Physical Education'
WHEN school_program = 'MINPHYSICS' THEN 'Minor Physics'
WHEN school_program = 'MINPOLSCI' THEN 'Minor Political Science'
WHEN school_program = 'MINPSYCH' THEN 'Minor Psychology'
WHEN school_program = 'MINREADING' THEN 'Minor Reading'
WHEN school_program = 'MINRELSTDS' THEN 'Minor Religious Studies'
WHEN school_program = 'MINSECEDUC' THEN 'Minor Secondary Education'
WHEN school_program = 'MINSOCIOLOGY' THEN 'Minor Sociology'
WHEN school_program = 'MINSPANISH' THEN 'Minor Spanish'
WHEN school_program = 'MINTEXTILE' THEN 'Minor Textile'
WHEN school_program = 'MINTHEATRE' THEN 'Minor Theatre Arts'
WHEN school_program = 'MSACCOUNTING' THEN 'MS Accounting'
WHEN school_program = 'MSACCTASSFIN' THEN 'MS  Acct-Assurance/Fin Report'
WHEN school_program = 'MSACCTTAX' THEN 'MS Accounting/Tax'
WHEN school_program = 'MSAPPLSTATS' THEN 'MS Applied Statistics'
WHEN school_program = 'MSBIOLOGY' THEN 'MS Biology'
WHEN school_program = 'MSBUSADM' THEN 'MS Business Administration'
WHEN school_program = 'MSCOMMPSYC' THEN 'MS Community Psychology'
WHEN school_program = 'MSEDPSYNOTHE' THEN 'MS Educational Psychology (NT)'
WHEN school_program = 'MSEDUCPSYC' THEN 'MS Educational Psychology'
WHEN school_program = 'MSHEALTHINFO' THEN 'MS Health Informatics'
WHEN school_program = 'MSINORPSYC' THEN 'MS Industrial/Organizatl Psyc'
WHEN school_program = 'MSINORPSYCNT' THEN 'MS Industrial/Organ Psyc (NT)'
WHEN school_program = 'MSISC' THEN 'MS Internatnl Sport Coaching'
WHEN school_program = 'MSKINESIOLOG' THEN 'MS Kinesiology'
WHEN school_program = 'MSMATH' THEN 'MS Mathematics'
WHEN school_program = 'MSMEDNUTR' THEN 'MS Medical Nutrition'
WHEN school_program = 'MSNCNSADUGER' THEN 'MSN Clin Nrs Spec/Adult Geront'
WHEN school_program = 'MSNMBA' THEN 'MSN-MBA Nursing/Business Admin'
WHEN school_program = 'MSNNURADMIN' THEN 'MSN Nursing Administration'
WHEN school_program = 'MSNNURBNL' THEN 'RN-MSN Bridge Track'
WHEN school_program = 'MSNNURCNL' THEN 'MSN Clinical Nurse Leader'
WHEN school_program = 'MSNNURCNS' THEN 'MSN Clinical Nurse Specialist'
WHEN school_program = 'MSNNUREDUC' THEN 'MSN Nursing Education'
WHEN school_program = 'MSNNURS' THEN 'MSN Nursing'
WHEN school_program = 'MSNNURSLEAD' THEN 'MSN Nursing Leadership'
WHEN school_program = 'MSNUTRADMCAP' THEN 'MS Nutrition Admin (Capstone)'
WHEN school_program = 'MSNUTRADMN' THEN 'MS Nutrition Administration'
WHEN school_program = 'MSNUTRADMTHS' THEN 'MS Nutrition Admin (Thesis)'
WHEN school_program = 'MSNUTRCAP' THEN 'MS Nutrition (Capstone)'
WHEN school_program = 'MSNUTREDCAP' THEN 'MS Nutrition Ed/Health Promo'
WHEN school_program = 'MSNUTREDTHES' THEN 'MS Nutrition Ed/Health Promo'
WHEN school_program = 'MSNUTREDUC' THEN 'MS Nutrition Educ/Health Promo'
WHEN school_program = 'MSNUTRITION' THEN 'MS Nutrition'
WHEN school_program = 'MSNUTRTHESIS' THEN 'MS Nutrition (Thesis)'
WHEN school_program = 'MSORGDEVLE14' THEN 'MS Org Development/Leadership'
WHEN school_program = 'MSORGDEVLEAD' THEN 'MS Org Development/Leadership'
WHEN school_program = 'MSPSYC' THEN 'MS Psychology'
WHEN school_program = 'MSRESRCSTATS' THEN 'MS Research Statistics'
WHEN school_program = 'MSSPORTPSYC' THEN 'MS Sport Psychology'
WHEN school_program = 'MSSPORTSMGMT' THEN 'MS Sports Management'
WHEN school_program = 'MSVISIONSCI' THEN 'MS Vision Science'
WHEN school_program = 'NONDEGREE' THEN 'Non-Degree'
WHEN school_program = 'NONDEGREEGR' THEN 'Non-Degree Graduate'
WHEN school_program = 'OPTOMETRY' THEN 'Doctor of Optometry'
WHEN school_program = 'OPTOMETRY2' THEN 'Doctor of Optometry'
WHEN school_program = 'PHARMACY' THEN 'Pharmacy'
WHEN school_program = 'PHARMD' THEN 'Pharmacy'
WHEN school_program = 'PHDEDINEE' THEN 'PhD Intnl Ed Entrepreneurship'
WHEN school_program = 'PHDEDUCINEE' THEN 'PhD Intnl Ed/Entrepreneurship'
WHEN school_program = 'PHDHIGHEDADM' THEN 'PhD Higher Education:  Admin'
WHEN school_program = 'PHDHIGHEDPRO' THEN 'PhD Higher Education Professor'
WHEN school_program = 'PHDHIGHEDUC' THEN 'PhD Higher Education'
WHEN school_program = 'PHDHIGHERED' THEN 'PhD Higher Education'
WHEN school_program = 'PHDMATH' THEN 'PhD Mathematics Education'
WHEN school_program = 'PHDMATHEDUC' THEN 'PhD Mathematics Education'
WHEN school_program = 'PHDMTH657133' THEN 'PhD Mathematics Education'
WHEN school_program = 'PHDORGLDSP' THEN 'PhD Organizational Leadership'
WHEN school_program = 'PHDORGLEAD' THEN 'PhD Organizational Leadership'
WHEN school_program = 'PHDORLDADLED' THEN 'PhD Organizational Leadership'
WHEN school_program = 'PHDORLDERLCH' THEN 'PhD Organization Leadership'
WHEN school_program = 'PHDORLDINEE' THEN 'PhD Organizational Leadership'
WHEN school_program = 'PHDORLDKINES' THEN 'PhD Organizational Leadership'
WHEN school_program = 'PHDORLDONLTT' THEN 'PhD Organizational Leadership'
WHEN school_program = 'PHDORLDPROEV' THEN 'PhD Organizational Leadership'
WHEN school_program = 'PHDORLDSCHLD' THEN 'PhD Organizational Leadership'
WHEN school_program = 'PHDORLDSPTMG' THEN 'PhD Organizational Leadership'
WHEN school_program = 'PHDORLDSTSV' THEN 'PhD Organizational Leadership'
WHEN school_program = 'PHDVISIONSCI' THEN 'PhD Vision Science'
WHEN school_program = 'PMBAASSETMGM' THEN 'MBA Asset Management'
WHEN school_program = 'PMBAASTMGT14' THEN 'MBA Asset Management'
WHEN school_program = 'PMBADATA' THEN 'MBA Data Analytics'
WHEN school_program = 'PMBADATA14' THEN 'MBA Data Analytics'
WHEN school_program = 'PMBAGEN' THEN 'MBA Business Administration'
WHEN school_program = 'PMBAGEN14' THEN 'MBA Business Administration'
WHEN school_program = 'PMBAGENER14' THEN 'MBA Business Administration'
WHEN school_program = 'PMBAGENERIC' THEN 'Master/Business Administration'
WHEN school_program = 'PMBAHRMGMT' THEN 'MBA Human Resource Management'
WHEN school_program = 'PMBAHRMGT14' THEN 'MBA Human Resource Management'
WHEN school_program = 'PPDPT' THEN 'Doctor of Physical Therapy'
WHEN school_program = 'PPDPT34' THEN 'Doctor of Physical Therapy'
WHEN school_program = 'PRENURSGEN' THEN 'BS Nursing'
WHEN school_program = 'PREPHARBIOL' THEN 'Pre-Pharmacy Biology'
WHEN school_program = 'PREPHARCHEM' THEN 'Pre-Pharmacy Chemistry'
WHEN school_program = 'PREPHARMACY' THEN 'Pre-Pharmacy'
WHEN school_program = 'PREREQ3381' THEN 'PSYC 3381 Prerequisites'
WHEN school_program = 'PREREQ4320' THEN 'PSYC 4320 Prerequisites'
WHEN school_program = 'PREREQ4331' THEN 'PSYC 4331 Prerequisites'
WHEN school_program = 'PREREQPROG' THEN 'Prerequisite Checking'
WHEN school_program = 'PSYCHLTHPRAC' THEN 'Psych Mntl Hlth Nurs Prac Cert'
WHEN school_program = 'RELPREREQ' THEN 'Prerequisite for Advanced RELS'
WHEN school_program = 'UGCORE' THEN 'Undecided Core Curriculum'
ELSE SCHOOL_PROGRAM END SCHOOL_PROGRAM
,STARTED_APPLICATION_INDICATOR
,CASE WHEN LEN(STATE) = 2 AND LEN(REGEXP_REPLACE(LEFT(ZIP5,5),'[^0-9]','')) = 5 THEN STATE ELSE NULL END STATE
,STUDENT_TYPE
,STUDENT_TYPE_SOURCE_VALUE
,SUBMITTED_APPLICATION_INDICATOR
,SUFFIX
,TEXT_MESSAGE_OPT_OUT_INDICATOR
,US_CITIZENSHIP_STATUS
,WITHDRAW_DATE
,WITHDRAWN_INDICATOR
,YEARS_EMPLOYED
,YOUNG_ALUMNI_INDICATOR
,CASE WHEN LEN(STATE) = 2 AND LEN(REGEXP_REPLACE(LEFT(ZIP5,5),'[^0-9]','')) = 5 THEN LEFT(ZIP5,5) ELSE NULL END ZIP5													   
																					   
--select *													  
from
<[ALR].[Applicant]> as a