package access;

import java.util.List;

import org.antlr.v4.runtime.CommonTokenStream;
import org.antlr.v4.runtime.Parser;
import org.antlr.v4.runtime.ParserRuleContext;

import errorhandling.ParseErrorCollector;
import errorhandling.ParseErrorListener;
import errorhandling.SyntaxError;


/**
 * AbstractParserAccess.java
 * This set of classes will provide a common set of functions for working with PSS parsers for
 * external and embedded use.
 * 
 * It allows command line and embedded, cross-language access to creating and using the parser.
 */
public abstract class AbstractParserAccess {

    // showAmbiguities: If true, the parser will display ambiguities in the SQL query.
    protected boolean showAmbiguities = false;
    // showFullContext: If true, the parser will provide full context information during parsing.
    protected boolean showFullContext = false;
    // showContextSensitivty: If true, the parser will consider context sensitivity in the
    protected boolean showContextSensitivty = false;

    public void setShowAmbiguities(boolean showAmbiguities) {
        this.showAmbiguities = showAmbiguities;
    }
    public void setShowFullContext(boolean showFullContext) {
        this.showFullContext = showFullContext;
    }
    public void setShowContextSensitivty(boolean showContextSensitivty) {
        this.showContextSensitivty = showContextSensitivty;
    }
    public boolean isShowAmbiguities() {
        return showAmbiguities;
    }
    public boolean isShowFullContext() {
        return showFullContext;
    }
    public boolean isShowContextSensitivty() {
        return showContextSensitivty;
    }

    // Holds the parse tree generated by the parser.
    protected ParserRuleContext parserEmitPoint;

    // This is the result of the Parse and Extraction process
    protected Snippet snippet;

    // This is the error collector used to collect parse errors.
    protected ParseErrorCollector errorCollector;

    // This is the error listener used to collect syntax errors and other messages.
    protected ParseErrorListener errorListener;


    /**
     * Builds a parser instance for the given query.
     * This method should be implemented by subclasses.
     *
     * @param inputText The text to be parsed.
     * @return An instance of a parser ready to parse the provided query.
     */
    public abstract void buildParser(final String inputText);

    public abstract Parser getParser();


    public Snippet getSnippet() {
        // Return the Snippet object containing the results of the parsing and extraction process.
        return this.snippet;
    }   

    // This method creates a CommonTokenStream from the input text.
    protected abstract CommonTokenStream getCommonTokenStream(final String inputText);

    /* COMMON HIDDEN UTILITY METHODS */
        
    // This method adds an error collector to the parser.
    protected void addErrorCollectorToParser(Parser parser) {
        // There is only one ErrorCollector in the Parser.
        // The ParseErrorCollector is a custom error strategy that only collects parse errors.
        // It does not handle errors in any specific way, but allows the parser to continue parsing
        // even if there are syntax errors.
        // This is useful for collecting all errors in a single pass, rather than stopping at the first error.
        // The ParseErrorCollector replaces the default ANTLR object set as the error handler for the parser.

        // You can retrieve the errors later using the getErrorList() method.

        errorCollector = new ParseErrorCollector();
        parser.setErrorHandler(errorCollector);
    }

    // This method adds a custom error listener to the parser.
    protected void addErrorListenerToParser(Parser parser) {
        // Here we add a custom error listener to collect syntax errors and optionally
        // additional Parser generated internal messages (Ambiguities, FullContext and COntextSensitivity).
        // The ParseErrorListener will collect errors and store them in a list.
        // You can retrieve the errors later using the getSyntaxErrors() method on the parser.
        ParseErrorListener errorListener = new ParseErrorListener(showAmbiguities, showFullContext, showContextSensitivty);
            parser.addErrorListener(errorListener);
    }

    /**
     * UNIVERSAL PARSER ACCESS METHODS
     */

    // This method retrieves the count of errors collected by the ParseErrorCollector.
    // It returns the size of the error list, which contains all parse errors encountered during parsing
    // This is the definitive list of errors that failed the parse.  (In contrast to the set of messages in the Listeners
    // which may contain additional messages that are not parse errors, such as ambiguities or context sensitivity messages.)
    public int getFatalErrorCount() {
        // This method retrieves the number of errors collected by the ParseErrorCollector.
        // It returns the size of the error list, which contains all parse errors encountered during parsing.
        if (errorCollector != null) {
            return errorCollector.getErrorList().size();
        }
        return 0;
    }

    public boolean hasFatalErrors() {
        // Check if there are any syntax errors collected by the ParseErrorCollector.
        // This is the definitive list of errors that failed the parse.
        int number = getFatalErrorCount();
        return number > 0; 
    }    

    public List<String> getFatalErrorList() {
        // This method retrieves the list of error messages collected by the ParseErrorCollector.
        // It returns a list of error messages that were collected during parsing.
        if (errorCollector != null) {
            return errorCollector.getErrorList();
        }
        return List.of(); // Return an empty list if no errors are collected
    }

    // This method retrieves the list of error messages collected by the ParseErrorListener.
    // This could be a list of syntax errors, ambiguities, or context sensitivity messages,
    // depending on the configuration of the ParseErrorListener.
    public List<String> getAllErrorStrings() {
        // This method retrieves the syntax errors collected by the ParseErrorListener.
        // It returns a list of error messages that were collected during parsing.
        List<String> errorList = new java.util.ArrayList<>();
        // check for Syntax Errors Captured by the Listeners
        List<?> listeners = getParser().getErrorListeners();
        for (Object listener : listeners) {
            if (listener instanceof ParseErrorListener) {
                for (SyntaxError item : ((ParseErrorListener) listener).getSyntaxErrors()) {
                    errorList.add(item.toString());
                }
            }
        }
        return errorList;
    }


      // This method retrieves the list of SyntaxError objects collected by the ParseErrorListener.
      // Each SyntaxError object contains detailed information about a syntax error encountered during parsing.
      // This could include the line number, character position, and a description of the error.
      // These errors are typically collected by the ParseErrorListener during the parsing process and could 
      // include syntax errors, ambiguities, or context sensitivity messages, depending on the configuration of the listener.
    public List<SyntaxError> getAllErrors() {
        // This method retrieves the syntax errors collected by the ParseErrorListener.
        // It returns a list of SyntaxError objects that were collected during parsing.
        List<SyntaxError> errorList = new java.util.ArrayList<>();
        // check for Syntax Errors Captured by the Listeners
        List<?> listeners = getParser().getErrorListeners();
        for (Object listener : listeners) {
            if (listener instanceof ParseErrorListener) {
                errorList.addAll(((ParseErrorListener) listener).getSyntaxErrors());
            }
        }
        return errorList;
    }

    public boolean hasErrorMessages() {
        // Check if there are any syntax errors collected by the ParseErrorListener.
        List<SyntaxError> syntaxErrors = getAllErrors();
        return syntaxErrors != null && !syntaxErrors.isEmpty(); 
    }

   /**
        * This method is intended to run the parser on the input text.
        * It should be implemented by subclasses to execute the parsing process.
        * The implementation will depend on the specific parser being used (e.g., SQL, PUML3).
        * Different grammars will also have a different set of END POINTS to be called. A parameter
        * must be passed to get the correct end point for the grammar being used.

        * @param endPointType A string representing the endPointType of grammar to be called.
        */
    public abstract void runParser(String endPointType);

    /**
     * This method is intended to generate an Abstract Syntax Tree (AST) from the parse tree and
     * extract the parser objects, collecting them in a Snippet object which could be retrieved
     * using the getSnippet() method. 
     * The implementation will depend on the specific parser being used (e.g., SQL, PUML3).
     * It should be implemented by subclasses to generate the AST based on the parse tree.
     */
    public abstract void generateAST();

    /**
     * Orchestrates the entire parsing operation for a particular input text and end point type.
     * This method should be called to perform the complete parsing operation, including building the parser,
     * running the parser, and generating the AST.
     * 
     * If successful, then the calling process can retrieve the Snippet containing all of the important
     * details of the parsing operation, including the AST, Symbol Table, Table Dictionary,
     * Query Interface, and any captured errors.
     */
    public void executeTheParse(String inputText, String endPointType) {
        // Build the parser for the given input text.
        buildParser(inputText);
        
        // Run the parser on the input text using the specified end point type.
        runParser(endPointType);
        
        // Generate the Abstract Syntax Tree (AST) and extract relevant information into a Snippet.
        generateAST();
    }   
    
}