package access;

import org.antlr.v4.runtime.CharStream;
import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CommonTokenStream;
import org.antlr.v4.runtime.tree.ParseTreeWalker;

import static mumble.PUML3Constants.PUML3_CONDITION_TREE_KEY;
import static mumble.PUML3Constants.PUML3_EQUATION_TREE_KEY;
import puml.walker.PUML3EventWalker;
import puml3.PUML3Lexer;
import puml3.PUML3Parser;

/*
 * PUML3ParserAccess.java
 * This class will allow command line and embedded, cross-language access to the PUML3 parser.
 */
public class PUML3ParserAccess extends AbstractParserAccess {

    // This holds the parser generated by the Access class.
    // It is protected so that subclasses can access it directly.
    protected PUML3Parser parser;

    // This is the event walker used to extract information from the parse tree.
    private PUML3EventWalker extractor;

    // Flags to control the behavior of the parser regarding ambiguities, context, and sensitivity.
    public PUML3ParserAccess(boolean showAmbiguities, boolean showFullContext, boolean showContextSensitivty) {
        // Initialize the parser access with the provided flags.
        setShowAmbiguities(showAmbiguities);
        setShowFullContext(showFullContext);
        setShowContextSensitivty(showContextSensitivty);
        // Constructor can be used for initialization if needed
    }

 	/**
	 * Builds a bespoke PUML3Parser instance for the given SQL query string.
	 * Does not run the parser, but prepares it for parsing.
	 * 
	 * @param query The PUML3 statement string to parse.
	 * @return An instance of PUML3Parser ready to parse the provided query.
	 */
    @Override
	public  void buildParser(final String inputText) {

        try {
            // Create the nested CommonTokenStream from the input query string.
            CommonTokenStream tokens = getCommonTokenStream(inputText);

            // Create a parser for the SQL query using the generated SQLSelectParserParser.
            // The parser will use the tokens from the CommonTokenStream to parse the SQL query            
		    this.parser = new PUML3Parser(tokens);
		
            // Add error listeners and collectors to the parser for error handling.
		    addErrorListenerToParser(this.parser);

		    addErrorCollectorToParser(this.parser);

            this.extractor = new PUML3EventWalker();

        } catch (Exception e) {
            System.err.println("EXCEPTION when adding listener: " + e.getMessage());
            e.printStackTrace();
        }
 	}

    @Override
    public PUML3Parser getParser() {
        // Return the parser instance created by the buildParser method.
        return this.parser; 
    }


    // It is used to tokenize the input query and produce a stream of tokens that can be
    // submitted to the parser for parsing.
    @Override
    protected CommonTokenStream getCommonTokenStream(final String inputText) {
        // Create a CharStream from the input query string.
        CharStream qryStream = CharStreams.fromString(inputText);
        // Create a lexer for the SQL query using the generated SQLSelectParserLexer.
        // The lexer will tokenize the input query and produce a stream of tokens.           
        PUML3Lexer lexer = new PUML3Lexer(qryStream);
        // Create a CommonTokenStream from the lexer.
        // The CommonTokenStream will hold the tokens produced by the lexer and submit them to the parser in sequence. 
        CommonTokenStream tokens = new CommonTokenStream(lexer);
        return tokens;
    }

 
    @Override
    public void runParser(String type) {
        // This method runs the parser on the input text and returns the parse tree.
        if (this.parser == null) {
            throw new IllegalStateException("Parser has not been built. Call buildParser() first.");
        } else if (type.equals(PUML3_CONDITION_TREE_KEY)) {
            this.parserTree = parser.condition();
        } else if (type.equals(PUML3_EQUATION_TREE_KEY)) {
            this.parserTree = parser.equation();
         } else {
            throw new IllegalArgumentException("Invalid Grammar End Point Type Requested: " + type);
        }
    }

    @Override
    public void generateAST() {
        // This method generates the Abstract Syntax Tree (AST) from the parse tree.
        // Walk the parse tree using the extractor.
        if (this.parserTree != null) {
            // Initialize the extractor if it is not already initialized.
            if (this.extractor == null)
                // Create a new instance of SqlParseEventWalker to extract the SQL from the parse tree
                this.extractor = new PUML3EventWalker();
			
 			// walk the tree and extract the SQL USING THE CUSTOM Extractor/Event Walker
            // The ParseTreeWalker.DEFAULT is used to walk the parse tree and call the appropriate methods in the extractor.
            // The extractor will collect the SQL Abstract Syntax Tree, Symbol Table, Table Column Dictionary, Substitution Variables, and Query Interface.
			ParseTreeWalker.DEFAULT.walk(this.extractor, this.parserTree);

            // Save the results in a local Snippet object
            this.snippet = new Snippet(
                this.extractor.getSqlTree(),
                this.extractor.getTableColumnMap(),
                this.extractor.getSymbolTable(),
                this.extractor.getSubstitutionsMap(),
                this.extractor.getInterface()
            );
            // Add the error and other messages to the Snippet object
            snippet.setParserMessageList(this.getAllErrors());
            snippet.setParserMessageStringList(this.getAllErrorStrings());
            snippet.setFatalErrorStringList(this.getFatalErrorList());

       } else {
            throw new IllegalStateException("Parser tree is null. Ensure the parser was run successfully.");    
        }
    }
   

}
