package access;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.antlr.v4.runtime.CharStream;
import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CommonTokenStream;
import org.antlr.v4.runtime.tree.ParseTreeWalker;

import static mumble.MumbleConstants.MUMBLE_EXISTS_KEY;
import static mumble.MumbleConstants.MUMBLE_INTERFACE_KEY;
import static mumble.MumbleConstants.MUMBLE_IN_LIST_KEY;
import static mumble.MumbleConstants.MUMBLE_PREDICAND_KEY;
import static mumble.MumbleConstants.MUMBLE_UNKNOWN_KEY;
import static mumble.SQLParserEndPoints.SQLPARSER_COLUMN_TREE_KEY;
import static mumble.SQLParserEndPoints.SQLPARSER_CONDITION_TREE_KEY;
import static mumble.SQLParserEndPoints.SQLPARSER_INSERT_TREE_KEY;
import static mumble.SQLParserEndPoints.SQLPARSER_IN_LIST_TREE_KEY;
import static mumble.SQLParserEndPoints.SQLPARSER_JOIN_EXTENSION_TREE_KEY;
import static mumble.SQLParserEndPoints.SQLPARSER_PREDICAND_TREE_KEY;
import static mumble.SQLParserEndPoints.SQLPARSER_QUERY_TREE_KEY;
import static mumble.SQLParserEndPoints.SQLPARSER_SQL_TREE_KEY;
import static mumble.SQLParserEndPoints.SQLPARSER_TUPLE_TREE_KEY;
import static mumble.SQLParserEndPoints.SQLPARSER_VALUES_TREE_KEY;
import sql.SQLSelectParserLexer;
import sql.SQLSelectParserParser;
import sql.walker.SqlParseEventWalker;


/*
 * SqlParserAccess.java
 * This class will allow command line and embedded, cross-language access to the SQL parser.
 * 
 * To USE this class, create an instance setting the flags for ambiguities, context, and sensitivity with the constructor method.
 *  SqlParserAccess(boolean showAmbiguities, boolean showFullContext, boolean showContextSensitivty) 
 * 
 * Then call the executeTheParse(String inputText, String endPointType) (from the parent class AbstractParserAccess)
 * method with the SQL query string and the type of parse you want to perform.
 * 
 * The END POINTS of the GRAMMAR define the end point type strings and can be "sql", "column_value", "predicand_value",
 * "in_list_predicate_value", "condition_value", "tuple_value", "values_statement_end", "query_value", or "join_extension_value".
 * 
 * Then retrieve the parser results Snippet object using the getSnippet() method. This will have all of the available
 * information extracted from the parse tree, including the SQL Abstract Syntax Tree, Symbol Table, Table Column Dictionary,
 * Substitution Variables, and the Query Interface, and any errors encountered during parsing.
 */
public class SqlParserAccess extends AbstractParserAccess {

    // This holds the parser generated by the Access class.
    // It is protected so that subclasses can access it directly.
    protected SQLSelectParserParser parser;

 
    // This is the event walker used to extract information from the parse tree.
    private SqlParseEventWalker extractor;

    // Flags to control the behavior of the parser regarding ambiguities, context, and sensitivity.
    public SqlParserAccess(boolean showAmbiguities, boolean showFullContext, boolean showContextSensitivty) {
        // Initialize the parser access with the provided flags.
        this.showAmbiguities = showAmbiguities;
        this.showFullContext = showFullContext;
        this.showContextSensitivty = showContextSensitivty;
    }

 	/**
	 * Builds a bespoke SQLSelectParserParser instance for the given SQL query string.
	 * Does not run the parser, but prepares it for parsing.
	 * 
	 * @param inputText The SQL query string to parse.
	 * @return An instance of SQLSelectParserParser ready to parse the provided query.
	 */
    @Override
	public  void buildParser(final String inputText) {

        try {
            // Create the nested CommonTokenStream from the input query string.
            CommonTokenStream tokens = getCommonTokenStream(inputText);

            // Create a parser for the SQL query using the generated SQLSelectParserParser.
            // The parser will use the tokens from the CommonTokenStream to parse the SQL query            
		    this.parser = new SQLSelectParserParser(tokens);
		
            // Add error listeners and collectors to the parser for error handling.
		    addErrorListenerToParser(this.parser);

		    addErrorCollectorToParser(this.parser);

            this.extractor = new SqlParseEventWalker();

        } catch (Exception e) {
            System.err.println("EXCEPTION when adding listener: " + e.getMessage());
            // Log the full stack trace to standard error
            for (StackTraceElement element : e.getStackTrace()) {
                System.err.println("\tat " + element);
            }
        }

	}

    @Override
    public SQLSelectParserParser getParser() {
        // Return the parser instance created by the buildParser method.
        return this.parser; 
    }

    // It is used to tokenize the input query and produce a stream of tokens that can be
    // submitted to the parser for parsing.
    @Override
    protected CommonTokenStream getCommonTokenStream(final String inputText) {
        // Create a CharStream from the input query string.
        CharStream qryStream = CharStreams.fromString(inputText);
        // Create a lexer for the SQL query using the generated SQLSelectParserLexer.
        // The lexer will tokenize the input query and produce a stream of tokens.           
        SQLSelectParserLexer lexer = new SQLSelectParserLexer(qryStream);
        // Create a CommonTokenStream from the lexer.
        // The CommonTokenStream will hold the tokens produced by the lexer and submit them to the parser in sequence. 
        CommonTokenStream tokens = new CommonTokenStream(lexer);
        return tokens;
    }

    // This method runs the parser on the input text and returns the parse tree.
    // It is called by the executeTheParse method in the parent class AbstractParserAccess.
    @Override
    public void runParser(String type) {
        // This method runs the parser on the input text and returns the parse tree.
        if (this.parser == null) {
            throw new IllegalStateException("Parser has not been built. Call buildParser() first.");
        } else if (type.equals(SQLPARSER_SQL_TREE_KEY)) {
            this.parserEmitPoint = parser.sql();
        } else if (type.equals(SQLPARSER_COLUMN_TREE_KEY)) {
            this.parserEmitPoint = parser.column_value();
        } else if (type.equals(SQLPARSER_PREDICAND_TREE_KEY)) {
            this.parserEmitPoint = parser.predicand_value();
        } else if (type.equals(SQLPARSER_IN_LIST_TREE_KEY)) {
            this.parserEmitPoint = parser.in_list_predicate_value();
        } else if (type.equals(SQLPARSER_CONDITION_TREE_KEY)) {
            this.parserEmitPoint = parser.condition_value();
        } else if (type.equals(SQLPARSER_TUPLE_TREE_KEY)) {
            this.parserEmitPoint = parser.tuple_value();
        } else if (type.equals(SQLPARSER_VALUES_TREE_KEY)) {
            this.parserEmitPoint = parser.values_statement_end();
        } else if (type.equals(SQLPARSER_QUERY_TREE_KEY)) {
            this.parserEmitPoint = parser.query_value();
        } else if (type.equals(SQLPARSER_JOIN_EXTENSION_TREE_KEY)) {
            this.parserEmitPoint = parser.join_extension_value();
        } else if (type.equals(SQLPARSER_INSERT_TREE_KEY)) {
            this.parserEmitPoint = parser.insert_end_point();
         } else {
            throw new IllegalArgumentException("Invalid Grammar End Point Type Requested: " + type);
        }
    }

    @Override
    public void generateAST() {
        // This method generates the Abstract Syntax Tree (AST) from the parse tree.
        // Walk the parse tree using the extractor.
    if (this.parserEmitPoint != null) {
        // Initialize the extractor if it is not already initialized.
        if (this.extractor == null)
            // Create a new instance of SqlParseEventWalker to extract the SQL from the parse tree
            this.extractor = new SqlParseEventWalker();
		
        try{
 			// walk the tree and extract the SQL USING THE CUSTOM Extractor/Event Walker
            // The ParseTreeWalker.DEFAULT is used to walk the parse tree and call the appropriate methods in the extractor.
            // The extractor will collect the SQL Abstract Syntax Tree, Symbol Table, Table Column Dictionary, Substitution Variables, and Query Interface.
			ParseTreeWalker.DEFAULT.walk(this.extractor, this.parserEmitPoint);

        } catch (Exception e) {
            System.err.println("EXCEPTION when walking the parse tree: " + e.getMessage());
            this.addFatalError("Exception when walking the parse tree: " + e.getMessage());
            System.out.println("Exception: " + this.getFatalErrorList());
        }
        // Save the results in a local Snippet object
        this.snippet = this.extractor.getSnippet();

        // Post-parse validations
        validateSingleSubqueryUnknownsAndReportErrors(this.snippet);
        List<String> warnings = validateColumnCoverageWarnings(this.snippet);

        // Add the error and other messages to the Snippet object
        snippet.setParserMessageList(this.getAllErrors());
        List<String> msgs = new ArrayList<>(this.getAllErrorStrings());
        if (warnings != null && !warnings.isEmpty()) {
            msgs.addAll(warnings);
        }
        snippet.setParserMessageStringList(msgs);
        snippet.setFatalErrorStringList(this.getFatalErrorList());

        } else {
            throw new IllegalStateException("Parser tree is null. Ensure the parser was run successfully.");    
        }
    }

    /**
     * If the top-level symbol table has exactly one source and it is a subquery (e.g., "query0"),
     * and there are unknown (unqualified) column references, then verify those columns exist in the
     * subquery's interface. If a column is not present, add a runtime error to the access error list.
     */
    @SuppressWarnings("unchecked")
    private void validateSingleSubqueryUnknownsAndReportErrors(Snippet snippet) {
        if (snippet == null || snippet.getSymbolTable() == null) {
            return;
        }

        Map<String, Object> sym = snippet.getSymbolTable();

        int sourceCount = 0;
        String onlySourceKey = null;
        for (String key : sym.keySet()) {
            Object v = sym.get(key);
            if (!(v instanceof Map)) {
                continue;
            }
            if (key.equals(MUMBLE_INTERFACE_KEY) || key.startsWith("def_")
               || key.startsWith(MUMBLE_PREDICAND_KEY) || key.startsWith(MUMBLE_EXISTS_KEY)
               || key.startsWith(MUMBLE_IN_LIST_KEY)) {
                continue;
            }
            sourceCount++;
            onlySourceKey = key;
        }

        Map<String, Object> unknowns = (Map<String, Object>) sym.get(MUMBLE_UNKNOWN_KEY);
        if (sourceCount == 1 && onlySourceKey != null && onlySourceKey.startsWith("query") && unknowns != null && !unknowns.isEmpty()) {
            Map<String, Object> subq = (Map<String, Object>) sym.get(onlySourceKey);
            Map<String, Object> iface = subq == null ? null : (Map<String, Object>) subq.get(MUMBLE_INTERFACE_KEY);

            for (String col : unknowns.keySet()) {
                boolean inInterface = iface != null && iface.containsKey(col);
                if (!inInterface) {
                    this.addFatalError("Unqualified column '" + col + "' not found in single FROM subquery interface (" + onlySourceKey + ")");
                }
            }
        }
    }

    /**
     * Non-fatal coverage warnings across all sources:
     * - For each unqualified column in UNKNOWN: warn if found in multiple sources (ambiguous),
     *   or warn if not found in any source (unmatched).
     * - For each column recorded under a subquery source, warn if not present in that subquery's interface.
     * - For each column recorded under a table source, warn if not present in that table's dictionary.
     */
    @SuppressWarnings("unchecked")
    private List<String> validateColumnCoverageWarnings(Snippet snippet) {
        List<String> warnings = new ArrayList<>();
        if (snippet == null || snippet.getSymbolTable() == null) {
            return warnings;
        }

        Map<String, Object> sym = snippet.getSymbolTable();
        Map<String, Object> dict = snippet.getTableDictionary();

        Map<String, Set<String>> sourceColumns = new HashMap<>();

        for (String key : sym.keySet()) {
            Object v = sym.get(key);
            if (!(v instanceof Map)) {
                continue; // skip alias entries mapping to strings
            }
            if (key.equals(MUMBLE_INTERFACE_KEY) || key.startsWith("def_")
               || key.startsWith(MUMBLE_PREDICAND_KEY) || key.startsWith(MUMBLE_EXISTS_KEY)
               || key.startsWith(MUMBLE_IN_LIST_KEY)) {
                continue;
            }

            if (key.startsWith("query") || key.startsWith("union") || key.startsWith("intersect") || key.startsWith("values")) {
                Map<String, Object> subq = (Map<String, Object>) v;
                Map<String, Object> iface = (Map<String, Object>) subq.get(MUMBLE_INTERFACE_KEY);
                Set<String> cols = (iface == null) ? java.util.Set.of() : iface.keySet();
                sourceColumns.put(key, cols);
            } else {
                String ref = key.startsWith("<") ? key : key.toLowerCase();
                Map<String, Object> tableCols = (Map<String, Object>) dict.get(ref);
                Set<String> cols = (tableCols == null) ? java.util.Set.of() : tableCols.keySet();
                sourceColumns.put(key, cols);
            }
        }

        java.util.function.Function<String, Integer> countMatches = (col) -> {
            int n = 0;
            for (Set<String> cols : sourceColumns.values()) {
                if (cols.contains(col)) {
                    n++;
                }
            }
            return n;
        };

        Map<String, Object> unknowns = (Map<String, Object>) sym.get(MUMBLE_UNKNOWN_KEY);
        if (unknowns != null && !unknowns.isEmpty()) {
            for (String col : unknowns.keySet()) {
                int n = countMatches.apply(col);
                if (n == 0) {
                    warnings.add("Unqualified column '" + col + "' not found in any source");
                } else if (n > 1) {
                    warnings.add("Ambiguous unqualified column '" + col + "' found in " + n + " sources");
                }
            }
        }

        // Interface coverage checks respecting alias semantics:
        // For each query-like source's interface, resolve the alias reference:
        // - If the interface entry references a column with a specific table_ref source, check that source has the column.
        // - If table_ref is null and the query has exactly one local source, check that single source has the column.
        // - Otherwise, if table_ref is null and multiple local sources exist, emit an ambiguity warning.
        for (String queryKey : sym.keySet()) {
            Object q = sym.get(queryKey);
            if (!(q instanceof Map)) {
                continue;
            }
            if (!(queryKey.startsWith("query") || queryKey.startsWith("union") || queryKey.startsWith("intersect") || queryKey.startsWith("values"))) {
                continue;
            }
            Map<String, Object> qmap = (Map<String, Object>) q;
            Map<String, Object> iface = (Map<String, Object>) qmap.get(MUMBLE_INTERFACE_KEY);
            if (iface == null || iface.isEmpty()) {
                continue;
            }
            // Build local sources for this query
            Map<String, Set<String>> localSources = new HashMap<>();
            for (String k : qmap.keySet()) {
                if (k.equals(MUMBLE_INTERFACE_KEY) || k.startsWith("def_")) {
                    continue;
                }
                Object vv = qmap.get(k);
                if (vv instanceof Map) {
                    Map<String, Object> tcols = (Map<String, Object>) vv;
                    localSources.put(k, tcols.keySet());
                }
            }
            int localCount = localSources.size();

            for (Map.Entry<String, Object> entry : iface.entrySet()) {
                String alias = entry.getKey();
                Object ref = entry.getValue();
                if (!(ref instanceof Map)) {
                    continue;
                }
                Map<String, Object> refMap = (Map<String, Object>) ref;
                Map<String, Object> col = (Map<String, Object>) refMap.get("column");
                if (col == null) {
                    // Not a plain column reference; skip (could be expression/subquery)
                    continue;
                }
                String colName = (String) col.get("name");
                Object tr = col.get("table_ref");
                String tableRef = (tr == null) ? null : tr.toString();

                if (tableRef != null) {
                    // Check specific source
                    Set<String> cols = localSources.getOrDefault(tableRef, java.util.Set.of());
                    if (!cols.contains(colName)) {
                        warnings.add("Interface alias '" + alias + "' references column '" + colName + "' not found in source '" + tableRef + "' of '" + queryKey + "'");
                    }
                } else {
                    // Unqualified: single local source -> check that one; multiple -> ambiguity
                    if (localCount == 1) {
                        String onlySrc = localSources.keySet().stream().findFirst().orElse(null);
                        Set<String> cols = (onlySrc == null) ? java.util.Set.of() : localSources.getOrDefault(onlySrc, java.util.Set.of());
                        if (!cols.contains(colName)) {
                            warnings.add("Interface alias '" + alias + "' references column '" + colName + "' not found in single source '" + onlySrc + "' of '" + queryKey + "'");
                        }
                    } else if (localCount > 1) {
                        int n = 0;
                        for (Set<String> cols : localSources.values()) {
                            if (cols.contains(colName)) {
                                n++;
                            }
                        }
                        if (n == 0) {
                            warnings.add("Interface alias '" + alias + "' references column '" + colName + "' not found in any source of '" + queryKey + "'");
                        } else if (n > 1) {
                            warnings.add("Ambiguous interface alias '" + alias + "' for column '" + colName + "' found in " + n + " sources of '" + queryKey + "'");
                        }
                    }
                }
            }
        }

        for (String source : sym.keySet()) {
            Object v = sym.get(source);
            if (!(v instanceof Map)) {
                continue;
            }
            if (source.equals(MUMBLE_INTERFACE_KEY) || source.startsWith("def_")) {
                continue;
            }

            Map<String, Object> entries = (Map<String, Object>) v;
            Set<String> available = sourceColumns.getOrDefault(source, java.util.Set.of());

            for (String col : entries.keySet()) {
                if (col.equals(MUMBLE_INTERFACE_KEY)) {
                    continue;
                }
                Object val = entries.get(col);
                if (!(val instanceof String)) {
                    continue;
                }
                if (!available.contains(col)) {
                    warnings.add("Column '" + col + "' under source '" + source + "' not present in declared columns");
                }
            }
        }

        return warnings;
    }

}
