package access;


import org.antlr.v4.runtime.CharStream;
import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CommonTokenStream;
import org.antlr.v4.runtime.tree.ParseTreeWalker;

import static mumble.SQLParserEndPoints.SQLPARSER_COLUMN_TREE_KEY;
import static mumble.SQLParserEndPoints.SQLPARSER_CONDITION_TREE_KEY;
import static mumble.SQLParserEndPoints.SQLPARSER_INSERT_TREE_KEY;
import static mumble.SQLParserEndPoints.SQLPARSER_IN_LIST_TREE_KEY;
import static mumble.SQLParserEndPoints.SQLPARSER_JOIN_EXTENSION_TREE_KEY;
import static mumble.SQLParserEndPoints.SQLPARSER_PREDICAND_TREE_KEY;
import static mumble.SQLParserEndPoints.SQLPARSER_QUERY_TREE_KEY;
import static mumble.SQLParserEndPoints.SQLPARSER_SQL_TREE_KEY;
import static mumble.SQLParserEndPoints.SQLPARSER_TUPLE_TREE_KEY;
import static mumble.SQLParserEndPoints.SQLPARSER_VALUES_TREE_KEY;
import sql.SQLSelectParserLexer;
import sql.SQLSelectParserParser;
import sql.walker.SqlParseEventWalker;


/*
 * SqlParserAccess.java
 * This class will allow command line and embedded, cross-language access to the SQL parser.
 * 
 * To USE this class, create an instance setting the flags for ambiguities, context, and sensitivity with the constructor method.
 *  SqlParserAccess(boolean showAmbiguities, boolean showFullContext, boolean showContextSensitivty) 
 * 
 * Then call the executeTheParse(String inputText, String endPointType) (from the parent class AbstractParserAccess)
 * method with the SQL query string and the type of parse you want to perform.
 * 
 * The END POINTS of the GRAMMAR define the end point type strings and can be "sql", "column_value", "predicand_value",
 * "in_list_predicate_value", "condition_value", "tuple_value", "values_statement_end", "query_value", or "join_extension_value".
 * 
 * Then retrieve the parser results Snippet object using the getSnippet() method. This will have all of the available
 * information extracted from the parse tree, including the SQL Abstract Syntax Tree, Symbol Table, Table Column Dictionary,
 * Substitution Variables, and the Query Interface, and any errors encountered during parsing.
 */
public class SqlParserAccess extends AbstractParserAccess {

    // This holds the parser generated by the Access class.
    // It is protected so that subclasses can access it directly.
    protected SQLSelectParserParser parser;

 
    // This is the event walker used to extract information from the parse tree.
    private SqlParseEventWalker extractor;

    // Flags to control the behavior of the parser regarding ambiguities, context, and sensitivity.
    public SqlParserAccess(boolean showAmbiguities, boolean showFullContext, boolean showContextSensitivty) {
        // Initialize the parser access with the provided flags.
        this.showAmbiguities = showAmbiguities;
        this.showFullContext = showFullContext;
        this.showContextSensitivty = showContextSensitivty;
    }

 	/**
	 * Builds a bespoke SQLSelectParserParser instance for the given SQL query string.
	 * Does not run the parser, but prepares it for parsing.
	 * 
	 * @param inputText The SQL query string to parse.
	 * @return An instance of SQLSelectParserParser ready to parse the provided query.
	 */
    @Override
	public  void buildParser(final String inputText) {

        try {
            // Create the nested CommonTokenStream from the input query string.
            CommonTokenStream tokens = getCommonTokenStream(inputText);

            // Create a parser for the SQL query using the generated SQLSelectParserParser.
            // The parser will use the tokens from the CommonTokenStream to parse the SQL query            
		    this.parser = new SQLSelectParserParser(tokens);
		
            // Add error listeners and collectors to the parser for error handling.
		    addErrorListenerToParser(this.parser);

		    addErrorCollectorToParser(this.parser);

            this.extractor = new SqlParseEventWalker();

        } catch (Exception e) {
            System.err.println("EXCEPTION when adding listener: " + e.getMessage());
            e.printStackTrace();
        }

	}

    @Override
    public SQLSelectParserParser getParser() {
        // Return the parser instance created by the buildParser method.
        return this.parser; 
    }

    // It is used to tokenize the input query and produce a stream of tokens that can be
    // submitted to the parser for parsing.
    @Override
    protected CommonTokenStream getCommonTokenStream(final String inputText) {
        // Create a CharStream from the input query string.
        CharStream qryStream = CharStreams.fromString(inputText);
        // Create a lexer for the SQL query using the generated SQLSelectParserLexer.
        // The lexer will tokenize the input query and produce a stream of tokens.           
        SQLSelectParserLexer lexer = new SQLSelectParserLexer(qryStream);
        // Create a CommonTokenStream from the lexer.
        // The CommonTokenStream will hold the tokens produced by the lexer and submit them to the parser in sequence. 
        CommonTokenStream tokens = new CommonTokenStream(lexer);
        return tokens;
    }

    // This method runs the parser on the input text and returns the parse tree.
    // It is called by the executeTheParse method in the parent class AbstractParserAccess.
    @Override
    public void runParser(String type) {
        // This method runs the parser on the input text and returns the parse tree.
        if (this.parser == null) {
            throw new IllegalStateException("Parser has not been built. Call buildParser() first.");
        } else if (type.equals(SQLPARSER_SQL_TREE_KEY)) {
            this.parserEmitPoint = parser.sql();
        } else if (type.equals(SQLPARSER_COLUMN_TREE_KEY)) {
            this.parserEmitPoint = parser.column_value();
        } else if (type.equals(SQLPARSER_PREDICAND_TREE_KEY)) {
            this.parserEmitPoint = parser.predicand_value();
        } else if (type.equals(SQLPARSER_IN_LIST_TREE_KEY)) {
            this.parserEmitPoint = parser.in_list_predicate_value();
        } else if (type.equals(SQLPARSER_CONDITION_TREE_KEY)) {
            this.parserEmitPoint = parser.condition_value();
        } else if (type.equals(SQLPARSER_TUPLE_TREE_KEY)) {
            this.parserEmitPoint = parser.tuple_value();
        } else if (type.equals(SQLPARSER_VALUES_TREE_KEY)) {
            this.parserEmitPoint = parser.values_statement_end();
        } else if (type.equals(SQLPARSER_QUERY_TREE_KEY)) {
            this.parserEmitPoint = parser.query_value();
        } else if (type.equals(SQLPARSER_JOIN_EXTENSION_TREE_KEY)) {
            this.parserEmitPoint = parser.join_extension_value();
        } else if (type.equals(SQLPARSER_INSERT_TREE_KEY)) {
            this.parserEmitPoint = parser.insert_end_point();
         } else {
            throw new IllegalArgumentException("Invalid Grammar End Point Type Requested: " + type);
        }
    }

    @Override
    public void generateAST() {
        // This method generates the Abstract Syntax Tree (AST) from the parse tree.
        // Walk the parse tree using the extractor.
        if (this.parserEmitPoint != null) {
            // Initialize the extractor if it is not already initialized.
            if (this.extractor == null)
                // Create a new instance of SqlParseEventWalker to extract the SQL from the parse tree
                this.extractor = new SqlParseEventWalker();
		
        String exceptionString = null;
        try{
 			// walk the tree and extract the SQL USING THE CUSTOM Extractor/Event Walker
            // The ParseTreeWalker.DEFAULT is used to walk the parse tree and call the appropriate methods in the extractor.
            // The extractor will collect the SQL Abstract Syntax Tree, Symbol Table, Table Column Dictionary, Substitution Variables, and Query Interface.
			ParseTreeWalker.DEFAULT.walk(this.extractor, this.parserEmitPoint);

        } catch (Exception e) {
            System.err.println("EXCEPTION when walking the parse tree: " + e.getMessage());
            this.addFatalError("Exception when walking the parse tree: " + e.getMessage());
            System.out.println("Exception: " + this.getFatalErrorList());
        }
            // Save the results in a local Snippet object
            this.snippet = new Snippet(
                this.extractor.getAsTree(),
                this.extractor.getTableColumnMap(),
                this.extractor.getSymbolTable(),
                this.extractor.getSubstitutionsMap(),
                this.extractor.getInterface()
            );
            // Add the error and other messages to the Snippet object
            snippet.setParserMessageList(this.getAllErrors());
            snippet.setParserMessageStringList(this.getAllErrorStrings());
            snippet.setFatalErrorStringList(this.getFatalErrorList());

       } else {
            throw new IllegalStateException("Parser tree is null. Ensure the parser was run successfully.");    
        }
    }

}
