package access;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.antlr.v4.runtime.CharStream;
import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CommonTokenStream;
import org.antlr.v4.runtime.tree.ParseTreeWalker;

import errorhandling.ParseDiagnostic;
import errorhandling.ParseErrorListener;
import static mumble.SQLParserEndPoints.SQLPARSER_COLUMN_TREE_KEY;
import static mumble.SQLParserEndPoints.SQLPARSER_CONDITION_TREE_KEY;
import static mumble.SQLParserEndPoints.SQLPARSER_DDL_TREE_KEY;
import static mumble.SQLParserEndPoints.SQLPARSER_DELETE_TREE_KEY;
import static mumble.SQLParserEndPoints.SQLPARSER_INSERT_TREE_KEY;
import static mumble.SQLParserEndPoints.SQLPARSER_IN_LIST_TREE_KEY;
import static mumble.SQLParserEndPoints.SQLPARSER_JOIN_EXTENSION_TREE_KEY;
import static mumble.SQLParserEndPoints.SQLPARSER_PREDICAND_TREE_KEY;
import static mumble.SQLParserEndPoints.SQLPARSER_QUERY_TREE_KEY;
import static mumble.SQLParserEndPoints.SQLPARSER_SCRIPT_TREE_KEY;
import static mumble.SQLParserEndPoints.SQLPARSER_SQL_TREE_KEY;
import static mumble.SQLParserEndPoints.SQLPARSER_TRUNCATE_TREE_KEY;
import static mumble.SQLParserEndPoints.SQLPARSER_TUPLE_TREE_KEY;
import static mumble.SQLParserEndPoints.SQLPARSER_UPDATE_TREE_KEY;
import static mumble.SQLParserEndPoints.SQLPARSER_VALUES_TREE_KEY;
import sql.SQLSelectParserLexer;
import sql.SQLSelectParserParser;
import sql.walker.ScriptParseAccumulator;
import sql.walker.SqlParseEventWalker;


/*
 * SqlParserAccess.java
 * This class will allow command line and embedded, cross-language access to the SQL parser.
 * 
 * To USE this class, create an instance setting the flags for ambiguities, context, and sensitivity with the constructor method.
 *  SqlParserAccess(boolean showAmbiguities, boolean showFullContext, boolean showContextSensitivty) 
 * 
 * Then call the executeTheParse(String inputText, String endPointType) (from the parent class AbstractParserAccess)
 * method with the SQL query string and the type of parse you want to perform.
 * 
 * The END POINTS of the GRAMMAR define the end point type strings and can be "sql", "column_value", "predicand_value",
 * "in_list_predicate_value", "condition_value", "tuple_value", "values_statement_end", "query_value", or "join_extension_value".
 * 
 * Then retrieve the parser results Snippet object using the getSnippet() method. This will have all of the available
 * information extracted from the parse tree, including the SQL Abstract Syntax Tree, Symbol Table, Table Column Dictionary,
 * Substitution Variables, and the Query Interface, and any errors encountered during parsing.
 */
public class SqlParserAccess extends AbstractParserAccess {

    // This holds the parser generated by the Access class.
    // It is protected so that subclasses can access it directly.
    protected SQLSelectParserParser parser;

 
    // This is the event walker used to extract information from the parse tree.
    private SqlParseEventWalker extractor;

    // Flags to control the behavior of the parser regarding ambiguities, context, and sensitivity.
    public SqlParserAccess(boolean showAmbiguities, boolean showFullContext, boolean showContextSensitivty) {
        // Initialize the parser access with the provided flags.
        this.showAmbiguities = showAmbiguities;
        this.showFullContext = showFullContext;
        this.showContextSensitivty = showContextSensitivty;
    }

 	/**
	 * Builds a bespoke SQLSelectParserParser instance for the given SQL query string.
	 * Does not run the parser, but prepares it for parsing.
	 * 
	 * @param inputText The SQL query string to parse.
	 * @return An instance of SQLSelectParserParser ready to parse the provided query.
	 */
    @Override
	public  void buildParser(final String inputText) {

        try {
            // Create the nested CommonTokenStream from the input query string.
            CommonTokenStream tokens = getCommonTokenStream(inputText);

            // Create a parser for the SQL query using the generated SQLSelectParserParser.
            // The parser will use the tokens from the CommonTokenStream to parse the SQL query            
		    this.parser = new SQLSelectParserParser(tokens);
		
            // Add error listeners and collectors to the parser for error handling.
		    addErrorListenerToParser(this.parser);

		    addErrorCollectorToParser(this.parser);

            this.extractor = new SqlParseEventWalker();

        } catch (Exception e) {
            System.err.println("EXCEPTION when adding listener: " + e.getMessage());
            // Log the full stack trace to standard error
            for (StackTraceElement element : e.getStackTrace()) {
                System.err.println("\tat " + element);
            }
        }

	}

    @Override
    public SQLSelectParserParser getParser() {
        // Return the parser instance created by the buildParser method.
        return this.parser; 
    }

    @Override
    public List<ParseDiagnostic> getAllDiagnostics() {
        List<ParseDiagnostic> diagnostics = new ArrayList<>(super.getAllDiagnostics());
        if (this.snippet != null && this.snippet.getParserDiagnosticList() != null) {
            for (ParseDiagnostic diagnostic : this.snippet.getParserDiagnosticList()) {
                if (diagnostic != null && !diagnostics.contains(diagnostic)) {
                    diagnostics.add(diagnostic);
                }
            }
        }
        return diagnostics;
    }

    // It is used to tokenize the input query and produce a stream of tokens that can be
    // submitted to the parser for parsing.
    @Override
    protected CommonTokenStream getCommonTokenStream(final String inputText) {
        // Create a CharStream from the input query string.
        CharStream qryStream = CharStreams.fromString(inputText);
        // Create a lexer for the SQL query using the generated SQLSelectParserLexer.
        // The lexer will tokenize the input query and produce a stream of tokens.           
        SQLSelectParserLexer lexer = new SQLSelectParserLexer(qryStream);
        // Create a CommonTokenStream from the lexer.
        // The CommonTokenStream will hold the tokens produced by the lexer and submit them to the parser in sequence. 
        CommonTokenStream tokens = new CommonTokenStream(lexer);
        return tokens;
    }

    // This method runs the parser on the input text and returns the parse tree.
    // It is called by the executeTheParse method in the parent class AbstractParserAccess.
    @Override
    public void runParser(String type) {
        // This method runs the parser on the input text and returns the parse tree.
        if (this.parser == null) {
            throw new IllegalStateException("Parser has not been built. Call buildParser() first.");
        } else if (type.equals(SQLPARSER_SQL_TREE_KEY)) {
            this.parserEmitPoint = parser.sql();
        } else if (type.equals(SQLPARSER_COLUMN_TREE_KEY)) {
            this.parserEmitPoint = parser.column_value();
        } else if (type.equals(SQLPARSER_PREDICAND_TREE_KEY)) {
            this.parserEmitPoint = parser.predicand_value();
        } else if (type.equals(SQLPARSER_IN_LIST_TREE_KEY)) {
            this.parserEmitPoint = parser.in_list_predicate_value();
        } else if (type.equals(SQLPARSER_CONDITION_TREE_KEY)) {
            this.parserEmitPoint = parser.condition_value();
        } else if (type.equals(SQLPARSER_TUPLE_TREE_KEY)) {
            this.parserEmitPoint = parser.tuple_value();
        } else if (type.equals(SQLPARSER_VALUES_TREE_KEY)) {
            this.parserEmitPoint = parser.values_statement_end();
        } else if (type.equals(SQLPARSER_QUERY_TREE_KEY)) {
            this.parserEmitPoint = parser.query_value();
        } else if (type.equals(SQLPARSER_DDL_TREE_KEY)) {
            this.parserEmitPoint = parser.ddl();
        } else if (type.equals(SQLPARSER_SCRIPT_TREE_KEY)) {
            this.parserEmitPoint = parser.script();
        } else if (type.equals(SQLPARSER_JOIN_EXTENSION_TREE_KEY)) {
            this.parserEmitPoint = parser.join_extension_value();
        } else if (type.equals(SQLPARSER_INSERT_TREE_KEY)) {
            this.parserEmitPoint = parser.insert_end_point();
        } else if (type.equals(SQLPARSER_UPDATE_TREE_KEY)) {
            this.parserEmitPoint = parser.update_end_point();
        } else if (type.equals(SQLPARSER_DELETE_TREE_KEY)) {
            this.parserEmitPoint = parser.delete_end_point();
        } else if (type.equals(SQLPARSER_TRUNCATE_TREE_KEY)) {
            this.parserEmitPoint = parser.truncate_end_point();
         } else {
            throw new IllegalArgumentException("Invalid Grammar End Point Type Requested: " + type);
        }
    }

    @Override
    public void generateAST() {
        // This method generates the Abstract Syntax Tree (AST) from the parse tree.
        // Walk the parse tree using the extractor.
    if (this.parserEmitPoint != null) {
        // Initialize the extractor if it is not already initialized.
        if (this.extractor == null)
            // Create a new instance of SqlParseEventWalker to extract the SQL from the parse tree
            this.extractor = new SqlParseEventWalker();
		
        try{
 			// walk the tree and extract the SQL USING THE CUSTOM Extractor/Event Walker
            // The ParseTreeWalker.DEFAULT is used to walk the parse tree and call the appropriate methods in the extractor.
            // The extractor will collect the SQL Abstract Syntax Tree, Symbol Table, Table Column Dictionary, Substitution Variables, and Query Interface.
			ParseTreeWalker.DEFAULT.walk(this.extractor, this.parserEmitPoint);

        } catch (Exception e) {
            System.err.println("EXCEPTION when walking the parse tree: " + e.getMessage());
            this.addFatalError("Exception when walking the parse tree: " + e.getMessage());
            System.out.println("Exception: " + this.getFatalErrorList());
        }
        // Save the results in a local Snippet object
        this.snippet = this.extractor.getSnippet();


        // Add the error and other messages to the Snippet object
        // Merge point: combine walker diagnostics (semantic) with parser diagnostics (syntax/recovery).
        List<ParseDiagnostic> mergedDiagnostics = new ArrayList<>();
        List<ParseDiagnostic> walkerDiagnostics = snippet.getParserDiagnosticList();
        if (walkerDiagnostics != null) {
            mergedDiagnostics.addAll(walkerDiagnostics);
        }
        List<ParseDiagnostic> parserDiagnostics = this.getAllDiagnostics();
        if (parserDiagnostics != null) {
            mergedDiagnostics.addAll(parserDiagnostics);
        }
        // Final handoff: persist unified diagnostics back onto the access-layer snippet.
        snippet.setParserDiagnosticList(mergedDiagnostics);
        snippet.setParserMessageList(mergedDiagnostics);
        snippet.setFatalErrorStringList(this.getFatalErrorList());

        HashMap<String, Object> enrichedArrayCollectors = enrichArrayOutputCollectorsForSnippet(snippet);
        if (enrichedArrayCollectors != null && !enrichedArrayCollectors.isEmpty()) {
            snippet.setArrayOutputCollectorsMap(enrichedArrayCollectors);
        }

        ScriptParseAccumulator scriptAccumulator = this.extractor.getScriptParseAccumulator();
        if (scriptAccumulator.hasLineRanges()) {
            List<ParseDiagnostic> prefixedMergedDiagnostics = scriptAccumulator.prefixWalkerDiagnostics(
                    mergedDiagnostics);
            snippet.setParserDiagnosticList(prefixedMergedDiagnostics);
            snippet.setParserMessageList(prefixedMergedDiagnostics);
        }

        } else {
            throw new IllegalStateException("Parser tree is null. Ensure the parser was run successfully.");    
        }
    }

    @SuppressWarnings("unchecked")
    private HashMap<String, Object> enrichArrayOutputCollectorsForSnippet(Snippet snippet) {
        if (snippet == null) {
            return null;
        }

        HashMap<String, Object> baseCollectors = snippet.getArrayOutputCollectorsMap();
        if (baseCollectors == null || baseCollectors.isEmpty()) {
            return baseCollectors;
        }

        Map<String, ScriptParseAccumulator.StatementLineRange> statementLineRanges = getScriptStatementLineRanges();
        HashMap<String, Object> enriched = new LinkedHashMap<>();

        for (Map.Entry<String, Object> topEntry : baseCollectors.entrySet()) {
            Object topValue = topEntry.getValue();
            if (!(topValue instanceof Map<?, ?> topValueMapObj)) {
                enriched.put(topEntry.getKey(), topValue);
                continue;
            }

            Map<String, Object> topMap = (Map<String, Object>) topValueMapObj;
            enriched.put(topEntry.getKey(), enrichCollectorContainer(topMap, snippet, statementLineRanges));
        }

        return enriched;
    }

    @SuppressWarnings("unchecked")
    private HashMap<String, Object> enrichCollectorContainer(
            Map<String, Object> container,
            Snippet snippet,
            Map<String, ScriptParseAccumulator.StatementLineRange> statementLineRanges) {
        if (container == null || container.isEmpty()) {
            return new LinkedHashMap<>();
        }

        boolean hasNumberedQueryChildren = false;
        for (Map.Entry<String, Object> entry : container.entrySet()) {
            if (entry.getKey() != null
                    && entry.getKey().matches("\\d+")
                    && entry.getValue() instanceof Map<?, ?>) {
                hasNumberedQueryChildren = true;
                break;
            }
        }

        HashMap<String, Object> result = new LinkedHashMap<>();
        if (hasNumberedQueryChildren) {
            for (Map.Entry<String, Object> entry : container.entrySet()) {
                String key = entry.getKey();
                Object value = entry.getValue();
                if (key != null && key.matches("\\d+") && value instanceof Map<?, ?> valueMapObj) {
                    ScriptParseAccumulator.StatementLineRange range = (statementLineRanges == null) ? null : statementLineRanges.get(key);
                    HashMap<String, Object> diagnosticsPayload = buildArrayCollectorDiagnosticsPayload(snippet, range);
                    HashMap<String, Object> queryEntry = new LinkedHashMap<>((Map<String, Object>) valueMapObj);
                    injectDiagnosticsIntoQueryEntry(queryEntry, diagnosticsPayload);
                    if (!queryEntry.isEmpty()) {
                        result.put(key, queryEntry);
                    }
                } else {
                    result.put(key, value);
                }
            }
            return result;
        }

            HashMap<String, Object> diagnosticsPayload = buildArrayCollectorDiagnosticsPayload(snippet, null);
        HashMap<String, Object> singleQueryEntry = new LinkedHashMap<>(container);
        injectDiagnosticsIntoQueryEntry(singleQueryEntry, diagnosticsPayload);
        return singleQueryEntry;
    }

            private HashMap<String, Object> buildArrayCollectorDiagnosticsPayload(
                Snippet snippet,
                ScriptParseAccumulator.StatementLineRange lineRange) {
        HashMap<String, Object> payload = new LinkedHashMap<>();
        if (snippet == null) {
            return payload;
        }

            List<ParseDiagnostic> mergedDiagnostics = snippet.getParserDiagnosticList();

            List<String> parserErrors = collectDiagnosticMessages(
                mergedDiagnostics,
                Set.of(ParseDiagnostic.Severity.FATAL, ParseDiagnostic.Severity.ERROR, ParseDiagnostic.Severity.SEVERE_WARNING),
                lineRange,
                true,
                false);
        putIfNonEmpty(payload, "ParserErrors", parserErrors);

            putIfNonEmpty(payload, "Walker Fatal Errors", collectDiagnosticMessages(
                mergedDiagnostics,
                Set.of(ParseDiagnostic.Severity.FATAL),
                lineRange,
                false,
                true));
            putIfNonEmpty(payload, "Walker Non Fatal Errors", collectDiagnosticMessages(
                mergedDiagnostics,
                Set.of(ParseDiagnostic.Severity.ERROR),
                lineRange,
                false,
                true));
            putIfNonEmpty(payload, "Walker Severe Warnings", collectDiagnosticMessages(
                mergedDiagnostics,
                Set.of(ParseDiagnostic.Severity.SEVERE_WARNING),
                lineRange,
                false,
                true));
            putIfNonEmpty(payload, "Walker Warnings", collectDiagnosticMessages(
                mergedDiagnostics,
                Set.of(ParseDiagnostic.Severity.WARNING),
                lineRange,
                false,
                true));
            putIfNonEmpty(payload, "Walker Info", collectDiagnosticMessages(
                mergedDiagnostics,
                Set.of(ParseDiagnostic.Severity.INFO),
                lineRange,
                false,
                true));

        List<ParseDiagnostic> listenerDiagnostics = new ArrayList<>();
        if (getParser() != null) {
            List<?> listeners = getParser().getErrorListeners();
            for (Object listener : listeners) {
                if (listener instanceof ParseErrorListener parseErrorListener
                        && parseErrorListener.getDiagnostics() != null
                        && !parseErrorListener.getDiagnostics().isEmpty()) {
                    listenerDiagnostics.addAll(parseErrorListener.getDiagnostics());
                }
            }
        }
        List<ParseDiagnostic> filteredListenerDiagnostics = filterDiagnosticsByLineRange(listenerDiagnostics, lineRange);
        putIfNonEmpty(payload, "errorhandling.ParseErrorListener found Diagnostics", filteredListenerDiagnostics);

        return payload;
    }

    private List<String> collectDiagnosticMessages(
            List<ParseDiagnostic> diagnostics,
            Set<ParseDiagnostic.Severity> severities,
            ScriptParseAccumulator.StatementLineRange lineRange,
            boolean parserOnly,
            boolean walkerOnly) {
        List<String> messages = new ArrayList<>();
        if (diagnostics == null || diagnostics.isEmpty()) {
            return messages;
        }

        for (ParseDiagnostic diagnostic : diagnostics) {
            if (diagnostic == null) {
                continue;
            }
            if (severities != null && !severities.isEmpty() && !severities.contains(diagnostic.severity())) {
                continue;
            }
            if (parserOnly && !isParserDiagnostic(diagnostic)) {
                continue;
            }
            if (walkerOnly && !isWalkerDiagnostic(diagnostic)) {
                continue;
            }
            if (!matchesLineRange(diagnostic, lineRange)) {
                continue;
            }
            String message = diagnostic.message();
            if (message != null && !message.isBlank() && !messages.contains(message)) {
                messages.add(message);
            }
        }

        return messages;
    }

    private List<ParseDiagnostic> filterDiagnosticsByLineRange(
            List<ParseDiagnostic> diagnostics,
            ScriptParseAccumulator.StatementLineRange lineRange) {
        List<ParseDiagnostic> filtered = new ArrayList<>();
        if (diagnostics == null || diagnostics.isEmpty()) {
            return filtered;
        }

        for (ParseDiagnostic diagnostic : diagnostics) {
            if (diagnostic != null && matchesLineRange(diagnostic, lineRange)) {
                filtered.add(diagnostic);
            }
        }

        return filtered;
    }

    private boolean matchesLineRange(ParseDiagnostic diagnostic, ScriptParseAccumulator.StatementLineRange lineRange) {
        if (diagnostic == null || lineRange == null) {
            return true;
        }
        Integer line = diagnostic.line();
        if (line == null || line <= 0) {
            return false;
        }
        return line >= lineRange.startLine() && line <= lineRange.endLine();
    }

    private boolean isParserDiagnostic(ParseDiagnostic diagnostic) {
        if (diagnostic == null) {
            return false;
        }
        String source = diagnostic.source();
        return "ParseErrorCollector".equals(source)
                || "ParseErrorListener".equals(source)
                || "SqlParserAccess".equals(source)
                || "SqlParseMCP".equals(source);
    }

    private boolean isWalkerDiagnostic(ParseDiagnostic diagnostic) {
        if (diagnostic == null) {
            return false;
        }
        String source = diagnostic.source();
        return source != null && source.contains("SqlASTWalker");
    }

    private Map<String, ScriptParseAccumulator.StatementLineRange> getScriptStatementLineRanges() {
        if (this.extractor == null) {
            return Map.of();
        }
        ScriptParseAccumulator scriptAccumulator = this.extractor.getScriptParseAccumulator();
        if (!scriptAccumulator.hasLineRanges()) {
            return Map.of();
        }
        return scriptAccumulator.snapshot().statementLineRanges();
    }

    private void injectDiagnosticsIntoQueryEntry(
            HashMap<String, Object> queryEntry,
            HashMap<String, Object> diagnosticsPayload) {
        if (queryEntry == null) {
            return;
        }

        if (isEmptyValue(queryEntry.get("queryInterface"))) {
            queryEntry.remove("queryInterface");
        }

        for (Map.Entry<String, Object> payloadEntry : diagnosticsPayload.entrySet()) {
            String payloadKey = payloadEntry.getKey();
            if (payloadKey == null || queryEntry.containsKey(payloadKey)) {
                continue;
            }
            Object value = payloadEntry.getValue();
            if (!isEmptyValue(value)) {
                queryEntry.put(payloadKey, value);
            }
        }

        queryEntry.entrySet().removeIf(entry -> isEmptyValue(entry.getValue()));
    }

    private void putIfNonEmpty(HashMap<String, Object> target, String key, Object value) {
        if (target == null || key == null || isEmptyValue(value)) {
            return;
        }
        target.put(key, value);
    }

    private boolean isEmptyValue(Object value) {
        if (value == null) {
            return true;
        }
        if (value instanceof String stringValue) {
            return stringValue.isBlank();
        }
        if (value instanceof List<?> listValue) {
            return listValue.isEmpty();
        }
        if (value instanceof Map<?, ?> mapValue) {
            return mapValue.isEmpty();
        }
        return false;
    }

}
