package cli;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.regex.Pattern;

import access.Snippet;
import access.SqlParserAccess;
import static mumble.SQLParserEndPoints.SQLPARSER_SQL_TREE_KEY;

/**
 * Generates Java assertion snippets for map-style subtree paths from a SQL query.
 */
public final class SymbolTreeAssertionGenerator {

    private SymbolTreeAssertionGenerator() {
    }

    private record PathEntry(String path, Object value) {
    }

    public static void main(String[] args) throws IOException {
        Options options = Options.parse(args);
        String sql = options.sqlText != null
                ? options.sqlText
                : Files.readString(Path.of(options.sqlFile), StandardCharsets.UTF_8);

        SqlParserAccess access = new SqlParserAccess(false, false, false);
        access.executeTheParse(sql, SQLPARSER_SQL_TREE_KEY);
        Snippet snippet = access.getSnippet();

        if (snippet == null) {
            System.err.println("No parser snippet produced. Check SQL and parser diagnostics.");
            System.exit(2);
            return;
        }

        Object rootObject = extractRootObject(snippet, options.root);
        if (rootObject == null) {
            System.err.println("Selected root '" + options.root + "' is null for this query.");
            System.exit(2);
            return;
        }

        List<PathEntry> entries = new ArrayList<>();
        collectPaths("", rootObject, entries, options.pathRegex);

        if (entries.isEmpty()) {
            System.err.println("No matching paths found for regex: " + options.pathRegex.pattern());
            System.exit(3);
        }

        emitAssertions(entries, options);
    }

    @SuppressWarnings("unchecked")
    private static Object extractRootObject(Snippet snippet, String root) {
        return switch (root) {
            case "symbolTable" -> snippet.getSymbolTable();
            case "tableDictionary" -> snippet.getTableDictionary();
            case "queryDictionary" -> snippet.getQueryColumnDictionaryMap();
            case "sqlTree" -> snippet.getSqlAbstractTree();
            case "substitutionsMap" -> snippet.getSubstitutionsMap();
            case "arrayOutputCollectors" -> snippet.getArrayOutputCollectorsMap();
            default -> null;
        };
    }

    private static void collectPaths(String pathPrefix, Object node, List<PathEntry> entries, Pattern pathRegex) {
        if (node instanceof Map<?, ?> rawMap) {
            for (Map.Entry<?, ?> entry : rawMap.entrySet()) {
                if (!(entry.getKey() instanceof String key)) {
                    continue;
                }
                Object value = entry.getValue();
                String nextPath = pathPrefix.isEmpty() ? key : pathPrefix + "." + key;
                if (pathRegex.matcher(nextPath).matches()) {
                    entries.add(new PathEntry(nextPath, value));
                }
                collectPaths(nextPath, value, entries, pathRegex);
            }
            return;
        }

        if (node instanceof List<?> list) {
            for (Object child : list) {
                collectPaths(pathPrefix, child, entries, pathRegex);
            }
        }
    }

    private static void emitAssertions(List<PathEntry> entries, Options options) {
        System.out.println("// Generated by cli.SymbolTreeAssertionGenerator");
        System.out.println("// root: " + options.root);
        System.out.println("// path regex: " + options.pathRegex.pattern());
        System.out.println("// subtree count: " + entries.size());

        int index = 0;
        for (PathEntry entry : entries) {
            String variableName = options.variablePrefix + toPascalCase(entry.path()) + "_" + index;
            String expected = String.valueOf(entry.value());
            System.out.println();
            System.out.println("final String " + variableName + " = " + toJavaStringLiteral(expected) + ";");
            System.out.println(options.assertionMethod
                    + "(extractor.getSymbolTable(), \""
                    + entry.path()
                    + "\", "
                    + variableName
                    + ");");
            index++;
        }
    }

    private static String toPascalCase(String text) {
        StringBuilder out = new StringBuilder();
        StringBuilder token = new StringBuilder();
        for (int i = 0; i < text.length(); i++) {
            char ch = text.charAt(i);
            if (Character.isLetterOrDigit(ch)) {
                token.append(ch);
            } else if (token.length() > 0) {
                appendCapitalized(out, token.toString());
                token.setLength(0);
            }
        }
        if (token.length() > 0) {
            appendCapitalized(out, token.toString());
        }
        if (out.length() == 0) {
            return "SymbolPath";
        }
        return out.toString();
    }

    private static void appendCapitalized(StringBuilder out, String token) {
        if (token.isEmpty()) {
            return;
        }
        out.append(Character.toUpperCase(token.charAt(0)));
        if (token.length() > 1) {
            out.append(token.substring(1));
        }
    }

    private static String toJavaStringLiteral(String value) {
        String escaped = value
                .replace("\\", "\\\\")
                .replace("\"", "\\\"")
                .replace("\n", "\\n")
                .replace("\r", "\\r");
        return "\"" + escaped + "\"";
    }

    private static final class Options {
        private final String sqlText;
        private final String sqlFile;
        private final String assertionMethod;
        private final String variablePrefix;
        private final String root;
        private final Pattern pathRegex;

        private Options(
                String sqlText,
                String sqlFile,
                String assertionMethod,
                String variablePrefix,
                String root,
                Pattern pathRegex) {
            this.sqlText = sqlText;
            this.sqlFile = sqlFile;
            this.assertionMethod = assertionMethod;
            this.variablePrefix = variablePrefix;
            this.root = root;
            this.pathRegex = pathRegex;
        }

        private static Options parse(String[] args) {
            String sqlText = null;
            String sqlFile = null;
            String assertionMethod = "assertSymbolTreePathEquals";
            String variablePrefix = "expected";
            String root = "symbolTable";
            Pattern pathRegex = Pattern.compile(".*");

            for (int i = 0; i < args.length; i++) {
                String arg = args[i];
                if ("--sql".equals(arg) && i + 1 < args.length) {
                    sqlText = args[++i];
                } else if ("--sql-file".equals(arg) && i + 1 < args.length) {
                    sqlFile = args[++i];
                } else if ("--assertion-method".equals(arg) && i + 1 < args.length) {
                    assertionMethod = args[++i];
                } else if ("--variable-prefix".equals(arg) && i + 1 < args.length) {
                    variablePrefix = args[++i];
                } else if ("--root".equals(arg) && i + 1 < args.length) {
                    root = args[++i];
                } else if ("--path-regex".equals(arg) && i + 1 < args.length) {
                    pathRegex = Pattern.compile(args[++i]);
                } else if ("--help".equals(arg) || "-h".equals(arg)) {
                    printUsageAndExit(0);
                } else {
                    System.err.println("Unknown or incomplete option: " + arg);
                    printUsageAndExit(1);
                }
            }

            if ((sqlText == null || sqlText.isBlank()) && (sqlFile == null || sqlFile.isBlank())) {
                System.err.println("Provide one of --sql or --sql-file.");
                printUsageAndExit(1);
            }

            if (!isSupportedRoot(root)) {
                System.err.println("Unsupported --root value: " + root);
                printUsageAndExit(1);
            }

            return new Options(sqlText, sqlFile, assertionMethod, variablePrefix, root, pathRegex);
        }

        private static boolean isSupportedRoot(String root) {
            return "symbolTable".equals(root)
                    || "tableDictionary".equals(root)
                    || "queryDictionary".equals(root)
                    || "sqlTree".equals(root)
                    || "substitutionsMap".equals(root)
                    || "arrayOutputCollectors".equals(root);
        }

        private static void printUsageAndExit(int code) {
            System.out.println("Usage:");
            System.out.println("  java ... cli.SymbolTreeAssertionGenerator --sql-file <path>");
            System.out.println("  java ... cli.SymbolTreeAssertionGenerator --sql <sqlText>");
            System.out.println("Options:");
            System.out.println("  --assertion-method <name>   default: assertSymbolTreePathEquals");
            System.out.println("  --variable-prefix <prefix>  default: expected");
            System.out.println("  --root <name>               default: symbolTable");
            System.out.println("                               one of: symbolTable, tableDictionary, queryDictionary,");
            System.out.println("                                       sqlTree, substitutionsMap, arrayOutputCollectors");
            System.out.println("  --path-regex <regex>        default: .* (matches full dotted path)");
            System.exit(code);
        }
    }
}
