
package sql.walker;

import errorhandling.ParseDiagnostic;
import org.junit.Test;
import sql.SQLSelectParserParser;

/** Temporary probe — regenerated by tools/generate_dml_substitution_tests.py */
public class DmlSubstitutionGoldenProbe extends AbstractSqlParseEventWalkerTest {
@Test
            public void probeinsertComplexSubstitutionI1WithCteGroupByHaving() {
                runProbe("insertComplexSubstitutionI1WithCteGroupByHaving", "WITH staged AS ("
					+ "\n  SELECT a.emp_id, sum(a.<insert select col I1>) AS total_score"
					+ "\n  FROM <[HR Data].[Employee Accounts I1]> a"
					+ "\n  WHERE a.<insert where col I1> > 0"
					+ "\n  GROUP BY a.emp_id, a.<insert group col I1>"
					+ "\n  HAVING sum(a.<insert select col I1>) > 0)"
					+ "\nINSERT INTO employees (agg_score, rank_bucket)"
					+ "\nSELECT s.total_score, s.emp_id"
					+ "\nFROM staged s"
					+ "\nWHERE s.total_score > 0");
            }

@Test
            public void probeinsertComplexSubstitutionI2SubqueryUnionWhereSubstitutions() {
                runProbe("insertComplexSubstitutionI2SubqueryUnionWhereSubstitutions", "INSERT INTO employees (score, rank_bucket)"
					+ "\nSELECT u.emp_id, u.metric_val"
					+ "\nFROM ("
					+ "\n  SELECT a.emp_id, a.<insert select col I2> AS metric_val"
					+ "\n  FROM <[Sales Data].[Perf Feed I2]> a"
					+ "\n  WHERE a.<insert where col I2> > 0"
					+ "\n  UNION"
					+ "\n  SELECT b.dept_id, b.<insert select col I2b> AS metric_val"
					+ "\n  FROM <[Sales Data].[Quota Feed I2]> b"
					+ "\n  WHERE b.<insert where col I2b> > 0"
					+ "\n) u"
					+ "\nWHERE u.metric_val > 0");
            }

@Test
            public void probeinsertComplexSubstitutionI3WithCteIntersectOrderBySubstitution() {
                runProbe("insertComplexSubstitutionI3WithCteIntersectOrderBySubstitution", "WITH branch_a AS ("
					+ "\n  SELECT a.emp_id, a.<insert select col I3> AS score_val"
					+ "\n  FROM <[Ops Data].[Account Ledger I3]> a"
					+ "\n  WHERE a.<insert where col I3> > 0"
					+ "\n  ORDER BY a.<insert order col I3>"
					+ "\n), branch_b AS ("
					+ "\n  SELECT b.emp_id, b.<insert select col I3> AS score_val"
					+ "\n  FROM <[Ops Data].[Audit Ledger I3]> b"
					+ "\n  WHERE b.<insert where col I3> > 0"
					+ "\n  ORDER BY b.<insert order col I3>"
					+ "\n), base AS ("
					+ "\n  SELECT * FROM branch_a"
					+ "\n  INTERSECT"
					+ "\n  SELECT * FROM branch_b"
					+ "\n)"
					+ "\nINSERT INTO employees (top_score, rank_bucket)"
					+ "\nSELECT b.score_val, b.emp_id"
					+ "\nFROM base b");
            }

@Test
            public void probeinsertComplexSubstitutionI4NestedWithInCteBody() {
                runProbe("insertComplexSubstitutionI4NestedWithInCteBody", "WITH outer_cte AS ("
					+ "\n  WITH inner_cte AS ("
					+ "\n    SELECT a.emp_id, a.<insert select col I4> AS metric_val"
					+ "\n    FROM <[Finance].[Revenue Feed I4]> a"
					+ "\n    WHERE a.<insert where col I4> > 0"
					+ "\n  )"
					+ "\n  SELECT i.emp_id, i.metric_val"
					+ "\n  FROM inner_cte i"
					+ "\n  WHERE i.metric_val > 0"
					+ "\n)"
					+ "\nINSERT INTO employees (score, rank_bucket)"
					+ "\nSELECT o.metric_val, o.emp_id"
					+ "\nFROM outer_cte o");
            }

@Test
            public void probeinsertComplexSubstitutionI5WithCteQualifyWindowSubstitution() {
                runProbe("insertComplexSubstitutionI5WithCteQualifyWindowSubstitution", "WITH ranked AS ("
					+ "\n  SELECT a.emp_id, a.<insert select col I5> AS score_val,"
					+ "\n         row_number() OVER (PARTITION BY a.emp_id ORDER BY a.<insert order col I5> DESC) AS rn"
					+ "\n  FROM <[Metrics].[Score Feed I5]> a"
					+ "\n  WHERE a.<insert where col I5> > 0"
					+ "\n  QUALIFY rn = 1"
					+ "\n)"
					+ "\nINSERT INTO employees (top_score, rank_bucket)"
					+ "\nSELECT r.score_val, r.emp_id"
					+ "\nFROM ranked r");
            }

@Test
            public void probeinsertComplexSubstitutionI6SubqueryJoinOnColumnSubstitution() {
                runProbe("insertComplexSubstitutionI6SubqueryJoinOnColumnSubstitution", "INSERT INTO employees (score, rank_bucket)"
					+ "\nSELECT j.metric_val, j.emp_id"
					+ "\nFROM ("
					+ "\n  SELECT a.emp_id, a.<insert select col I6> AS metric_val"
					+ "\n  FROM <[Join Data].[Left Feed I6]> a"
					+ "\n  JOIN <[Join Data].[Right Feed I6]> b"
					+ "\n    ON a.<insert join col I6> = b.<insert join col I6b>"
					+ "\n  WHERE a.<insert where col I6> > 0"
					+ "\n) j");
            }

@Test
            public void probeinsertComplexSubstitutionI7ChainedCteReferences() {
                runProbe("insertComplexSubstitutionI7ChainedCteReferences", "WITH step1 AS ("
					+ "\n  SELECT a.emp_id, a.<insert select col I7> AS raw_val"
					+ "\n  FROM <[Pipeline].[Stage One I7]> a"
					+ "\n  WHERE a.<insert where col I7> > 0"
					+ "\n), step2 AS ("
					+ "\n  SELECT s.emp_id, s.raw_val"
					+ "\n  FROM step1 s"
					+ "\n  WHERE s.raw_val > 0"
					+ "\n)"
					+ "\nINSERT INTO employees (score, rank_bucket)"
					+ "\nSELECT t.raw_val, t.emp_id"
					+ "\nFROM step2 t");
            }

@Test
            public void probeinsertComplexSubstitutionI8UnionIntersectNestedSubquery() {
                runProbe("insertComplexSubstitutionI8UnionIntersectNestedSubquery", "INSERT INTO employees (score, rank_bucket)"
					+ "\nSELECT x.metric_val, x.emp_id"
					+ "\nFROM ("
					+ "\n  SELECT u.emp_id, u.metric_val"
					+ "\n  FROM ("
					+ "\n    SELECT a.emp_id, a.<insert select col I8> AS metric_val"
					+ "\n    FROM <[Blend Data].[Branch A I8]> a"
					+ "\n    WHERE a.<insert where col I8> > 0"
					+ "\n    UNION"
					+ "\n    SELECT b.emp_id, b.<insert select col I8> AS metric_val"
					+ "\n    FROM <[Blend Data].[Branch B I8]> b"
					+ "\n    WHERE b.<insert where col I8> > 0"
					+ "\n  ) u"
					+ "\n  INTERSECT"
					+ "\n  SELECT c.emp_id, c.<insert select col I8> AS metric_val"
					+ "\n  FROM <[Blend Data].[Branch C I8]> c"
					+ "\n  WHERE c.<insert where col I8> > 0"
					+ "\n) x");
            }

@Test
            public void probeinsertComplexSubstitutionI9WithCteSelfUnionBranches() {
                runProbe("insertComplexSubstitutionI9WithCteSelfUnionBranches", "WITH blended AS ("
					+ "\n  SELECT a.emp_id, a.<insert select col I9a> AS metric_val"
					+ "\n  FROM <[Union Data].[Feed Alpha I9]> a"
					+ "\n  WHERE a.<insert where col I9a> > 0"
					+ "\n  UNION"
					+ "\n  SELECT b.emp_id, b.<insert select col I9b> AS metric_val"
					+ "\n  FROM <[Union Data].[Feed Beta I9]> b"
					+ "\n  WHERE b.<insert where col I9b> > 0"
					+ "\n)"
					+ "\nINSERT INTO employees (score, rank_bucket)"
					+ "\nSELECT bl.metric_val, bl.emp_id"
					+ "\nFROM blended bl"
					+ "\nWHERE bl.metric_val > 0");
            }

@Test
            public void probeinsertComplexSubstitutionI10SubqueryGroupByHavingQualifyCombined() {
                runProbe("insertComplexSubstitutionI10SubqueryGroupByHavingQualifyCombined", "INSERT INTO employees (agg_score, rank_bucket)"
					+ "\nSELECT src.total_score, src.emp_id"
					+ "\nFROM ("
					+ "\n  SELECT a.emp_id, sum(a.<insert select col I10>) AS total_score,"
					+ "\n         row_number() OVER (PARTITION BY a.emp_id ORDER BY a.<insert order col I10> DESC) AS rn"
					+ "\n  FROM <[Agg Data].[Fact Table I10]> a"
					+ "\n  WHERE a.<insert where col I10> > 0"
					+ "\n  GROUP BY a.emp_id, a.<insert group col I10>"
					+ "\n  HAVING sum(a.<insert select col I10>) > 0"
					+ "\n  QUALIFY rn = 1"
					+ "\n) src");
            }

@Test
            public void probeupdateComplexSubstitutionU1WithCteGroupByHaving() {
                runProbe("updateComplexSubstitutionU1WithCteGroupByHaving", "WITH staged AS ("
					+ "\n  SELECT a.emp_id, sum(a.<update select col U1>) AS total_score"
					+ "\n  FROM <[HR Data].[Employee Accounts U1]> a"
					+ "\n  WHERE a.<update where col U1> > 0"
					+ "\n  GROUP BY a.emp_id, a.<update group col U1>"
					+ "\n  HAVING sum(a.<update select col U1>) > 0)"
					+ "\nUPDATE employees e"
					+ "\nSET score = s.total_score"
					+ "\nFROM staged s"
					+ "\nWHERE e.emp_id = s.emp_id AND s.total_score > 0");
            }

@Test
            public void probeupdateComplexSubstitutionU2SubqueryUnionWhereSubstitutions() {
                runProbe("updateComplexSubstitutionU2SubqueryUnionWhereSubstitutions", "UPDATE employees e"
					+ "\nSET score = src.metric_val, rank_bucket = src.emp_id"
					+ "\nFROM ("
					+ "\n  SELECT a.emp_id, a.<update select col U2> AS metric_val"
					+ "\n  FROM <[Sales Data].[Perf Feed U2]> a"
					+ "\n  WHERE a.<update where col U2> > 0"
					+ "\n  UNION"
					+ "\n  SELECT b.dept_id, b.<update select col U2b> AS metric_val"
					+ "\n  FROM <[Sales Data].[Quota Feed U2]> b"
					+ "\n  WHERE b.<update where col U2b> > 0"
					+ "\n) src"
					+ "\nWHERE e.emp_id = src.emp_id");
            }

@Test
            public void probeupdateComplexSubstitutionU3WithCteIntersectOrderBySubstitution() {
                runProbe("updateComplexSubstitutionU3WithCteIntersectOrderBySubstitution", "WITH base AS ("
					+ "\n  SELECT a.emp_id, a.<update select col U3> AS score_val"
					+ "\n  FROM <[Ops Data].[Account Ledger U3]> a"
					+ "\n  WHERE a.<update where col U3> > 0"
					+ "\n  INTERSECT"
					+ "\n  SELECT b.emp_id, b.<update select col U3> AS score_val"
					+ "\n  FROM <[Ops Data].[Audit Ledger U3]> b"
					+ "\n  WHERE b.<update where col U3> > 0"
					+ "\n)"
					+ "\nUPDATE employees e"
					+ "\nSET score = b.score_val"
					+ "\nFROM base b"
					+ "\nWHERE e.emp_id = b.emp_id");
            }

@Test
            public void probeupdateComplexSubstitutionU4NestedWithInCteBody() {
                runProbe("updateComplexSubstitutionU4NestedWithInCteBody", "WITH outer_cte AS ("
					+ "\n  WITH inner_cte AS ("
					+ "\n    SELECT a.emp_id, a.<update select col U4> AS metric_val"
					+ "\n    FROM <[Finance].[Revenue Feed U4]> a"
					+ "\n    WHERE a.<update where col U4> > 0"
					+ "\n  )"
					+ "\n  SELECT i.emp_id, i.metric_val"
					+ "\n  FROM inner_cte i"
					+ "\n)"
					+ "\nUPDATE employees e"
					+ "\nSET score = o.metric_val"
					+ "\nFROM outer_cte o"
					+ "\nWHERE e.emp_id = o.emp_id");
            }

@Test
            public void probeupdateComplexSubstitutionU5WithCteQualifyWindowSubstitution() {
                runProbe("updateComplexSubstitutionU5WithCteQualifyWindowSubstitution", "WITH ranked AS ("
					+ "\n  SELECT a.emp_id, a.<update select col U5> AS score_val,"
					+ "\n         row_number() OVER (PARTITION BY a.emp_id ORDER BY a.<update order col U5> DESC) AS rn"
					+ "\n  FROM <[Metrics].[Score Feed U5]> a"
					+ "\n  WHERE a.<update where col U5> > 0"
					+ "\n  QUALIFY rn = 1"
					+ "\n)"
					+ "\nUPDATE employees e"
					+ "\nSET score = r.score_val"
					+ "\nFROM ranked r"
					+ "\nWHERE e.emp_id = r.emp_id");
            }

@Test
            public void probeupdateComplexSubstitutionU6SubqueryJoinOnColumnSubstitution() {
                runProbe("updateComplexSubstitutionU6SubqueryJoinOnColumnSubstitution", "UPDATE employees e"
					+ "\nSET score = j.metric_val"
					+ "\nFROM ("
					+ "\n  SELECT a.emp_id, a.<update select col U6> AS metric_val"
					+ "\n  FROM <[Join Data].[Left Feed U6]> a"
					+ "\n  JOIN <[Join Data].[Right Feed U6]> b"
					+ "\n    ON a.<update join col U6> = b.<update join col U6b>"
					+ "\n  WHERE a.<update where col U6> > 0"
					+ "\n) j"
					+ "\nWHERE e.emp_id = j.emp_id");
            }

@Test
            public void probeupdateComplexSubstitutionU7ChainedCteReferences() {
                runProbe("updateComplexSubstitutionU7ChainedCteReferences", "WITH step1 AS ("
					+ "\n  SELECT a.emp_id, a.<update select col U7> AS raw_val"
					+ "\n  FROM <[Pipeline].[Stage One U7]> a"
					+ "\n  WHERE a.<update where col U7> > 0"
					+ "\n), step2 AS ("
					+ "\n  SELECT s.emp_id, s.raw_val"
					+ "\n  FROM step1 s"
					+ "\n)"
					+ "\nUPDATE employees e"
					+ "\nSET score = t.raw_val"
					+ "\nFROM step2 t"
					+ "\nWHERE e.emp_id = t.emp_id");
            }

@Test
            public void probeupdateComplexSubstitutionU8UnionIntersectNestedSubquery() {
                runProbe("updateComplexSubstitutionU8UnionIntersectNestedSubquery", "UPDATE employees e"
					+ "\nSET score = x.metric_val"
					+ "\nFROM ("
					+ "\n  SELECT u.emp_id, u.metric_val"
					+ "\n  FROM ("
					+ "\n    SELECT a.emp_id, a.<update select col U8> AS metric_val"
					+ "\n    FROM <[Blend Data].[Branch A U8]> a"
					+ "\n    WHERE a.<update where col U8> > 0"
					+ "\n    UNION"
					+ "\n    SELECT b.emp_id, b.<update select col U8> AS metric_val"
					+ "\n    FROM <[Blend Data].[Branch B U8]> b"
					+ "\n    WHERE b.<update where col U8> > 0"
					+ "\n  ) u"
					+ "\n  INTERSECT"
					+ "\n  SELECT c.emp_id, c.<update select col U8> AS metric_val"
					+ "\n  FROM <[Blend Data].[Branch C U8]> c"
					+ "\n  WHERE c.<update where col U8> > 0"
					+ "\n) x"
					+ "\nWHERE e.emp_id = x.emp_id");
            }

@Test
            public void probeupdateComplexSubstitutionU9WithCteSelfUnionBranches() {
                runProbe("updateComplexSubstitutionU9WithCteSelfUnionBranches", "WITH blended AS ("
					+ "\n  SELECT a.emp_id, a.<update select col U9a> AS metric_val"
					+ "\n  FROM <[Union Data].[Feed Alpha U9]> a"
					+ "\n  WHERE a.<update where col U9a> > 0"
					+ "\n  UNION"
					+ "\n  SELECT b.emp_id, b.<update select col U9b> AS metric_val"
					+ "\n  FROM <[Union Data].[Feed Beta U9]> b"
					+ "\n  WHERE b.<update where col U9b> > 0"
					+ "\n)"
					+ "\nUPDATE employees e"
					+ "\nSET score = bl.metric_val"
					+ "\nFROM blended bl"
					+ "\nWHERE e.emp_id = bl.emp_id");
            }

@Test
            public void probeupdateComplexSubstitutionU10SubqueryGroupByHavingQualifyCombined() {
                runProbe("updateComplexSubstitutionU10SubqueryGroupByHavingQualifyCombined", "UPDATE employees e"
					+ "\nSET score = src.total_score"
					+ "\nFROM ("
					+ "\n  SELECT a.emp_id, sum(a.<update select col U10>) AS total_score,"
					+ "\n         row_number() OVER (PARTITION BY a.emp_id ORDER BY a.<update order col U10> DESC) AS rn"
					+ "\n  FROM <[Agg Data].[Fact Table U10]> a"
					+ "\n  WHERE a.<update where col U10> > 0"
					+ "\n  GROUP BY a.emp_id, a.<update group col U10>"
					+ "\n  HAVING sum(a.<update select col U10>) > 0"
					+ "\n  QUALIFY rn = 1"
					+ "\n) src"
					+ "\nWHERE e.emp_id = src.emp_id");
            }

@Test
            public void probedeleteComplexSubstitutionD1WithCteGroupByHaving() {
                runProbe("deleteComplexSubstitutionD1WithCteGroupByHaving", "WITH staged AS ("
					+ "\n  SELECT a.emp_id, sum(a.<delete select col D1>) AS total_score"
					+ "\n  FROM <[HR Data].[Employee Accounts D1]> a"
					+ "\n  WHERE a.<delete where col D1> > 0"
					+ "\n  GROUP BY a.emp_id, a.<delete group col D1>"
					+ "\n  HAVING sum(a.<delete select col D1>) > 0)"
					+ "\nDELETE FROM employees e"
					+ "\nUSING staged s"
					+ "\nWHERE e.emp_id = s.emp_id AND s.total_score > 0");
            }

@Test
            public void probedeleteComplexSubstitutionD2SubqueryUnionWhereSubstitutions() {
                runProbe("deleteComplexSubstitutionD2SubqueryUnionWhereSubstitutions", "DELETE FROM employees e"
					+ "\nUSING ("
					+ "\n  SELECT a.emp_id, a.<delete select col D2> AS metric_val"
					+ "\n  FROM <[Sales Data].[Perf Feed D2]> a"
					+ "\n  WHERE a.<delete where col D2> > 0"
					+ "\n  UNION"
					+ "\n  SELECT b.dept_id, b.<delete select col D2b> AS metric_val"
					+ "\n  FROM <[Sales Data].[Quota Feed D2]> b"
					+ "\n  WHERE b.<delete where col D2b> > 0"
					+ "\n) src"
					+ "\nWHERE e.emp_id = src.emp_id");
            }

@Test
            public void probedeleteComplexSubstitutionD3WithCteIntersectOrderBySubstitution() {
                runProbe("deleteComplexSubstitutionD3WithCteIntersectOrderBySubstitution", "WITH base AS ("
					+ "\n  SELECT a.emp_id, a.<delete select col D3> AS score_val"
					+ "\n  FROM <[Ops Data].[Account Ledger D3]> a"
					+ "\n  WHERE a.<delete where col D3> > 0"
					+ "\n  INTERSECT"
					+ "\n  SELECT b.emp_id, b.<delete select col D3> AS score_val"
					+ "\n  FROM <[Ops Data].[Audit Ledger D3]> b"
					+ "\n  WHERE b.<delete where col D3> > 0"
					+ "\n)"
					+ "\nDELETE FROM employees e"
					+ "\nUSING base b"
					+ "\nWHERE e.emp_id = b.emp_id");
            }

@Test
            public void probedeleteComplexSubstitutionD4NestedWithInCteBody() {
                runProbe("deleteComplexSubstitutionD4NestedWithInCteBody", "WITH outer_cte AS ("
					+ "\n  WITH inner_cte AS ("
					+ "\n    SELECT a.emp_id, a.<delete select col D4> AS metric_val"
					+ "\n    FROM <[Finance].[Revenue Feed D4]> a"
					+ "\n    WHERE a.<delete where col D4> > 0"
					+ "\n  )"
					+ "\n  SELECT i.emp_id, i.metric_val"
					+ "\n  FROM inner_cte i"
					+ "\n)"
					+ "\nDELETE FROM employees e"
					+ "\nUSING outer_cte o"
					+ "\nWHERE e.emp_id = o.emp_id");
            }

@Test
            public void probedeleteComplexSubstitutionD5WithCteQualifyWindowSubstitution() {
                runProbe("deleteComplexSubstitutionD5WithCteQualifyWindowSubstitution", "WITH ranked AS ("
					+ "\n  SELECT a.emp_id, a.<delete select col D5> AS score_val,"
					+ "\n         row_number() OVER (PARTITION BY a.emp_id ORDER BY a.<delete order col D5> DESC) AS rn"
					+ "\n  FROM <[Metrics].[Score Feed D5]> a"
					+ "\n  WHERE a.<delete where col D5> > 0"
					+ "\n  QUALIFY rn = 1"
					+ "\n)"
					+ "\nDELETE FROM employees e"
					+ "\nUSING ranked r"
					+ "\nWHERE e.emp_id = r.emp_id");
            }

@Test
            public void probedeleteComplexSubstitutionD6SubqueryJoinOnColumnSubstitution() {
                runProbe("deleteComplexSubstitutionD6SubqueryJoinOnColumnSubstitution", "DELETE FROM employees e"
					+ "\nUSING ("
					+ "\n  SELECT a.emp_id, a.<delete select col D6> AS metric_val"
					+ "\n  FROM <[Join Data].[Left Feed D6]> a"
					+ "\n  JOIN <[Join Data].[Right Feed D6]> b"
					+ "\n    ON a.<delete join col D6> = b.<delete join col D6b>"
					+ "\n  WHERE a.<delete where col D6> > 0"
					+ "\n) j"
					+ "\nWHERE e.emp_id = j.emp_id");
            }

@Test
            public void probedeleteComplexSubstitutionD7ChainedCteReferences() {
                runProbe("deleteComplexSubstitutionD7ChainedCteReferences", "WITH step1 AS ("
					+ "\n  SELECT a.emp_id, a.<delete select col D7> AS raw_val"
					+ "\n  FROM <[Pipeline].[Stage One D7]> a"
					+ "\n  WHERE a.<delete where col D7> > 0"
					+ "\n), step2 AS ("
					+ "\n  SELECT s.emp_id, s.raw_val"
					+ "\n  FROM step1 s"
					+ "\n)"
					+ "\nDELETE FROM employees e"
					+ "\nUSING step2 t"
					+ "\nWHERE e.emp_id = t.emp_id");
            }

@Test
            public void probedeleteComplexSubstitutionD8UnionIntersectNestedSubquery() {
                runProbe("deleteComplexSubstitutionD8UnionIntersectNestedSubquery", "DELETE FROM employees e"
					+ "\nUSING ("
					+ "\n  SELECT u.emp_id, u.metric_val"
					+ "\n  FROM ("
					+ "\n    SELECT a.emp_id, a.<delete select col D8> AS metric_val"
					+ "\n    FROM <[Blend Data].[Branch A D8]> a"
					+ "\n    WHERE a.<delete where col D8> > 0"
					+ "\n    UNION"
					+ "\n    SELECT b.emp_id, b.<delete select col D8> AS metric_val"
					+ "\n    FROM <[Blend Data].[Branch B D8]> b"
					+ "\n    WHERE b.<delete where col D8> > 0"
					+ "\n  ) u"
					+ "\n  INTERSECT"
					+ "\n  SELECT c.emp_id, c.<delete select col D8> AS metric_val"
					+ "\n  FROM <[Blend Data].[Branch C D8]> c"
					+ "\n  WHERE c.<delete where col D8> > 0"
					+ "\n) x"
					+ "\nWHERE e.emp_id = x.emp_id");
            }

@Test
            public void probedeleteComplexSubstitutionD9WithCteSelfUnionBranches() {
                runProbe("deleteComplexSubstitutionD9WithCteSelfUnionBranches", "WITH blended AS ("
					+ "\n  SELECT a.emp_id, a.<delete select col D9a> AS metric_val"
					+ "\n  FROM <[Union Data].[Feed Alpha D9]> a"
					+ "\n  WHERE a.<delete where col D9a> > 0"
					+ "\n  UNION"
					+ "\n  SELECT b.emp_id, b.<delete select col D9b> AS metric_val"
					+ "\n  FROM <[Union Data].[Feed Beta D9]> b"
					+ "\n  WHERE b.<delete where col D9b> > 0"
					+ "\n)"
					+ "\nDELETE FROM employees e"
					+ "\nUSING blended bl"
					+ "\nWHERE e.emp_id = bl.emp_id");
            }

@Test
            public void probedeleteComplexSubstitutionD10SubqueryGroupByHavingQualifyCombined() {
                runProbe("deleteComplexSubstitutionD10SubqueryGroupByHavingQualifyCombined", "DELETE FROM employees e"
					+ "\nUSING ("
					+ "\n  SELECT a.emp_id, sum(a.<delete select col D10>) AS total_score,"
					+ "\n         row_number() OVER (PARTITION BY a.emp_id ORDER BY a.<delete order col D10> DESC) AS rn"
					+ "\n  FROM <[Agg Data].[Fact Table D10]> a"
					+ "\n  WHERE a.<delete where col D10> > 0"
					+ "\n  GROUP BY a.emp_id, a.<delete group col D10>"
					+ "\n  HAVING sum(a.<delete select col D10>) > 0"
					+ "\n  QUALIFY rn = 1"
					+ "\n) src"
					+ "\nWHERE e.emp_id = src.emp_id");
            }

    private void runProbe(String name, String query) {
        SQLSelectParserParser parser = parse(query);
        SqlParseEventWalker extractor = runParsertest(query, parser);
        try {
            assertNoWalkerDiagnostics(extractor);
        } catch (AssertionError e) {
            System.out.println("DIAG_FAIL " + name);
            System.out.println("QUERY: " + query);
            System.out.println("FATAL: " + extractor.getSnippet().getFatalErrorStringList());
            System.out.println("ERROR: " + extractor.getSnippet().getErrorStringList(ParseDiagnostic.Severity.ERROR));
            System.out.println("WARN: " + extractor.getSnippet().getErrorStringList(ParseDiagnostic.Severity.SEVERE_WARNING));
            throw e;
        }
        System.out.println("GOLDEN_START " + name);
        System.out.println("AST: " + extractor.getAsTree());
        System.out.println("Interface: " + extractor.getInterface());
        System.out.println("Substitution Variables: " + extractor.getSubstitutionsMap());
        System.out.println("Table Dictionary: " + extractor.getTableColumnDictionaryMap());
        System.out.println("Query Column Dictionary: " + extractor.getQueryColumnDictionaryMap());
        System.out.println("Symbol Tree: " + extractor.getSymbolTable());
        System.out.println("GOLDEN_END " + name);
    }
}
