SELECT
        cast(alr_student.<Primary Student ID> AS varchar ) AS primary_student_id,
        cast(alr_student.<SIS Student ID> AS varchar) AS sis_student_id,
        cast(alr_student.<EAB Student ID> AS varchar) AS eab_student_id,
        cast(alr_student.<CRM Student ID> AS varchar) AS crm_student_id,
        cast(alr_student.<Other Student ID> AS varchar) AS other_student_id,
        cast(alr_student.FNAME AS varchar) AS fname,
        cast(alr_student.MNAME AS varchar) AS mname,
        cast(alr_student.LNAME AS varchar) AS lname,
        cast(alr_student.<Suffix> AS varchar) AS suffix,
        cast(alr_student.<Prefix> AS varchar) AS prefix,
        cast(alr_student.PREFERRED_FNAME AS varchar) AS preferred_fname,
        cast(alr_student.<US Citizenship Status> AS varchar) AS us_citizenship_status,
        cast(alr_student.INTERNATIONAL_IND AS varchar) AS international_ind,
        cast(alr_student.BIRTH_DT AS timestamp) AS birth_dt,
        cast(alr_student.<Gender> AS varchar) AS gender,
        cast(alr_student.PREF_GENDER AS varchar) AS pref_gender,
        cast(alr_student.<Religious Affiliation> AS varchar) AS religious_affiliation,
        cast(alr_student.HS_GRAD_YEAR AS varchar) AS hs_grad_year,
        cast(alr_student.origin_source AS varchar) AS origin_source, --made update
        cast(alr_student.ORIGIN_SOURCE_DT AS timestamp) AS origin_source_dt,
        cast(alr_student.FIRST_GEN_IND AS varchar) AS first_gen_ind,
        cast(alr_student.MILITARY_SERVICE_STATUS AS varchar) AS military_service_status,
        cast(alr_student.EAB_FIRST_GEN_IND AS boolean) AS eab_first_gen_ind,
        cast(alr_student.EAB_PREF_GENDER AS varchar) AS eab_pref_gender,
        cast(alr_student.EAB_INTERNATIONAL_IND AS boolean) AS eab_international_ind,
        cast(alr_student.EAB_MILITARY_VETERAN_IND AS boolean) AS eab_military_veteran_ind,
        cast(alr_student.ALUMNI_RELATION_IND AS varchar) AS alumni_relation_ind,
        cast(alr_student.EAB_ALUMNI_RELATION_IND AS boolean) AS eab_alumni_relation_ind,
        cast(alr_student.EAB_ETHNICITY AS varchar) AS eab_ethnicity,
        cast(alr_student.HISPANIC_IND AS varchar) AS hispanic_ind,
        cast(alr_student.<Ethnicity> AS varchar) AS ethnicity,
        cast(alr_student.CAMPUS_VISIT_CNT AS varchar) AS campus_visit_cnt,
        cast(alr_student.CAMPUS_VISIT_IND AS varchar) AS campus_visit_ind,
        cast(alr_student.FIRST_CAMPUS_VISIT_DT AS timestamp) AS first_campus_visit_dt,
        cast(alr_student.LAST_CAMPUS_VISIT_DT AS timestamp) AS last_campus_visit_dt,
        cast(alr_student.EAB_CAMPUS_VISIT_IND AS boolean) AS eab_campus_visit_ind,
        cast(alr_student.MAIL_OPTOUT_IND AS varchar) AS mail_optout_ind,
        cast(alr_student.EAB_MAIL_OPTOUT_IND AS boolean) AS eab_mail_optout_ind,
        cast(alr_student.EMAIL_OPTOUT_IND AS varchar) AS email_optout_ind,
        cast(alr_student.PHONE_OPTOUT_IND AS varchar) AS phone_optout_ind,
        cast(alr_student.SMS_OPTIN_IND AS varchar) AS sms_optin_ind,
        cast(alr_student.SMS_OPTOUT_IND AS varchar) AS sms_optout_ind,
        cast(alr_student.EAB_EMAIL_OPTOUT_IND AS boolean) AS eab_email_optout_ind,
        cast(alr_student.EAB_PHONE_OPTOUT_IND AS boolean) AS eab_phone_optout_ind,
        cast(alr_student.EAB_SMS_OPTIN_IND AS boolean) AS eab_sms_optin_ind,
        cast(alr_student.EAB_OPT_OUT_IND AS boolean) AS eab_opt_out_ind,
        cast(alr_student.OPT_OUT_IND AS varchar) AS opt_out_ind,
        cast(alr_student.<Intake Dt> AS timestamp) AS intake_dt
FROM
     <[ALR].[student].{final}> AS alr_student
WHERE alr_student.primary_student_id != '' AND alr_student.primary_student_id IS NOT NULL
UNION
SELECT
        par__student.primary_student_id AS primary_student_id,
        par__student.sis_student_id AS sis_student_id,
        par__student.eab_student_id AS eab_student_id,
        par__student.crm_student_id AS crm_student_id,
        par__student.other_student_id AS other_student_id,
        par__student.fname AS fname,
        par__student.mname AS mname,
        par__student.lname AS lname,
        par__student.suffix AS suffix,
        par__student.prefix AS prefix,
        par__student.preferred_fname AS preferred_fname,
        par__student.us_citizenship_status AS us_citizenship_status,
        par__student.international_ind AS international_ind,
        par__student.birth_dt AS birth_dt,
        par__student.gender AS gender,
        par__student.pref_gender AS pref_gender,
        par__student.religious_affiliation AS religious_affiliation,
        par__student.hs_grad_year AS hs_grad_year,
        par__student.origin_source AS origin_source,
        par__student.origin_source_dt AS origin_source_dt,
        par__student.first_gen_ind AS first_gen_ind,
        par__student.military_service_status AS military_service_status,
        par__student.eab_first_gen_ind AS eab_first_gen_ind,
        par__student.eab_pref_gender AS eab_pref_gender,
        par__student.eab_international_ind AS eab_international_ind,
        par__student.eab_military_veteran_ind AS eab_military_veteran_ind,
        par__student.alumni_relation_ind AS alumni_relation_ind,
        par__student.eab_alumni_relation_ind AS eab_alumni_relation_ind,
        par__student.eab_ethnicity AS eab_ethnicity,
        par__student.hispanic_ind AS hispanic_ind,
        par__student.ethnicity AS ethnicity,
        par__student.campus_visit_cnt AS campus_visit_cnt,
        par__student.campus_visit_ind AS campus_visit_ind,
        par__student.first_campus_visit_dt AS first_campus_visit_dt,
        par__student.last_campus_visit_dt AS last_campus_visit_dt,
        par__student.eab_campus_visit_ind AS eab_campus_visit_ind,
        par__student.mail_optout_ind AS mail_optout_ind,
        par__student.eab_mail_optout_ind AS eab_mail_optout_ind,
        par__student.email_optout_ind AS email_optout_ind,
        par__student.phone_optout_ind AS phone_optout_ind,
        par__student.sms_optin_ind AS sms_optin_ind,
        par__student.sms_optout_ind AS sms_optout_ind,
        par__student.eab_email_optout_ind AS eab_email_optout_ind,
        par__student.eab_phone_optout_ind AS eab_phone_optout_ind,
        par__student.eab_sms_optin_ind AS eab_sms_optin_ind,
        par__student.eab_opt_out_ind AS eab_opt_out_ind,
        par__student.opt_out_ind AS opt_out_ind,
        par__student.intake_dt AS intake_dt
FROM
     PDP_ALR_V2.par__student AS par__student
LEFT JOIN
     <[ALR].[student].{final}> AS alr__student
   ON   
     coalesce(par__student.primary_student_id, '') = coalesce(alr__student.<Primary Student ID>, '')
WHERE 
     alr__student.<Primary Student ID> IS NULL