-- added intake_dt for prooritization change - 11/15/2021 -Madhvi
select agg.sourcecontact_id,
agg.act_english_score,
agg.act_math_score,
agg.act_reading_score,
agg.act_science_score,
agg.act_writing_score,
agg.account_id,
agg.address_verified_indicator,
agg.all_colleges_of_interest,
agg.annual_family_income,
agg.areas_of_interest,
agg.areas_of_interest_cip_codes,
agg.cbo_list,
agg.candidate_order_id,
agg.candidate_sent_date,
agg.candidate_type,
agg.cappex_id,
agg.college_gpa,
agg.college_grad_month,
agg.college_grad_year,
agg.college_size_preferences,
agg.college_of_interest,
agg.colleges,
agg.composite_act_score,
agg.composite_sat_score,
agg.country_code,
agg.create_datetime,
agg.date_account_created,
agg.date_college_connection_created,
agg.date_inquiry_created,
agg.date_of_birth,
agg.desired_completion_timeframe,
CASE WHEN NULLIF(TRIM(agg.email_address),'') REGEXP '[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,3}' THEN TRIM(agg.email_address)
									   ELSE CONCAT(UUID_STRING(),'@test.eab.com')  END AS email_address,
agg.email_uuid,
agg.entry_term,
agg.entry_year,
agg.ethnicities,
agg.expected_college_grad_date,
agg.expected_entry_term,
agg.expected_time_commitments,
agg.expected_transfer_entry_term,
agg.first_name,
agg.freshman_match_indicator,
agg.gmat_score,
agg.gre_analytical_score,
agg.gre_quantitative_score,
agg.gre_verbal_score,
agg.gender,
agg.greenlight_match_indicator,
agg.high_school_grad_date,
agg.high_school_grad_month,
agg.high_school_grad_year,
agg.high_school_id,
agg.high_school_name,
agg.high_school_ceeb,
agg.inquiry_delivered_date,
agg.inquiry_is_delivered_ind,
agg.inquiry_subtype,
agg.inquiry_type,
agg.interested_in_aid_indicator,
agg.last_name,
agg.last_update_datetime,
agg.level_of_degree,
agg.major_cip_codes,
agg.major_names,
agg.open_to_transfer_indicator,
agg.psat_nmsqt_score,
agg.persona_types,
agg.phone,
agg.pre_act_score,
agg.record_source,
agg.record_source_detail,
agg.record_type,
agg.redacted_indicator,
agg.religion,
agg.sat_math_score,
agg.sat_read_write_score,
agg.selected_major,
agg.start_timeframe,
agg.student_age_at_time_of_connection,
agg.student_type,
agg.transfer_entry_term,
agg.transfer_entry_year,
agg.transfer_match_indicator,
agg.unweighted_gpa,
agg.years_of_work_experience
from (
  
select row_number() over (partition by all_cappex.cappex_id, all_cappex.record_type order by all_cappex.rn desc, all_cappex.last_update_datetime desc) rn2,
all_cappex.*
 from (
   	
    select 2 as rn, 
    <Cappex sourcecontact_id Hash> as sourcecontact_id,
	cappex__i.act_english as act_english_score,
	cappex__i.act_math as act_math_score,
	cappex__i.act_reading as act_reading_score,
	cappex__i.act_science as act_science_score,
	cappex__i.act_writing as act_writing_score,
	cappex__i.account_identifier as account_id,
	cappex__i.address_validated as address_verified_indicator,
	cappex__i.institutions_interested_in as all_colleges_of_interest,
	cappex__i.family_income_level as annual_family_income,
	cappex__i.intended_areas_of_study as areas_of_interest,
	cappex__i.intended_area_of_study_cip_families as areas_of_interest_cip_codes,
	cappex__i.cbo as cbo_list,
	cappex__i.candidate_order_id,
	cappex__i.candidate_sent_date,
	cappex__i.candidate_type,
	cappex__i.inquiry_id as cappex_id,
	cappex__i.college_gpa,
	cappex__i.college_grad_month,
	cappex__i.college_grad_year,
	cappex__i.college_size as college_size_preferences,
	cappex__i.institution_interested_in as college_of_interest,
	cappex__i.institutions_interested_in as colleges,
	cappex__i.act_composite as composite_act_score,
	cappex__i.sat_composite as composite_sat_score,
	cappex__i.phone_country_code as country_code,
	cappex__i.intake_dt as create_datetime,
	cappex__i.account_creation_date as date_account_created,
	cappex__i.connected_college_creation_date as date_college_connection_created,
	cappex__i.inquiry_creation_date as date_inquiry_created,
	cappex__i.birth_date as date_of_birth,
	cappex__i.desired_completion_timeframe as desired_completion_timeframe,
	cappex__i.email_address,
	cappex__i.email_uuid,
	cappex__i.college_start_term as entry_term,
	cappex__i.college_start_year as entry_year,
	cappex__i.student_ethnicities_list as ethnicities,
	cappex__i.expected_college_graduation_date as expected_college_grad_date,
	cappex__i.college_start_term as expected_entry_term,
	cappex__i.time_commitment as expected_time_commitments,
	cappex__i.expected_transfer_start_term as expected_transfer_entry_term,
	cappex__i.first_name,
	cappex__i.freshman_mvlp as freshman_match_indicator,
	cappex__i.gmat_total as gmat_score,
	cappex__i.gre_analytical_writing as gre_analytical_score,
	cappex__i.gre_quantitative_reasoning as gre_quantitative_score,
	cappex__i.gre_verbal_reasoning as gre_verbal_score,
	cappex__i.gender,
	cappex__i.greenlight_mvlp as greenlight_match_indicator,
	cappex__i.high_school_grad_date,
	cappex__i.high_school_grad_month,
	cappex__i.high_school_grad_year,
	cappex__i.high_school_id,
	cappex__i.high_school_name,
	cappex__i.high_school_ceeb_code as high_school_ceeb,
	cappex__i.inquiry_delivered_date,
	cappex__i.is_inquiry_delivered as inquiry_is_delivered_ind,
	cappex__i.inquiry_subtype,
	cappex__i.inquiry_type,
	cappex__i.interested_in_financial_aid as interested_in_aid_indicator,
	cappex__i.last_name,
	cappex__i.updated_on as last_update_datetime,
	cappex__i.level_of_degree_seeking as level_of_degree,
	cappex__i.student_college_major_cip_codes as major_cip_codes,
	cappex__i.intended_college_majors as major_names,
	cappex__i.transfer_student as open_to_transfer_indicator,
	cappex__i.psat_nmsqt as psat_nmsqt_score,
	cappex__i.personas as persona_types,
	cappex__i.phone,
	cappex__i.pre_act as pre_act_score,
	cappex__i.record_source,
	cappex__i.record_source_detail,
	cappex__i.record_type,
	cappex__i.account_redacted as redacted_indicator,
	cappex__i.religion,
	cappex__i.sat_math as sat_math_score,
	cappex__i.sat_read_write as sat_read_write_score,
	cappex__i.student_college_major_cip_codes as selected_major,
	cappex__i.start_timeframe,
	cappex__i.student_age_at_time_of_connection as student_age_at_time_of_connection,
	cappex__i.student_type,
	cappex__i.college_transfer_term as transfer_entry_term,
	cappex__i.college_transfer_year as transfer_entry_year,
	cappex__i.transfer_mvlp as transfer_match_indicator,
	cappex__i.high_school_gpa as unweighted_gpa,
	cappex__i.years_of_work_experience
	from <[Cappex].[Inquiries]> cappex__i
    left outer join
    (select cappex_id, record_type, cc_pdp.sourcecontact_id
	from PDP.lsc__cappex_contacts cc_pdp) cc_pdp
    on TO_VARCHAR(cappex__i.inquiry_id) = TO_VARCHAR(cc_pdp.cappex_id)
    and cappex__i.record_type = cc_pdp.record_type
	where coalesce(cappex__i.inquiry_type,'') || '*' || coalesce(cappex__i.record_type,'') <> 'Adult Learner*Inquiry'

	UNION ALL
	
	select 1 as rn, 
    cc_pdp.sourcecontact_id,
	cc_pdp.act_english,
	cc_pdp.act_math,
	cc_pdp.act_reading,
	cc_pdp.act_science,
	cc_pdp.act_writing,
	cc_pdp.account_id,
	cc_pdp.address_verified,
	cc_pdp.interested_institutions_list,
	cc_pdp.annual_family_income_level,
	cc_pdp.intended_areas_of_study_list,
	cc_pdp.intended_areas_of_study_cip_families_list,
	cc_pdp.cbo_list,
	cc_pdp.candidate_order_id,
	cc_pdp.candidate_sent_date,
	cc_pdp.candidate_type,
	cc_pdp.cappex_id,
	cc_pdp.college_gpa,
	cc_pdp.college_grad_month,
	cc_pdp.college_grad_year,
	cc_pdp.college_size_preference_list,
	cc_pdp.institution_interested_in,
	cc_pdp.interested_institutions_list,
	cc_pdp.act_composite,
	cc_pdp.sat_composite,
	cc_pdp.phone_country_code,
	cc_pdp.create_dt,
	cc_pdp.account_created_on_dt,
	cc_pdp.connected_college_created_on_dt,
	cc_pdp.inquiry_created_on_dt,
	cc_pdp.birth_date,
	cc_pdp.desired_completion_timeframe,
	cc_pdp.email,
	cc_pdp.email_uuid,
	cc_pdp.college_start_term,
	cc_pdp.college_start_year,
	cc_pdp.ethnicity_list,
	cc_pdp.expected_college_grad_date,
	cc_pdp.college_expected_start,
	cc_pdp.desired_completion_timeframe,
	cc_pdp.expected_transfer_start_term,
	cc_pdp.first_name,
	cc_pdp.is_freshman_match_ind,
	cc_pdp.gmat_total,
	cc_pdp.gre_analytical_writing,
	cc_pdp.gre_quantitative_reasoning,
	cc_pdp.gre_verbal_reasoning,
	cc_pdp.gender,
	cc_pdp.is_greenlight_match_ind,
	cc_pdp.high_school_grad_date,
	cc_pdp.high_school_grad_month,
	cc_pdp.high_school_grad_year,
	cc_pdp.high_school_id,
	cc_pdp.high_school,
	cc_pdp.high_school_ceeb_code,
	cc_pdp.inquiry_delivered_date,
	cc_pdp.Inquiry_is_delivered_ind,
	cc_pdp.inquiry_sub_type,
	cc_pdp.inquiry_type,
	cc_pdp.interested_in_financial_aid_ind,
	cc_pdp.last_name,
	cc_pdp.updated_on_dt,
	cc_pdp.level_of_degree_seeking,
	cc_pdp.major_cip_code,
	cc_pdp.intended_college_majors_list,
	cc_pdp.open_to_transfer_ind,
	cc_pdp.psat_nmsqt,
	cc_pdp.persona_type_list,
	cc_pdp.phone,
	cc_pdp.pre_act,
	cc_pdp.record_source,
	cc_pdp.record_source_detail,
	cc_pdp.record_type,
	cc_pdp.is_redacted_ind,
	cc_pdp.religion,
	cc_pdp.sat_math,
	cc_pdp.sat_read_write,
	cc_pdp.intended_college_major_cip_code_list,
	cc_pdp.start_timeframe,
	cc_pdp.student_age_at_time_of_connection,
	cc_pdp.student_type,
	cc_pdp.college_transfer_term,
	cc_pdp.college_transfer_year,
	cc_pdp.is_transfer_match_ind,
	cc_pdp.gpa_unweighted,
	cc_pdp.years_of_work_experience
	FROM PDP.lsc__cappex_contacts cc_pdp
  
	) all_cappex
  ) agg
where agg.rn2 = 1